- hack/make/.validate
- hack/make/validate-gofmt
- hack/make/validate-lint
- hack/make/validate-vet
Validating only committed files is not useful in the natural
>  $test_everything_passes; commit; push
workflow; the failures will not be caught locally, only by Travis later (and only if PRs are used instead of direct commits to master).
So, use the working directory state instead of last commit for validations; and remove misleading comments in checks which already use the working directory state.
> Use contents of local checkout instead of last commit for validation

- .travis.yml
- Makefile
There haven’t been any unit tests in the code base so far; after adding them,
- Just running them is more difficult than `go test .`, so `Makefile` targets are useful.
- A full test run (Docker,Travis,non-Docker) now means validate+unit+integration tests, and it is easy to forget one or more; so, this adds new all-in-one `Makefile` targets.
- Travis should run the unit tests; by using the all-in-one target we get this for free.
- IDEs should be able to run the tests; this adds a demo for VS Code
The VS Code aspect is honestly a bit dubious; I’ll gladly drop it if you think it does not belong upstream.
> Add infrastructure for running unit tests

- hack/.vendor-helpers.sh
- vendor/github.com/codegangsta/cli/README.md
- vendor/github.com/codegangsta/cli/app.go
- vendor/github.com/codegangsta/cli/help.go
- vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go
- vendor/golang.org/x/net/context/context.go
Otherwise the `clean` step of `hack/vendor.sh` would drop most `.go` files from `vendor/` as unused.
Also commits refreshed versions of a few of the vendored packages.
> Fix hack/.vendor-helper.sh for main package move.

- integration/signing_test.go
If executing the command fails, the output to stderr is more useful than
the exit code, so test the output first.
> Test command output before eror status in signing integration tests

- cgo_pthread_ordering_workaround.go
See detailed explanation inside the added file.
If you want to reproduce this, add an use of the `net` package somewhere early in the `main` package, and `sudo make check` (ensuring that your `fedora` image is Fedora 23).
> Add a workaround for a glibc bug when -lphtread precedes -lgpgme

- docker.go
> docker.go: do not concatenate url in ping

- directory.go
- docker.go
- types/types.go
`docker.go` is currently doing everything related to Docker images. To better support the Docker Registry, Atomic Registry, `docker save,load}` tarballs, and local directories (for debugging) in the future, introduce `ImageSource` and `ImageDestination` as abstractions of dumb storage which does not modify its contents.
Currently the only implementations are the existing ones, Docker Registry `dockerImageSource` and a local directory (`dirImageSource`, `dirImageDestination`). The `dockerImage` struct remains, as a layer on top of `dockerImageSource`; eventually this should probably be restructured further (e.g. `dockerImage.Layers` should probably mostly happen in the top-level `layers.go`, so that we don’t hard-code creation of random-named directories in the current directory).
> Add ImageSource and ImageDestination abstractions

- vendor/github.com/mtrmac/gpgme/go_gpgme.h
In particular, https://github.com/proglottis/gpgme/pull/8 .
This fixes a RHEL 7 build failure: https://github.com/projectatomic/skopeo/pull/45#issuecomment-217576783 . I apologize again.
> Rerun hack/vendor.sh to pick up gpgme changes

- man1/skopeo.1
Signed-off-by: Jhon Honce <jhonce@redhat.com>
> Correct man page formatting

- cmd/skopeo/copy.go
The `dir:` source type does not return the value, the value is
untrusted/not validated, and it is not at all clear why we should print
it in the first place.
> Don‘t write the mainfest digest on stdout in (skopeo copy)

- signature/json.go
- signature/json_test.go
- signature/mechanism.go
- signature/signature.go
- signature/signature_test.go
Splitting from the main policy work for easier review. This should not change behavior at all, only moving some utilities into a separate file, adding comments, some trivial cleanups.
> signature cleanups

- cmd/skopeo/copy.go
- cmd/skopeo/utils.go
- directory/directory.go
- docker/docker_client.go
- docker/docker_image.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- docker/docker_utils.go
- openshift/openshift-copies.go
- openshift/openshift.go
Does not change behavior.  This is a straightforward move and update of package references, except for:
- Adding a duplicate definition of `manifestSchema1` to `cmd/skopeo/copy.go`.  This will need to be cleaned up later, for now preferring to make no design changes in this commit.
- Renaming `parseDockerImage` to `NewDockerImage`, to both make it public and consistent with common golang conventions.
> Move directory, docker and openshift from cmd/skopeo to their own subpackages

- cmd/skopeo/inspect.go
- directory/directory.go
- docker/docker_image.go
- docker/docker_image_src.go
- openshift/openshift.go
- types/types.go
This adds methods useful for validating signatures to `types.Image`, namely the ability to retrieve signatures, and the supposedly signed identity, and renames `RawManifest` for consistency.
The implementation remains Docker-specific (in particular, not usable for OpenShift), but having the type and API will allow the policy evaluation code to compile, which is on my critical path now.
See comments in the individual commits for details.
> API for signatures

- cmd/skopeo/inspect.go
- directory/directory.go
- docker/docker_image.go
- docker/docker_image_src.go
- openshift/openshift.go
- types/types.go
> API for signatures - drop Get prefixes on quick getters

- cmd/skopeo/copy.go
- cmd/skopeo/inspect.go
- directory/directory.go
- docker/docker_image.go
- docker/docker_image_src.go
- openshift/openshift.go
- types/types.go
This is a follow-up to #57, I will rebase as needed.
This somewhat cleans up `types.Image` towards becoming the primary inspection endpoint for images:
- We can now change the API without breaking `skopeo inspect` output format
- `Image.Manifest` turns into `Image.Inspect`, which parses the manifest, config and layers only; its other former functions are split into new methods.
- Added comments on how the API types are expected to be used.
This does not yet completely clean up the API (e.g. moving parts of `Layers` to `cmd/skopeo`).
Nor does this make `Image` independent of the underlying Docker implementation yet: (`InspectInfo.Name` returns the parsed Docker ref, and `GetRepositoryTags` needs a Docker client). Non-Docker replacements for this mostly depend on what values we define …
> General image API cleanups

- docker/docker_client.go
- docker/docker_image_dest.go
There's currently no way to pass more values for a single header, this fixes it
@mtrmac PTAL
> provide a way to pass multi values-signle key headers

- cmd/skopeo/copy.go
- directory/directory.go
- docker/docker_image.go
- docker/docker_image_src.go
- openshift/openshift.go
- types/types.go
This is tough, but as a user of skopeo libraries/pkgs I wish to be able to provide a list of mime types which I wish to get back (in order). Then I can check the returned mime type to understand it.
@mtrmac PTAL
> add the possibility to choose image's MIME type

- docker/utils/manifest.go
- docker/utils/manifest_test.go
As opposed to callers just calling `utils.ManifestDigest(image.Manifest())`, this is a forward-compatible interface, allowing other digest algorithms to be added in the future.
Right now, we only support SHA-256, so the underlying implementation does not change anything.
> Add docker/utils.ManifestMatchesDigest

- docker/docker_client.go
- docker/docker_image_dest.go
Implement a client to the chunked API, instead of the nonexistent one-shot API (per https://github.com/docker/distribution/commit/2a4deee4413a4027b3024113a2c880e217097754 ).
Adds a FIXME to DELETE the pending upload on failure; the uploads are supposed to time out so this is not immediately critical.
Fixes #64 .
> Fix uploading layer blobs to Docker registry

- cmd/skopeo/delete.go
- cmd/skopeo/main.go
- directory/directory.go
- docker/docker_image_src.go
- man1/skopeo.1
- openshift/openshift.go
- types/types.go
Add support to mark images for deletion from repository
Requires:
* V2 API and schema
* registry configured to allow deletes
* run registry garbage collection to free up disk space
Signed-off-by: Jhon Honce <jhonce@redhat.com>
> Card container_security_113 - Delete image support

- cmd/skopeo/inspect.go
- cmd/skopeo/utils.go
- docker/docker_image.go
- image/image.go
- signature/policy_eval_signedby_test.go
Signature verification in `skopeo --policy … copy` requires a `types.Image`, making `docker.GenericImageFromSource` increasingly awkward. Clean this up by moving the `genericImage` code into a separate `skopeo/image` subpackage.
See individual commits for more detailed comments.
> Move docker.genericImage to a separate skopeo/image subpackage

- cmd/skopeo/copy.go
- directory/directory.go
- docker/docker_image_dest.go
- docker/docker_image_src.go
- image/image.go
- openshift/openshift.go
- types/types.go
preparation for https://trello.com/c/hhK1klNW/143-skopeo-pull-from-docker-and-convert-to-oci
This is actually needed because to convert to OCI image's manifest we also need to fetch the *config* from a v2s2 manifest which is referenced just a normal blob
> Generalize [Get|Put]Layer

- .gitignore
`/skopeo.1` was a generated file before #35; now this path is not used (replaced by `man1/skopeo.1`); if the generated file is left around, it is obsolete (and confusingly empty).  Remove it from `.gitignore` to nudge developers like me to clean up.
> Remove /skopeo.1 from .gitignore

- cmd/skopeo/inspect.go
- cmd/skopeo/main.go
- cmd/skopeo/main_test.go
- cmd/skopeo/signing.go
Instead of each command handler terminating the process, let it return
an error object, and terminate the process at the top level.
See https://github.com/mtrmac/skopeo/commit/3ccea6cdeaf7e375c50a907b7a709da2f184a5ae for usage.
This will need to be extended to also capture stdout/stderr.
> Support for in-process command testing

- cmd/skopeo/copy.go
- cmd/skopeo/layers.go
- image/image.go
- image/image_test.go
- signature/policy_reference_match_test.go
- types/types.go
See individual commits for detailed comments.
> Move parsing layer digests from copy.go to types.Image

- Dockerfile.build
- Makefile
- hack/make/test-integration
so that people don't need to install all dependencies just to build.
Make it so that "make binary" does nothing if nothing changed.
Also use ${DEST} in a few more spots for consistency
Signed-off-by: Doug Davis <dug@us.ibm.com>
> Build binary in a docker container

- cmd/skopeo/main.go
- integration/check_test.go
Clearly wrong (from containers/image):
```bash
$./skopeo --version
skopeo version 0.1.0-dev commit: 6d7c93acf7bc380d5c0c51aa0a5788cc99810df0
$ ./skopeo --version
skopeo version 0.1.14-dev commit: 6d7c93acf7bc380d5c0c51aa0a5788cc99810df0
```
> cmd: skopeo: fix version

- Dockerfile
I don’t know how to checkout a specific untagged commit ( 9ff4bf43548c758b6767b639b335681285fece48 ) from the original repo, so I have forked the project and fetched that commit from a cached Docker image.
We should instead update the containers/image client for the new API ASAP, and then the github.com/mtrmac/origin repo should be removed.
> Keep using an old version of https://github.com/openshift/origin/pull/9181

- cmd/skopeo/copy.go
- cmd/skopeo/inspect.go
- cmd/skopeo/layers.go
- cmd/skopeo/utils.go
- integration/copy_test.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/docker/docker_image.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/image/image.go
- vendor/github.com/containers/image/manifest/manifest.go
- vendor/github.com/containers/image/oci/oci_dest.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/types/types.go
replacement for #102 - currently blocked on containers/image#23 bits (this branch contains code from containers/image#23 from my personal fork) 
/cc @mtrmac 
> add possibility to download to OCI image-layout

- integration/check_test.go
This fixes `--version` integration test on CentOS, as noticed by https://github.com/projectatomic/skopeo/pull/91 .  The underlying cause is:
- `Makefile` builds with `-ldflags "-X var=value"`, while go 1.4.2 only supports `"-X var value"`.  This  auses CentOS builds to be built without the specific commit information
- The `--version` integration test assumes that commit information will always follow the version number.
Changing either one of these would fix the build, changing the integration test has the advantage that we don't have to use the obsolete `-X` syntax and suffer warnings on newer Go versions.
> Fix integration tests on CentOS

- cmd/skopeo/copy.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/directory/directory_src.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/docker/docker_utils.go
- vendor/github.com/containers/image/image/image.go
- vendor/github.com/containers/image/oci/oci_dest.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/signature/policy_eval.go
- vendor/github.com/containers/image/signature/policy_reference_match.go
- vendor/github.com/containers/image/types/types.go
- vendor/github.com/docker/libtrust/README.md
This pulls in mtrmac/image:docker-references and updates for the API change, to demonstrate things working.
Do not merge as is, I will re-vendor from the master branch after merging the other PR.
> Clean up Docker reference handling

- cmd/skopeo/copy.go
- cmd/skopeo/layers.go
- cmd/skopeo/utils.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/directory/directory_src.go
- vendor/github.com/containers/image/directory/directory_transport.go
- vendor/github.com/containers/image/docker/docker_image.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/docker/docker_transport.go
- vendor/github.com/containers/image/docker/docker_utils.go
- vendor/github.com/containers/image/image/image.go
- vendor/github.com/containers/image/oci/oci_dest.go
- vendor/github.com/containers/image/oci/oci_transport.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/openshift/openshift_transport.go
- vendor/github.com/containers/image/signature/policy_eval.go
- vendor/github.com/containers/image/signature/policy_eval_simple.go
- vendor/github.com/containers/image/signature/policy_reference_match.go
- vendor/github.com/containers/image/transports/transports.go
- vendor/github.com/containers/image/types/types.go
This pulls, in and updates for, https://github.com/containers/image/pull/39 .
> Reference abstraction

- cmd/skopeo/copy.go
- cmd/skopeo/copy_test.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/directory/directory_transport.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/oci/oci_dest.go
- vendor/github.com/containers/image/oci/oci_transport.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/types/types.go
This adds verification of blobs against the expected digests as they are being copied.
Depends on https://github.com/containers/image/pull/48 , I will revendor after it is merged.
> Verify blobs

- Makefile
This ensures that we are not installing e.g. an obsolete version of the man page after the Markdown version is updated.
Note that this greatly benefits from the `skopeo` target being non-phony, otherwise `(make install)` would rebuild the binary.
> Make the install-* targets depend on things they are installing

- cmd/skopeo/fixtures/v2s1-invalid-signatures.manifest.json
- cmd/skopeo/inspect.go
- cmd/skopeo/main.go
- cmd/skopeo/manifest.go
- cmd/skopeo/manifest_test.go
- docs/skopeo.1.md
- Modify `skopeo inspect --raw` to output an _unmodified_ manifest.
- Provide `skopeo manifest-digest $manifest_file` to compute a manifest digest, including the v2s1 signature stripping.
Both will be called by `atomic`.
> Improve manifest digest handling

- Makefile
- cmd/skopeo/main.go
- hack/make/bash_autocomplete
This PR adds the first level skopeo commands as bash auto completions.
Partially addresses issue #4 
This is to test the waters for the simple bash completions. Can add bash completion functions for skopeo command parameters and zsh completions (if folks want those too) in subsequent PR(s). 
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
> add support for completions

- Makefile
- cmd/skopeo/copy.go
- cmd/skopeo/main.go
- default-policy.json
- docs/skopeo.1.md
- hack/make/test-integration
- vendor/github.com/containers/image/docker/docker_transport.go
- vendor/github.com/containers/image/oci/oci_transport.go
- vendor/github.com/containers/image/openshift/openshift_transport.go
- vendor/github.com/containers/image/signature/policy_config.go
- vendor/github.com/containers/image/types/types.go
- vendor/github.com/davecgh/go-spew/LICENSE
Adds `/etc/atomic/policy.json`, and a command-line option to override (`skopeo --policy some_path copy …`), and enforces this policy in `skopeo copy`.
`make install` now installs `default-policy.json` to `/etc/atomic/policy.json`; the policy is set to `insecureAcceptAnything` for all images by default. (This may not be desirable long-term, but it is a reasonable transition strategy for now I think. The policy always uses the most specific matching scope, so it is easy to e.g. pin a key and require signatures for a specific repository namespace.)
Note that with merging this, `./skopeo` will abort if the policy in `/etc/atomic` does not exist. This should not affect real deployments, but may be noticeable with local checkouts. A bit regrettable, but we do need to fail closed if a policy …
> Verify signatures on pull

- integration/copy_test.go
- integration/fixtures/policy.json
- integration/openshift.go
This includes https://github.com/projectatomic/skopeo/pull/146 and https://github.com/projectatomic/skopeo/pull/157 (I will rebase after those are merged), and adds integration tests for the signature and policy handling by `skopeo copy`.
> Copy signing integration tests

- cmd/skopeo/copy.go
- docs/skopeo.1.md
- vendor/github.com/containers/image/copy/copy.go
This exposes https://github.com/containers/image/pull/68, and is necessary to allow copying signed images into destinations which don't support signatures.
(We could instead silently drop signatures when copying into such destinations, I think that is worse. `atomic pull` can easily hard-code `skopeo copy --remove-signatures docker://$source docker-daemon:$destination` when we know that `docker-daemon:` doesn’t support signatures; after we add such support, we would drop the option from `atomic`.)
> Add --remove-signatures to (skopeo copy)

- cmd/skopeo/main.go
- cmd/skopeo/utils.go
- docs/skopeo.1.md
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/docker/lookaside.go
- vendor/github.com/containers/image/types/types.go
- vendor/github.com/docker/distribution/reference/reference.go
This vendors in unmerged https://github.com/containers/image/pull/52 and updates the API usage.  See the documentation in that PR for more details.
> Implement a lookaside storage for signatures of images in Docker registries

- Makefile
Per recent conversations; to make it easier to place the registries `.yaml` files into the correct place, and to avoid the question of what happens when the directory is missing.
Cc @lsm5 .
> Create /etc/containers/registries.d in (make install)

- cmd/skopeo/main.go
- cmd/skopeo/utils.go
- docs/skopeo.1.md
- integration/check_test.go
- integration/copy_test.go
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/types/types.go
Depends on https://github.com/containers/image/pull/87 .
- Flip `--tls-verify` default to true    
- Document better what `--tls-verify` does
- ... and sprinkle `--tls-verify=false` over integration tests.
cc @baude
> TLS verification in docker registries

- README.md
- version/version.go
as soon as of all the deps are fixed /cc @mtrmac @rhatdan I'll tag https://github.com/projectatomic/skopeo/pull/217/commits/584f3c24e813b82805ef7933424424618c9d8155 as 0.1.15 once this is merged
/cc @lsm5 to rebuild on F25/Rawhide once I tag a new release
> Bump to 0.1.15 and then again to 0.1.16-dev

- integration/copy_test.go
- integration/fixtures/policy.json
- integration/fixtures/registries.yaml
- integration/registry.go
This includes https://github.com/projectatomic/skopeo/pull/170 , and adds integration tests for it.
Sadly, those tests depend on something like https://github.com/mtrmac/image/tree/docker-push-to-tag to support reasonable pushing to Docker registries, and that is not really ready. (Though perhaps it could be argued that it is better than status quo already?)
> Docker lookaside tests

- integration/copy_test.go
- vendor/github.com/containers/image/copy/copy.go
- vendor/github.com/containers/image/directory/directory_src.go
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/image/docker_list.go
- vendor/github.com/containers/image/image/image.go
- vendor/github.com/containers/image/manifest/manifest.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/types/types.go
specifically https://github.com/containers/image/pull/115 and also add an integration test
> vendor containers/image

- Makefile
- default.yaml
@mtrmac @baude PTAL
We'll soon ship a skopeo sub-pkg which will just contain `/etc/containers/policy.json` and `/etc/containers/registries.d/default.yaml` so that docker (after projectatomic/docker#200) and atomic can require it in their spec w/o having N specs shipping those files.
> add sigstore default configuration

- cmd/skopeo/layers.go
As title says. @mtrmac PTAL
@giuseppe I know you're using `skopeo layers` in your sys containers, would be nice to migrate that to `mkdir dir && skopeo copy docker://image_name dir:here_are_the_layers`
> Fix skopeo layers and deprecate it

- Dockerfile.build
- Makefile
I want to run `skopeo` on CentOS with low glibc version, so static compile is better for me.
Signed-off-by: Ye Yin <eyniy@qq.com>
> Add static compile target in Makefile

- Makefile
Both `make binary` and `make binary-static` compile the code and create a skopeo binary, so `make all` should only depend on one of them.
> Only build one skopeo binary by (make all)

- Dockerfile
Newer docker version (> 1.12.x) now perform a pre-build syntax check. Inline comments are no longer allowed.
> Dockerfile: remove inline comments

- README.md
- cmd/skopeo/copy.go
- cmd/skopeo/delete.go
- cmd/skopeo/inspect.go
- cmd/skopeo/main.go
- cmd/skopeo/utils.go
- docs/skopeo.1.md
- integration/check_test.go
- integration/copy_test.go
- vendor/github.com/containers/image/copy/copy.go
We already use global flags for docker specific stuff. This patch enables `--username` and `--password` to be passed down to `containers/image` to setup docker's registries auth.
Fixes #253 
@mtrmac @cyphar PTAL
> use user/pass flags

- vendor/github.com/containers/image/copy/copy.go
- vendor/github.com/containers/image/docker/daemon/daemon_types.go
- vendor/github.com/containers/image/image/docker_schema1.go
- vendor/github.com/containers/image/image/manifest.go
- vendor/github.com/containers/image/types/types.go
Forgot to fix and revendor c/image in #254 - this also vendor `string->digest.Digest` conversion.
> revendor containers/image

- cmd/skopeo/layers.go
- hack/vendor.sh
- vendor/github.com/containers/image/copy/copy.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/directory/directory_src.go
- vendor/github.com/containers/image/docker/daemon/daemon_dest.go
- vendor/github.com/containers/image/docker/daemon/daemon_src.go
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/image/docker_schema2.go
- vendor/github.com/containers/image/manifest/manifest.go
- vendor/github.com/containers/image/oci/layout/oci_dest.go
- vendor/github.com/containers/image/oci/layout/oci_src.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/types/types.go
Based on https://github.com/containers/image/pull/147
> Support layers federation

- Dockerfile
This reverts commit 3dcdb1ff7d2360419c29c24e4032b7852aee3c26.
Upstream fix: https://github.com/docker/docker/pull/29006
> Revert "Dockerfile: remove inline comments"

- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/image/docker_schema1.go
- vendor/github.com/containers/image/image/docker_schema2.go
- vendor/github.com/containers/image/image/manifest.go
- vendor/github.com/containers/image/image/oci.go
- vendor/github.com/containers/image/oci/layout/oci_dest.go
- vendor/github.com/containers/image/types/types.go
This updates `containers/image` to be newer. In particular, it pulls in the recent changes I've made related to OCI images and being able to adequately convert OCI images to Docker images. Is it possible for us to tag a new release of skopeo after this is merged? It will make the maintenance burden of skopeo for openSUSE much easier (I'm currently backporting all of my OCI changes).
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> vendor: update to containers/image@a791c5446737

- Makefile
Run the "go" command with the $(BUILDTAGS) makefile variable passed in as build tags.  We don't currently set it, but we'll need to eventually, and adding it now does no harm.
> Makefile: run "go" with $(BUILDTAGS)

- version/version.go
I'll tag `v0.1.17` the following commit: https://github.com/runcom/skopeo-1/commit/b3b4e2b8f8cebba9a9fe50e8e9c6cf4fe600c448
> Bump v0.1.17 and again to v0.1.18-dev

- cmd/skopeo/signing_test.go
With https://github.com/containers/image/pull/183 , this no longer applies.
> Remove an obsolete FIXME

- Makefile
When user installed go-md2man via `go get`, it is unlikely to be installed as `/usr/bin/go-md2man`.
So I suggest changing `/usr/bin/go-md2man` to just `go-md2man`.
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
> Makefile: /usr/bin/go-md2man -> go-md2man

- Dockerfile
- integration/copy_test.go
- integration/openshift.go
- integration/utils.go
This updates OpenShift from 1.3.0-alpha.3 to 1.5.0-alpha.3.
More detailed description is in the individual commit messages.
> Update OpenShift in integration tests to get the docker/distribution API extensions

- cmd/skopeo/inspect.go
- completions/bash/skopeo
- integration/check_test.go
A wrong name of this parameter prevents it from being used for the context (and at all). This is also different than the docs.
> Fix wrong naming of cert-dir argument in inspect command

- cmd/skopeo/main.go
- completions/bash/skopeo
- docs/skopeo.1.md
This PR is merely a rebase of #203, whose submitter needed to rebase their PR.
I resolved a trivial merge conflict to rebase, and the flag works as advertised.
I'm assuming that the previous agreement on the flag name,  `--insecure-policy`, is still valid, and I updated the bash completion and man page accordingly. Let me know if there's anywhere else :)
Original submission follows:
> This patch adds a new flag --insecure-policy.
> Closes #181, we can now directly use the tool with the
> above mentioned flag wihout using a policy file
> 
> Signed-off-by: Kushal Das <mail@kushaldas.in>
> Insecure policy flag redux

- integration/openshift_shell_test.go
We are maintaining code to set up and run registries, including the fairly complex setup for Atomic Registry, in the integration tests. This is all useful for experimentation in shell, and the easiest way to
do that is to add a “test” which, after all the set up is done, simply starts a shell.
Obviously this is commented out and thus does not affect ordinary test runs.
A possible alternative would be to convert all of the setup code not to depend on `check.C` and `testing.T`, but that would be fairly cumbersome due to how prevalent `c.Logf` and `c.Assert` are throughout the setup code. Especially the natural replacement of `c.Assert` with a `panic()` would be
pretty ugly, and adding real error handling to all of that would make the code noticeably longer.  Commenting/uncommenting a …
> Add a commented-out CopySuite.TestRunShell

- integration/copy_test.go
- Uncomment an `os.RemoveAll(tmpDir)`
- Remove a copy&pasted comment
> Trivial bug fixes to `CopySuite.TestCopyDockerSigstore`

- vendor/github.com/containers/image/docker/lookaside.go
- vendor/k8s.io/client-go/README.md
This demonstrates https://github.com/containers/image/pull/247 .  There is a `TestCopyDockerSigstore` which tests that the write staging / read HTTP paths for a sigstore are interoperable, but it does not prescribe a specific layout, so it does not need updating.
> Vendor mtrmac/image:change-sigstore-layout

- vendor/github.com/containers/image/copy/copy.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/docker/daemon/daemon_dest.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/docker/lookaside.go
- vendor/github.com/containers/image/image/docker_schema1.go
- vendor/github.com/containers/image/image/docker_schema2.go
- vendor/github.com/containers/image/image/manifest.go
- vendor/github.com/containers/image/image/oci.go
- vendor/github.com/containers/image/oci/layout/oci_dest.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/storage/storage_image.go
- vendor/github.com/containers/image/types/types.go
Depends on https://github.com/containers/image/pull/259
This PR just revendor c/image w/o touching anything in skopeo
@mtrmac ptal
> revendor c/image for OCIConfig

- cmd/skopeo/copy.go
- cmd/skopeo/utils.go
- completions/bash/skopeo
- docs/skopeo.1.md
- vendor/github.com/containers/image/ostree/ostree_dest.go
- vendor/github.com/containers/image/ostree/ostree_transport.go
- vendor/github.com/containers/image/transports/alltransports/alltransports.go
- vendor/github.com/containers/image/types/types.go
Currently blocked on: https://github.com/containers/image/pull/228
> skopeo: support copy to OSTree storage

- integration/copy_test.go
- integration/openshift.go
- integration/utils.go
- vendor/github.com/containers/image/copy/copy.go
- vendor/github.com/containers/image/copy/manifest.go
- vendor/github.com/containers/image/copy/sign.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/tarfile/dest.go
- vendor/github.com/containers/image/oci/layout/oci_dest.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/ostree/ostree_dest.go
- vendor/github.com/containers/image/storage/storage_image.go
- vendor/github.com/containers/image/types/types.go
This vendors in https://github.com/containers/image/pull/264 and adds integration tests for it.
See the individual commit messages for more details.
Note that the added integration test currently tests OpenShift with `acceptschema2:{true,false}`; a test against upstream docker/distribution registries (with the s2 and s1 versions already built by `Dockerfile`) exists, but is disabled because it fails—not on the s2→s1 conversion, but on s1→s1 copies: the s1-only registry requires updating the tag value, which we currently don’t do.
Updating the tag in s1 uploads is actually ready in  https://github.com/containers/image/pull/88 , but it breaks other integration tests (which incorrectly assume that s1 uploads don’t change the manifest) fairly badly, so we will need to update the other tests …
> Run-time manifest type support (e.g. schema1/schema2) autodetection re-vendor + integration tests

- integration/copy_test.go
- integration/fixtures/policy.json
- integration/registry.go
- vendor/github.com/containers/image/copy/copy.go
- vendor/github.com/containers/image/image/docker_schema1.go
- vendor/github.com/containers/image/image/docker_schema2.go
- vendor/github.com/containers/image/image/manifest.go
- vendor/github.com/containers/image/image/oci.go
- vendor/github.com/containers/image/types/types.go
This vendors in https://github.com/containers/image/pull/88 , updates tests to pass now that schema1 manifests are being modified by the upload, and enables several tests which were previously broken by our incorrect schema1 support.  Fixes #290 .
Similarly to https://github.com/containers/image/pull/88, depends on, and includes, #336. I will rebase as necessary.
See the individual commit messages for more details.
> Update name/tag embedded into schema1 manifests

- Dockerfile
- integration/check_test.go
- integration/registry.go
- integration/signing_test.go
This moves various setup steps from `SetUpTest` to `SetUpSuite` so that we don’t start up processes over and over; that is _slightly_ less reliable, but more efficient.
Also increases the registry startup timeout from 0.5 to 5 seconds, hopefully avoiding some CI flakes.
Finally, completely stops starting some of the registries which we don’t use, with an `if false` to keep the existing code structure. (Alternatively we could drop that, and stop building the docker/registry code altogether.
> Simplify infrastructure setup, and make registry timeouts less strict

- Dockerfile.build
From the [docs](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#build-cache) in March 2017:
Always combine `RUN apt-get update` with `apt-get install` in the same  RUN statement, for example
`RUN apt-get update && apt-get install -y package-bar`
Using `apt-get update` alone in a RUN statement causes caching issues and subsequent` apt-get install `instructions fail.
Signed-off-by: Jing Qiu <aqiu0720@gmail.com>
> Always combine RUN apt-get update with apt-get install in the same RUN statement.

- README.md
Two more packages are needed to locally build skopeo on fedora viz. btrfs-progs-devel & device-mapper-devel, so added them in README.
Signed-off-by: Suraj Deshmukh <surajssd009005@gmail.com>
> docs(README): add build dependencies for fedora

- Dockerfile.build
ubuntu 16.04 have not package `libostree-dev`. also, we should
install `libglib2.0-dev` package when build skopeo with command `make binary`.
Signed-off-by: 0x0916 <w@laoqinren.net>
> Dockerfile.build: using ubuntu 17.04

- integration/copy_test.go
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/oci/layout/oci_dest.go
- vendor/github.com/containers/image/oci/layout/oci_transport.go
- vendor/github.com/containers/image/vendor.conf
The oci name changes in containers/image https://github.com/containers/image/pull/318 caused the skopeo test to fail
Signed-off-by: umohnani8 <umohnani@redhat.com>
> Modify skopeo tests

- cmd/skopeo/layers.go
- cmd/skopeo/utils.go
- vendor/github.com/containers/image/copy/copy.go
- vendor/github.com/containers/image/directory/directory_transport.go
- vendor/github.com/containers/image/docker/archive/transport.go
- vendor/github.com/containers/image/docker/daemon/daemon_transport.go
- vendor/github.com/containers/image/docker/docker_image.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/docker/docker_transport.go
- vendor/github.com/containers/image/oci/archive/oci_src.go
- vendor/github.com/containers/image/oci/archive/oci_transport.go
- vendor/github.com/containers/image/oci/layout/oci_transport.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/openshift/openshift_transport.go
- vendor/github.com/containers/image/ostree/ostree_transport.go
- vendor/github.com/containers/image/storage/storage_reference.go
- vendor/github.com/containers/image/types/types.go
This makes skopeo compile (and pass tests) with the change to ImageReference.NewImageSource in https://github.com/containers/image/pull/338
> Update for removal of requestedMIMETypes from ImageReference.NewImageSource()

- cmd/skopeo/delete.go
- cmd/skopeo/layers.go
make lint is complaining for cases where the error returned is checked
for err != nil, and then returned anyways.
Needed for https://github.com/containers/image/pull/333
Signed-off-by: umohnani8 <umohnani@redhat.com>
> fixing error checking due to update in make lint

- Makefile
This will allow compilation with a custom go binary,
for example /usr/lib/go-1.8/bin/go instead of /usr/bin/go on Ubuntu
16.04 which is still version 1.6
@mtrmac @runcom ptal
> use Makefile var for go compiler

- Makefile
The security benefits of PIC binaries are quite well known (since they
work with ASLR), and there is effectively no downside. In addition,
we've been seeing some weird linker errors on ppc64le that are resolved
by using -buildmode=pie.
Signed-off-by: Aleksa Sarai <asarai@suse.de>
> makefile: use -buildmode=pie

- CONTRIBUTING.md
while reviewing CRI-O's CONTRIBUTING.md, we spotted a few small grammatical changes that needed to be made here too.
> A few wording touchups to CONTRIBUTING.md

- Dockerfile
Four small changes to reduce the size of the `skopeo-dev` containers.
Looking at `docker history`, the RPM installation step is now 605 MB instead of 611 MB, while installing many more packages; and the OpenShift build step is 456 MB instead of 1.82 GB.  Overall, the container size is decreased from 2.78 GB to 1.41 GB, almost by half.
See the individual commit messages for details.
> Create smaller testing containers

- CONTRIBUTING.md
See the updated text for the rationale.
This mirrors https://github.com/containers/image/pull/375 . Feel free to tell me this is wrong and reject it.
> Modify CONTRIBUTING.md to prefer smaller commits over squashing them

- cmd/skopeo/copy.go
- cmd/skopeo/utils.go
- vendor/github.com/containers/image/oci/layout/oci_dest.go
- vendor/github.com/containers/image/oci/layout/oci_src.go
- vendor/github.com/containers/image/oci/layout/oci_transport.go
- vendor/github.com/containers/image/types/types.go
Following on from containers/image#369, this adds command-line flags to `skopeo copy` which allow users to use a shared directory for blobs when working with OCI layouts.
@runcom this patch is nice and tiny, but is there a better way to scope flags to specific source/dest types?
> copy: add shared blob directory support for OCI sources/destinations

- README.md
In README.md, there is an example of skopeo copy command to download an
image in OCI format, but the current code returns an error:
skopeo copy docker://busybox:latest oci:busybox_ocilayout
FATA[0000] Error initializing destination oci:tmp:: cannot save image with empty image.ref.name
If we add a tag after the oci directory, the problem is gone:
skopeo copy docker://busybox:latest oci:busybox_ocilayout:latest
Fixes: #446
Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>
> README.md: Fix example of skopeo copy command

- cmd/skopeo/copy.go
- cmd/skopeo/utils.go
- completions/bash/skopeo
- docs/skopeo.1.md
- integration/copy_test.go
- vendor.conf
- vendor/github.com/containers/image/copy/copy.go
- vendor/github.com/containers/image/copy/manifest.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/directory/directory_transport.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/types/types.go
Add manifest type conversion to skopeo with dir transport
User can select from 3 manifest types: oci, v2s1, or v2s2
Adds option to compress blobs when saving to the directory using the dir transport
e.g skopeo copy --format v2s1 --compress-blobs docker-archive:alp.tar dir:my-directory
Addresses issue https://github.com/projectatomic/skopeo/issues/361
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> Add manifest type conversion to skopeo copy

- vendor/github.com/containers/storage/images.go
- vendor/github.com/containers/storage/images_ffjson.go
- vendor/github.com/containers/storage/store.go
Bump containers/storage to master=138cddaf9d6b3910b18de44a017417f60bff4e66 (i.e., the current master).
> Update to a newer containers/storage master

- cmd/skopeo/copy.go
- cmd/skopeo/delete.go
- cmd/skopeo/inspect.go
- cmd/skopeo/utils.go
- completions/bash/skopeo
- docs/skopeo.1.md
skopeo copy, delete, and inspect can now use credentials stored in the auth file
by the kpod login command
e.g kpod login docker.io -> skopeo copy dir:mydir docker://username/image
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> Use credentials from authfile for skopeo commands

- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/image/oci.go
- vendor/github.com/containers/image/ostree/ostree_dest.go
- vendor/github.com/containers/image/tarball/tarball_reference.go
- vendor/github.com/containers/storage/drivers/overlay/overlay.go
Update containers/image and containers/storage to the current master
revisions.
So to inherit all the fixes in the ostree backend.
> vendor: bump containers/image and containers/image

- version/version.go
Releasing a new version mainly for the selinux fixes for system containers. Will tag https://github.com/projectatomic/skopeo/commit/0270e5694c9adf6eabfa3ab1f2980b8b62deb4b7 as `v0.1.28`.
@mtrmac @giuseppe @rhatdan PTAL
> Bump 0.1.28

- Dockerfile.build
17.04 is EOLed and no longer works.
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>
> Dockerfile: bump to ubuntu 17.10

- contrib/containers-storage.conf.5.md
- contrib/storage.conf
These files are used by deb and rpm packages, so I'd rather have them
upstream than maintain in 2 separate places.
@runcom @rhatdan PTAL
> add storage.conf and manpage in contrib/

- cmd/skopeo/copy.go
- cmd/skopeo/utils.go
- completions/bash/skopeo
- docs/skopeo.1.md
This PR adds CLI support for overriding the default docker daemon host when using the
`docker-daemon` transport.
See also containers/image#434
Fixes #244
Signed-off-by: Justin Lewis Salmon <justin.lewis.salmon@gmail.com>
> Support host configuration for docker-daemon sources and destinations

- Dockerfile
The `hack/common.sh` script contains
```sh
local go_version
go_version=($(go version))
if [[ "${go_version[2]}" < "go1.5" ]]; then
fi
```
which does a lexicographic string comparison, and fails with 1.10. Just drop it, the `fedora:latest` image is not likely to revert to 1.5.
> Fix test suite failures with go >= 1.10

- hack/make/validate-vet
Apparently, it was never documented to use `go vet $somefile.go` (but `go tool vet $somefile.go` was).
go 1.10 seems to do more checks within packages, and `$somefile.go` is interpreted as a package with only that file (even if other files from that package are in the same directory), leading to spurious `"undefined: $symbol"` errors.
So, just run `go vet` on `./...` (explicitly excluding `skopeo/vendor` for the benefit of Go 1.8). We only have three subpackages, so the savings, if any, from running `go vet` only on the modified subpackages would be small.
More importantly, on a toolchain update, `./...` allows us to see the newly detected issues all at once, instead of randomly waiting for a commit that changes one of the affected files for the failure to show up.
> Run (go vet) on all subpackages instead only of changed files

- cmd/skopeo/copy.go
- vendor/github.com/containers/image/docker/archive/dest.go
- vendor/github.com/containers/image/docker/archive/transport.go
- vendor/github.com/containers/image/docker/daemon/daemon_transport.go
- vendor/github.com/containers/image/docker/docker_image.go
- vendor/github.com/containers/image/docker/tarfile/dest.go
- vendor/github.com/containers/image/internal/tmpdir/tmpdir.go
- vendor/github.com/containers/image/pkg/docker/config/config.go
- vendor/github.com/containers/image/storage/storage_image.go
- vendor/github.com/containers/image/types/types.go
- vendor/github.com/containers/image/vendor.conf
Add multitag support when generating docker-archive tarballs via the
newly added '--aditional-tag' option, which can be specified multiple
times to add more than one tag.  All specified tags will be added to the
RepoTags field in the docker-archive's manifest.json file.
This change requires to vendor the latest containers/image with
commit a1a9391830fd08637edbe45133fd0a8a2682ae75.
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
> skopeo-copy: docker-archive: multitag support

- README.md
- _Start_ with installing distribution packages, instead of mentioning it after the user has already built everything from source.
- Note that both the binary and documentation needs to be built for `make install` to work.
> Improve installation documentation a bit

- integration/copy_test.go
- vendor/github.com/containers/image/docker/archive/dest.go
- vendor/github.com/containers/image/docker/archive/transport.go
- vendor/github.com/containers/image/docker/tarfile/dest.go
- vendor/github.com/containers/image/oci/layout/oci_dest.go
- vendor/github.com/containers/image/oci/layout/oci_transport.go
- vendor/github.com/containers/image/pkg/docker/config/config.go
docker-archive and oci-archive now allow the image reference
for the destination to be empty.
Update tests for this new change.
Fixes tests for https://github.com/containers/image/pull/458
Signed-off-by: umohnani8 <umohnani@redhat.com>
> [DO NOT MERGE] Pick up changes to transports in containers/image

- vendor.conf
- vendor/github.com/containers/storage/drivers/driver_linux.go
- vendor/github.com/containers/storage/pkg/archive/example_changes.go
- vendor/github.com/containers/storage/pkg/chrootarchive/chroot_linux.go
- vendor/github.com/containers/storage/vendor.conf
- vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
- vendor/github.com/syndtr/gocapability/LICENSE
- vendor/github.com/syndtr/gocapability/capability/capability.go
- vendor/github.com/syndtr/gocapability/capability/capability_linux.go
- vendor/github.com/syndtr/gocapability/capability/capability_noop.go
- vendor/github.com/syndtr/gocapability/capability/enum.go
- vendor/github.com/syndtr/gocapability/capability/enum_gen.go
- vendor/github.com/syndtr/gocapability/capability/syscall_linux.go
skopeo is failing to build now on 32 bit systems.  go-selinux update
should fix this.  Also container/storage has had some cleanup fixes
to devicemapper support.
> Vendor in latest go-selinux and containers/storage

- vendor/github.com/containers/image/ostree/ostree_dest.go
Needed to pick up this change:
ostree: use the same thread for ostree operations
Since https://github.com/ostreedev/ostree/pull/1555, locking is
enabled by default in OSTree.  Unfortunately it uses thread-private
data and it breaks the Golang bindings.  Force the same thread for the
write operations to the OSTree repository.
> vendor: update containers/image

- cmd/skopeo/copy.go
https://github.com/projectatomic/skopeo/pull/519 made `skopeo copy` suceed and print nothing to stderr; that could lead to hard-to-diagnose failures in rare corner cases, e.g. shell scripts which do
`skopeo copy $src $dst` (as opposed to the correct `skopeo copy "$src" "$dst"` ) if `$src` and `$dst` are empty due to a previous failure.
> Ensure that we still return 1, and print something to stderr, on (skopeo copy) failure

- Makefile
- README.md
These targets produce a pure-Go binary, without the following features:
* ostree
* devicemapper
* btrfs
* gpgme
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
> Makefile: add binary-minimal and binary-static-minimal

- Makefile
Minor Makefile change to allow passing the env TESTFLAGS to make. That's pretty
convenient to filter what tests to run.
E.g. run integration tests containing the substring `Copy`:
make test-integration TESTFLAGS="-check.f Copy"
> Allow passing TESTFLAGS env to hack/make.sh from make

- Makefile
... which has, apparently, never worked, because the `golang` image has neither the `GOPATH` nor the working directory the `Makefile` expects.
Rather than move all this configuration into the `Makefile` to be able to work with the `golang` images, just always use the `skopeobuildimage` path, and only override the tags, to minimize divergence.
Fixes #546.
> Fix (make DISABLE_CGO=1)

- cmd/skopeo/copy.go
- cmd/skopeo/delete.go
- cmd/skopeo/inspect.go
- cmd/skopeo/layers.go
- cmd/skopeo/main.go
- cmd/skopeo/utils.go
- completions/bash/skopeo
- docs/skopeo.1.md
the copy sub command may stuck if there are some network issue(e.g. slow network cause of network flapping in infrastructure), skopeo stuck there and application cannot do anything. It results in all the workers hang and cannot continue(retry, or report failure). 
Add the command-timeout option to make it possible to terminate the command to avoid this case.
Test result:
```
./skopeo copy --command-timeout=2s  --src-tls-verify=true --src-creds ****:***** docker://ubuntu:14.04 dir:/tmp/*****/raw
Getting image source signatures
Copying blob sha256:*******
4.53 MB / 48.98 MB [=====>-------------------------------------------------] 1s
FATA[0002] Error writing blob: context deadline exceeded
```
> add timeout support for image copy

- Makefile
podman only accepts the `=` syntax.
Fixes #567.
> Use --security-opt label=disable instead of label:disable

- vendor.conf
... after https://github.com/opencontainers/image-spec/pull/750 was merged.
> Re-vendor image-spec from upstream again

- cmd/skopeo/copy.go
- cmd/skopeo/delete.go
- cmd/skopeo/flag.go
- cmd/skopeo/flag_test.go
- cmd/skopeo/inspect.go
- cmd/skopeo/layers.go
- cmd/skopeo/main.go
- cmd/skopeo/main_test.go
- cmd/skopeo/manifest.go
- cmd/skopeo/signing.go
- cmd/skopeo/utils.go
- cmd/skopeo/utils_test.go
- vendor.conf
- vendor/github.com/urfave/cli/LICENSE
- vendor/github.com/urfave/cli/README.md
- vendor/github.com/urfave/cli/app.go
- vendor/github.com/urfave/cli/cli.go
- vendor/github.com/urfave/cli/command.go
- vendor/github.com/urfave/cli/context.go
- vendor/github.com/urfave/cli/errors.go
- vendor/github.com/urfave/cli/flag.go
- vendor/github.com/urfave/cli/flag_generated.go
- vendor/github.com/urfave/cli/help.go
@runcom , others: RFC
While testing a related change I have noticed that `skopeo layers` sets `DockerDaemonInsecureSkipTLSVerify` always to `true`, because the `--tls-verify` option is not declared for `skopeo layers`; and the way `urfave/cli` is used, there was no connection between the option declaration and reading the value, so it’s way too easy to omit one or the other.  (In particular, `cli.BoolT` can return `false` if the option is not found, or on any other error, really, not only when the user has explicitly provided a `false` value.)
So, this motivated a comprehensive rework of the CLI data management; instead of copy&pasting strings and hoping to never make a typo (which is just not good enough for security options), create a `struct someCommandOptions` holding well-typed …
> RFC: Reliable CLI parsing

- version/version.go
close https://github.com/containers/skopeo/issues/574
will tag https://github.com/containers/skopeo/commit/6eb5131b8554650f4529e6c4475a7e970ec5be36 as `v0.1.33`
> bump to v0.1.33

- vendor.conf
- vendor/github.com/containers/image/copy/copy.go
- vendor/golang.org/x/crypto/otr/libotr_test_helper.c
- vendor/golang.org/x/crypto/otr/otr.go
- vendor/golang.org/x/crypto/otr/smp.go
- vendor/golang.org/x/crypto/ssh/terminal/terminal.go
- vendor/golang.org/x/crypto/ssh/terminal/util.go
- vendor/golang.org/x/crypto/ssh/terminal/util_aix.go
- vendor/golang.org/x/crypto/ssh/terminal/util_bsd.go
- vendor/golang.org/x/crypto/ssh/terminal/util_linux.go
- vendor/golang.org/x/crypto/ssh/terminal/util_plan9.go
- vendor/golang.org/x/crypto/ssh/terminal/util_solaris.go
- vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
- vendor/golang.org/x/crypto/ssh/test/doc.go
- vendor/golang.org/x/crypto/ssh/test/sshd_test_pw.c
When copying images and the output is not a tty (e.g., when piping to a
file) print single lines instead of using progress bars.  This avoids
long and hard to parse output.
> vendor latest c/image

- CONTRIBUTING.md
- README.md
Move documentation about dependencies management from README.md to
CONTRIBUTING.md.
Closes #583
Signed-off-by: Silvano Cirujano Cuesta <silvano.cirujano-cuesta@siemens.com>
> docs: consolidate CONTRIBUTING

- cmd/skopeo/copy.go
- docs/skopeo.1.md
People are using skopeo copy in batch commands and do not need
all of the logging.
> Add --quiet option to skopeo copy

- .gitignore
Modify .gitigare to target any man page since skopeo man page was split up in #598.
> Modify .gitignore for generated man pages

- completions/bash/skopeo
As follows, adds bash completions for transports which commands (copy, delete, and inspect) support.
```
$ skopeo copy 
containers-storage:  docker-archive:      docker:              oci:                 tarball: 
dir:                 docker-daemon:       oci-archive:         ostree: 
```
> completions: Introduce transports completions

- completions/bash/skopeo
This PR fixes the following problems: 
* bash completions does not work after specifying a global option.
* both of tabs and spaces in indentation are used.
> completions: Fix completions with a global option and indentation

- vendor.conf
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/image/docker_schema2.go
- vendor/github.com/containers/image/image/oci.go
- vendor/github.com/containers/image/pkg/blobinfocache/boltdb/boltdb.go
- vendor/github.com/containers/image/pkg/blobinfocache/default.go
- vendor/github.com/containers/image/pkg/blobinfocache/internal/prioritize/prioritize.go
- vendor/github.com/containers/image/pkg/blobinfocache/memory/memory.go
- vendor/github.com/containers/image/pkg/blobinfocache/none/none.go
- vendor/github.com/containers/image/storage/storage_image.go
- vendor/github.com/containers/image/storage/storage_transport.go
- vendor/github.com/containers/image/vendor.conf
- vendor/github.com/containers/storage/drivers/copy/copy.go
- vendor/github.com/containers/storage/pkg/archive/archive.go
- vendor/github.com/containers/storage/pkg/archive/archive_linux.go
- vendor/github.com/containers/storage/pkg/idtools/idtools.go
- vendor/github.com/containers/storage/pkg/idtools/idtools_unix.go
- vendor/github.com/containers/storage/store.go
- vendor/github.com/containers/storage/utils.go
Update containers/storage and containers/image to define location of local storage.
> Vendor in latest containers/storage and containers/image

- Makefile
Currently we are only installing the skopeo.1 man page.  This
change will generate and install all man pages.
> Make sure we install man pages

- Makefile
When I'm using a go binary in a non-default path, running make triggers "go not found" errors.
@vrothberg @mtrmac PTAL.
> use GO envvar throughout in Makefile

- cmd/skopeo/unshare.go
- cmd/skopeo/unshare_linux.go
- cmd/skopeo/utils.go
do not create a user namespace if we already have the capabilities we
need for pulling and storing an image.
Closes: https://github.com/containers/skopeo/issues/637
> rootless: do not create a user namespace if not needed

- vendor.conf
- vendor/github.com/containers/storage/drivers/devmapper/device_setup.go
- vendor/github.com/containers/storage/drivers/overlay/overlay.go
- vendor/github.com/containers/storage/pkg/idtools/parser.go
- vendor/github.com/containers/storage/store.go
- vendor/github.com/containers/storage/utils.go
overlay: propagate errors from mountProgram
utils: root in a userns uses global conf file
Fix handling of additional stores
Correctly check permissions on rootless directory
Fix possible integer overflow on 32bit builds
Evaluate device path for lvm
lockfile test: make concurrent RW test determinisitc
lockfile test: make concurrent read tests deterministic
>  Vendor update container/storage

- cmd/skopeo/utils.go
- completions/bash/skopeo
- docs/skopeo-copy.1.md
- docs/skopeo-delete.1.md
- docs/skopeo-inspect.1.md
- vendor/github.com/kr/pretty/go.mod
- vendor/github.com/kr/text/go.mod
- vendor/golang.org/x/text/go.mod
Follow PR #433 
Close #421 
Currently skopeo inspect allows to:
- Use the default credentials in $HOME/.docker.config
- Explicitly define credentials via de --creds flag
This implements a --no-creds flag which will query docker registries anonymously.
> Add --no-creds flag to skopeo inspect

- cmd/skopeo/inspect.go
- completions/bash/skopeo
- docs/skopeo-inspect.1.md
Add a --config option to "skopeo inspect" to dump an image's configuration blob in the OCI format, or the original format if --config and --raw are specified.  It's handy for me, and it might be useful for other people.
> inspect: add a --config flag

- cmd/skopeo/copy.go
- cmd/skopeo/delete.go
- cmd/skopeo/inspect.go
- cmd/skopeo/layers.go
- cmd/skopeo/unshare.go
- cmd/skopeo/unshare_linux.go
- cmd/skopeo/utils.go
- vendor.conf
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/docs/containers-signature.5.md
- vendor/github.com/containers/image/pkg/sysregistriesv2/system_registries_v2.go
- vendor/github.com/containers/image/transports/alltransports/alltransports.go
- vendor/github.com/containers/image/types/types.go
This change fixes skopeo usage in restricted environment such as
bubblewrap where it doesn't need extra capabilities or user namespace
to perform its action.
Close #649
Signed-off-by: Tristan Cacqueray <tdecacqu@redhat.com>
> rootless: don't create a namespace unless for containers-storage

- cmd/skopeo/unshare_linux.go
We need to verfy that the user entered a valid transport before attempting
to see if the transport exists,  otherwise skopeo segfaults.
> Skopeo crashes on any invalid transport

- integration/check_test.go
- integration/copy_test.go
This change adds a couple of tests to prevent further regression
introduced by https://github.com/containers/skopeo/pull/653
Signed-off-by: Tristan Cacqueray <tdecacqu@redhat.com>
> Add integration test for invalid reference

- Dockerfile.build
- README.md
`btrfs/ioctl.h` is in `libbtrfs-dev` (now?), `btrfs-tools` does not pull it in.
Fixes #663.
> Fix build on Ubuntu

- integration/copy_test.go
- integration/signing_test.go
Since GPG 2.1, GPG asks for a passphrase by default; opt out when generating the test key, to fix
```
gpg: agent_genkey failed: No pinentry
gpg: key generation failed: No pinentry
```
which happens otherwise.
> Explicitly disable encrypting the test GPG key

- systemtest/helpers.bash
The usual 'podman run -d' race condition: we've been forking
off the container but not actually making sure it's up; this
leads to flakes in which we try (and fail) to access it.
Solution: use curl to check the port; we will expect a zero
exit status once we can connect. Time out at ten seconds.
Resolves: #675
> start_registry: wait for registry to be ready

- systemtest/050-signing.bats
This does not happen in this repo's tests, but containers/image's `make test-skopeo` fails in the `containers_image_openpgp` configuration with
```
not ok 10 signing
...
```
To reproduce/test this:
```sh
make test-system BUILDTAGS='ostree containers_image_openpgp'
```
Cc: @edsantiago
> Skip systemtest/050-signing.bats if skopeo can't create signatures

- vendor.conf
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/docker/reference/README.md
- vendor/github.com/containers/image/docker/reference/normalize.go
- vendor/github.com/containers/image/docker/reference/reference.go
- vendor/github.com/containers/image/docker/reference/regexp.go
- vendor/github.com/containers/image/docs/containers-registries.conf.5.md
- vendor/github.com/containers/image/pkg/sysregistriesv2/system_registries_v2.go
- vendor/github.com/containers/image/registries.conf
- vendor/github.com/containers/image/version/version.go
This adds the mirror-by-digest-only option to mirrors, and moves the search order to an independent list.
> Rebase containers/image to v2.0.0

- README.md
Adds a simple documentation how to install skopeo on an openSUSE
distribution
Signed-off-by: José Guilherme Vanz <jguilhermevanz@suse.com>
> README.md: command to install on openSUSE

- Makefile
Turn of go modules to avoid breaking build environments to accidentally
try pulling the dependencies instead of using the ./vendor directory.
> Makefile: set GO111MODULE=off

- Makefile
- README.md
- hack/make/test-integration
containers/storage needs math/bits which has been added in go 1.9, so
this is now the lowest possible go version to build skopeo. We can also
remove the GO15VENDOREXPERIMENT variable since this has been enabled in
go 1.6 per default and removed in go 1.7.
Relates to https://github.com/containers/skopeo/pull/686
> Fix lowest possible go version to be 1.9

- go.mod
- go.sum
- integration/blocked_test.go
- integration/fixtures/blocked-registries.conf
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/pkg/docker/config/config.go
- vendor/github.com/containers/image/pkg/docker/config/config_linux.go
- vendor/github.com/containers/image/pkg/docker/config/config_unsupported.go
- vendor/github.com/containers/image/pkg/keyctl/key.go
- vendor/github.com/containers/image/pkg/keyctl/keyring.go
- vendor/github.com/containers/image/pkg/keyctl/perm.go
- vendor/github.com/containers/image/pkg/keyctl/sys_linux.go
- vendor/github.com/containers/image/pkg/keyctl/sys_linux_386.go
- vendor/github.com/containers/image/pkg/keyctl/sys_linux_amd64.go
- vendor/github.com/containers/image/pkg/sysregistriesv2/system_registries_v2.go
- vendor/github.com/containers/image/signature/policy_types.go
- vendor/github.com/containers/image/transports/alltransports/alltransports.go
- vendor/github.com/containers/image/version/version.go
- vendor/modules.txt
Vendor in the latest c/image to enforce blocking of registries when
creating a c/image/docker.dockerClient.  Add integration tests to
avoid regressions.
---
~~Do not merge: that's a pet PR for https://github.com/containers/image/pull/658.~~
> enforce blocking of registries

- .travis.yml
This reverts commit d6270f4691e6f83179ebefe445a199ee756fe159.
> Revert "Travis: use go 1.12.x"

- systemtest/060-delete.bats
- systemtest/helpers.bash
[root@dhcp-14-124 skopeo]# bats systemtest/060-delete.bats 
✓ delete: remove image from registry
1 test, 0 failures
Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>
> systemtest: support deleting image from registry

- hack/ostree_tag.sh
Starting from 9b902d0, the ostree transport is disabled by default,
and ostree is enabled with the tag containers_image_ostree.
/cc @vrothberg
> ostree: use the correct build tags

- cmd/skopeo/main.go
- hack/ostree_tag.sh
The PR #700 replaced ostree buildtag with containers_image_ostree.
However specifying the ostree buildtag is needed by containers/storage
vfs driver.
/cc @mtrmac @vrothberg
> ostree: use both image and & storage buildtags

- cmd/skopeo/inspect.go
Update the inspect command to show the environment variables
Signed-off-by: José Guilherme Vanz <jguilhermevanz@suse.com>
This change requires a change in the `containers/image` library: https://github.com/containers/image/pull/652
> inspect.go: inspect env variables

- go.mod
- go.sum
- vendor/github.com/opencontainers/image-spec/schema/loader.go
- vendor/github.com/opencontainers/image-spec/schema/validator.go
- vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
- vendor/github.com/opencontainers/image-spec/specs-go/version.go
- vendor/modules.txt
This mainly pulls in the latest support for zstd-compressed layers and
eases testing of containers/image.
> update OCI image-spec to 775207bd45b6cb8153ce218cc59351799217451f

- systemtest/010-inspect.bats
$ bats systemtest/010-inspect.bats 
✓ inspect: basic
✓ inspect: env
2 tests, 0 failures
Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>
> systemtest: add simple env test in inspect.bats

- systemtest/010-inspect.bats
The "inspect: env" test started failing since the environment in the
`fedora:latest` image has changed.  Hence, only check for `PATH` in
the image's environment which is a defacto standard.
> systemtest/010-inspect.bats: require only PATH

- systemtest/020-copy.bats
Add a systemtest coying an image from docker to storage and then to an
oci-archive.  There are other ways to trigger the same code paths, but
this one has caught a regression in c/image in libpod's.
Fixes: #734
> systemtest: copy: docker->storage->oci-archive

- systemtest/040-local-registry-auth.bats
Temporarily work around https://github.com/containers/libpod/issues/4227 until Fedora has an updated package that includes the fix, at which point we should revert this patch.
> Temporarily work around auth.json location confusion

- systemtest/020-copy.bats
- systemtest/helpers.bash
- zstd test - give unique name.
a36d81c copy/pasted an existing test but didn't give
the new test a new name, leading to bats warning:
duplicate test name(s) in [...]/020-copy.bats
- start_registry() - use bash builtins, not curl, to test
if registry port is open.
curl on Fedora now barfs with "Received HTTP/0.9 when not
allowed" when the registry is run with SSL, because the
response is not valid HTTP. One workaround would be 'curl
--http0.9' but (surprise) that option doesn't exist on rhel8;
and even with that option we would need --output /dev/null
to silence a different curl warning. Curl is overkill
for this purpose anyway, all we really need is netcat
or some simple binary is-port-listening-or-not test.
Fortunately, bash provides a /dev/tcp/<host>/<port>
emulator that does the right …
> System tests: various fixes

- Dockerfile
the package was renamed on Fedora 31.
> Dockerfile: use golang-github-cpuguy83-go-md2man

- systemtest/040-local-registry-auth.bats
This reverts commit 4962559e5cb79a0d6d869b1c26dbc0171354eb73.
Fixes #743 .
> Revert "Temporarily work around auth.json location confusion"

- cmd/skopeo/inspect.go
Per a report in https://github.com/containers/skopeo/issues/726 , it can happen if the user is not allowed the `ListImages` action on AWS ECR.
Should fix #726.
> Don't critically fail on a 403 when listing tags

- Makefile
- hack/make.sh
- hack/make/validate-vet
- integration/copy_test.go
See https://github.com/containers/skopeo/pull/760#issuecomment-557286929 below.
> Support running tests from c/image

- Makefile
Add a vendor-in-container make target to allow for executing make vendor
in a golang:1.13 container.  The CI is currently enforcing golang 1.13
which has a different vendoring behavior than previous versions which
can lead to failing tests as some files might be added or deleted.  The
new make target will help users who are not using 1.13 to vendor their
changes.
> make vendor-in-container

- cmd/skopeo/main.go
- cmd/skopeo/sync.go
- cmd/skopeo/utils.go
- docs/skopeo-sync.1.md
- docs/skopeo.1.md
- go.mod
- integration/openshift.go
- integration/sync_test.go
The skopeo sync command can sync images between a SOURCE and a destination.
The purpose of this command is to assist with the mirroring of container images from different docker registries to a single docker registry.
Right now the following transport matrix is implemented:
* `docker://` -> `docker://`
* `docker://` -> `dir:`
* `dir:` -> `docker://`
The `dir:` transport is supported to handle the use case of air-gapped environments.
In this context users can perform an initial sync on a trusted machine connected to the internet; that would be a `docker://` -> `dir:` sync.
The target directory can be copied to a removable drive that can then be plugged into a node of the air-gapped environment. From there a `dir:` -> `docker://` sync will import all the images into the registry serving the …
> Introduce the sync command

- Makefile
If not already set in the environment, set GOBIN.
Fixes: #779
> Makefile: set GOBIN

- cmd/skopeo/unshare_linux.go
Remove a direct reference on c/image/v5/storage which breaks the build
when using the `containers_image_storage_stub`.  The reference is only
used to get the storage tranport string, which is now hard-coded; this
is fine as the transport will not change for backwards compat.
Fixes: #771
> remove direct reference on c/image/storage

- cmd/skopeo/copy.go
... to avoid context-less errors like
```console
$ skopeo copy --decryption-key foo dir:x dir:y
FATA[0000] open foo: no such file or directory
$ skopeo copy --encryption-key /dev/null dir:x dir:y
FATA[0000] Invalid recipient format
```
> Add context to --encryption-key / --decryption-key processing failures

- .gitignore
- cmd/skopeo/utils.go
- cmd/skopeo/utils_test.go
- completions/bash/skopeo
- docs/skopeo-copy.1.md
- docs/skopeo-sync.1.md
With additional prefixed flags for authfiles, it is possible to override the shared authfile flag to use different authfiles for src and dest registries. This is an important feature if the two registries have the same domain (but different paths) and require separate credentials.
Closes #773.
Signed-off-by: Daniel Strobusch <1847260+dastrobu@users.noreply.github.com>
> add specific authfile options to copy (and sync) command.

- go.mod
This is another attempt to fix #791 after ineffective #802.
The referenced tag has been removed, which breaks dependabot (#791).
This is another attempt to fix it, by removing an explicit reference (which was added when updating Buildah, because the version seemed newer than Buildah's v0.0.0 with a newer commit).
The referenced package is never even physically vendored in here, so remove the reference:
> ```
> go mod edit -droprequire=github.com/openshift/api
> make vendor
> ```
> Remove the reference to openshift/api

- Dockerfile
- integration/copy_test.go
- integration/signing_test.go
- vendor.conf
- vendor/github.com/mtrmac/gpgme/data.go
- vendor/github.com/mtrmac/gpgme/go.mod
- vendor/github.com/mtrmac/gpgme/go_gpgme.c
- vendor/github.com/mtrmac/gpgme/go_gpgme.h
- vendor/github.com/mtrmac/gpgme/gpgme.go
- vendor/github.com/mtrmac/gpgme/unset_agent_info.go
- vendor/github.com/mtrmac/gpgme/unset_agent_info_windows.go
This fixes CVE-2020-8945 by incorporating proglottis/gpgme#23 .
Other changes included by the rebase:
- Support for `gpgme_off_t` (~no-op on Linux)
- Wrapping a few more GPGME functions (irrelevant if we don't call them)
Given how invasive the CVE fix is (affecting basically all binding code), it seems safer to just update the package (and be verifiably equivalent with upstream) than to backport and try to back out the few other changes.
Performed by updating vendor conf,
```console
$ vndr github.com/mtrmac/gpgme
```
and manually backing out unrelated deletions of files.
> Update to github.com/mtrmac/gpgme v0.1.2

- cmd/skopeo/copy.go
- docs/skopeo-copy.1.md
- integration/copy_test.go
While https://github.com/containers/skopeo/pull/732 brought in image encryption support in skopeo, this PR adds the support for partial image encryption. 
User will be able to select which layer of the image they want to encrypt instead of encrypting an entire image. This is very useful from the layer reusability point of view. e.g. User can take a standard `ubuntu:18:04` image and add their custom layer which they will like to protect with the encryption. 
When that image is saved in the snapshotter of the runtime, the layers that aren't encrypted end up getting reused which results in better disk space utilization as well as faster downloads (only have to download encrypted layers if the rest of the layers are already present in the snapshotter)
Signed-off-by: Harshal Patil …
> Partial image encryption support

- Dockerfile.build
Just bumping to ubuntu 19.10; ubuntu 18.10 is no longer supported, causing the current binary target to fail with errors
```sh
E: The repository 'http://security.ubuntu.com/ubuntu cosmic-security Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic-backports Release' does not have a Release file.
```
> build from ubuntu 19.10

- Dockerfile
- systemtest/helpers.bash
crun had a regression running on cgroupsv1 in containers.  It has been
fixed upstream but did not yet bubble up into the packages.  Force using
runc to unblock Skopeo's CI.
> CI: force Podman to use runc

- README.md
apparently the Fedora reference is not obviously relevant.
(I didn’t add the same update for the local build instructions, because that requires more information about enabling non-default repositories, and especially RHEL users should get a chance to think for a bit before overriding a system package. This is not at all clear to be the right decision — anyway, filing a PR for the easy decision for now.)
> Mention CentOS/RHEL in installation instructions

- cmd/skopeo/utils.go
- cmd/skopeo/utils_test.go
- docs/skopeo-copy.1.md
Fix cli to use REGISTRY_AUTH_FILE if set and to display the
default location to use for authfiles in the `skopeo copy --help`
Modify tests to verify the different settings.
> add support for REGISTRY_AUTH_FILE

- systemtest/010-inspect.bats
- systemtest/020-copy.bats
- systemtest/030-local-registry-tls.bats
- systemtest/040-local-registry-auth.bats
- systemtest/050-signing.bats
- systemtest/060-delete.bats
- systemtest/helpers.bash
Replace shortnames with FQINs; this should allow tests to
run regardless of the state of registries.conf.
And, fix one broken new test that invoked 'jq' (without dot).
This usage works in Fedora, but not in RHEL.
> Use fully-qualified image names

- cmd/skopeo/main.go
- cmd/skopeo/utils.go
- cmd/skopeo/utils_test.go
- completions/bash/skopeo
- docs/skopeo.1.md
Enhancement request: https://github.com/containers/skopeo/issues/805
Also sorted commands and options on skopeo man page and skopeo --help
Originally submitted by  Michel Belleau <michel.belleau@malaiwah.com>
> Skopeo should support for BigFilesTemporaryDir (SystemContext)

- Makefile
- go.sum
Run `go mod tidy` after `go mod vendor` to properly clean up the
dependencies.
> make vendor: run `tidy` after `vendor`

- Makefile
`(export a=b command args)` does not run `(command args)` with `a=b`, it sets `$a` to `b`, and marks variables `$a` `$command` `$args` as exported, i.e. `(command args)` is not run.
So, before https://github.com/containers/skopeo/pull/888 we were not actually running `(go mod tidy)`, and now we are not running `(go mod vendor)`.
Just use `$(GO)`, which already sets `GO111MODULE=on`, without the extra export.
> Fix (make vendor)

- go.mod
- go.sum
This reverts commit 8c8d9bd23f9ddd5f183391f2751927cd392794d0.
When correctly vendored, this breaks tests.
> Revert "Bump github.com/urfave/cli from 1.22.1 to 1.22.4"

- Makefile
This is conceptually consistent: First change the set of dependencies, then update the vendored copy.
(Due to `go mod verify` afterwards, and CI running this again, this should not make a difference in practice, so this is just a clean-up.)
> Run (go mod tidy) before (go mod vendor)

- systemtest/010-inspect.bats
'podman info' changed format, again, without preserving backward
compatibility. Basically, some keys that used to be lower-case
are now upper-case-first-letter.
These tests need to work with new podman on rawhide, and
old podman on f31/f32 and possibly RHEL. We must therefore
add a revolting workaround for the change.
> Fix for yet another breaking podman change

- version/version.go
Update on #834: force runc only when cgroupsv1
Update docs/skopeo.1.md
Add example with repository
Skopeo should support for BigFilesTemporaryDir (SystemContext)
Use fully-qualified image names
Mention CentOS/RHEL in installation instructions
bump to a supported ubuntu release
add support for REGISTRY_AUTH_FILE
Partial image encryption support
Fix wrong import of docker reference
Fix inconsistency in manpage example for list-tags
Fix formatting on test
Adds "list-tags" command to list tags with no known tag required. Fixes #276
> Bump to v0.2.0

- integration/copy_test.go
Actually test that X-R-S-S signatures are usable using `atomic:`, as the comment says.
> Fix TestCopyAtomicExtension

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
Only bumps the version number after the recent vendoring from master, but Dependabot seems to be confused by that; so, update to the final release to hopefully un-confuse it.
> Update containers/image to v5.4.4

- contrib/skopeoimage/stable/Dockerfile
Adds the Dockerfile for building the Skopeo container
image on quay.io.  Once merged, this image will be
built automatically upon any merge into the master
branch.  The images will live at:
quay.io/containers/skopeo:latest
quay.io/skopeo/stable:latest
I've built an image using this Dockerfile and have pushed
it to both repositories if you want to play with that.
Once merged, I'll create similar Dockerfiles for
quay.io/skopeo/testing and quay.io/skopeo/upstream.
> Add Skopeo Stable Image Dockerfile for Quay

- cmd/skopeo/sync.go
- docs/skopeo-sync.1.md
- integration/sync_test.go
This is a proposal to change #920 before it gets released.
IMHO, fields that magically change their behavior depending on type of the value are too much hassle for no benefit.
The initial commit just copies&pastes the full loop in `imagesToCopyFromRegistry` to create another loop handling the new `ImagesByTagRegex` field; then follows a large set of cleanups and small fixes, some related to the original subject matter, quite a few independent.
Please see individual commit messages for details.
I’ll be happy to move the unrelated changes (or even the partially-related changes?) into a separate PR if desired.
> Use a separate field for the “sync images with tag matching regex” feature

- contrib/skopeoimage/README.md
- contrib/skopeoimage/testing/Dockerfile
- contrib/skopeoimage/upstream/Dockerfile
This PR adds the Dockerfiles necessary to create the upstream
and testing variants of the Skopeo container images that will
reside in quay.io/skopeo/upstream and quay.io/skopeo/testing
repositories.  The only difference in the Dockerfile between
the stable and testing image is the option `--enablerepo updates-testing`
was added.  The testing variant is relatively the same, but
I'd to clone and install Skopeo in the container.
I've also added a README.md which explains all of the varities
of images and includes some sample usage.
> Add upstream and testing container images

- docs/skopeo-sync.1.md
To disable TLS verification need to set "tls-verify" to "false"
> Correct a typo in docs/skopeo-sync.1.md

- .gitignore
- Makefile
- contrib/skopeoimage/upstream/Dockerfile
- hack/make/test-integration
- hack/make/test-system
- hack/travis_osx.sh
- install.md
- integration/openshift_shell_test.go
- nix/default.nix
- nix/nixpkgs.json
- nix/nixpkgs.nix
> /kind feature
Similar PR goes for crun/conmon/libpod/cri-o/etc, too.
Also see:
- ~~https://github.com/containers/crun/pull/372~~
- ~~https://github.com/containers/conmon/pull/161~~
- https://github.com/containers/skopeo/pull/932
- https://github.com/containers/buildah/pull/2380
- https://github.com/containers/libpod/pull/6402
- https://github.com/cri-o/cri-o/pull/3804
Static binaries:
- [crun-0.13-linux-amd64](https://github.com/alvistack/crun/releases/download/0.13/crun-0.13-linux-amd64)
- [conmon-v2.0.17-linux-amd64](https://github.com/alvistack/conmon/releases/download/v2.0.17/conmon-v2.0.17-linux-amd64)
- [skopeo-v1.0.0-linux-amd64](https://github.com/alvistack/skopeo/releases/download/v1.0.0/skopeo-v1.0.0-linux-amd64)
- [buildah-v1.14.9-linux-amd64](https://github.com/alvistack/buil …
> [nix] Add nix derivation for static builds

- Dockerfile
- systemtest/helpers.bash
registry:2 no longer contains htpasswd.
> Run htpasswd from our build-container instead of registry:2

- .travis.yml
... which are currently failing with
> ```
> Error: The `brew link` step did not complete successfully
> The formula built, but is not symlinked into /usr/local
> Could not symlink Frameworks/Python.framework/Headers
> Target /usr/local/Frameworks/Python.framework/Headers
> is a symlink belonging to python@2. You can unlink it:
>   brew unlink python@2
> ```
because the Travis-installed machine apparently has quite a few Homebrew formulae installed, with an old version of Homebrew, including a now-removed `python@2`, and that prevents updates of `python@3`.
Remove the obsolete motivation for running (brew update), and replace it with a similarly-good motivation that the Travis images are just too old to be relevant to users.
> Fix macOS builds in Travis

- cmd/skopeo/inspect.go
- cmd/skopeo/utils.go
- completions/bash/skopeo
- docs/skopeo-inspect.1.md
- go.mod
Enables to retry skopeo inspect. Add `--retry-times` to set the number of times to retry.  Use exponential backoff and  1s as default initial retry delay.
fix #918 
> Retry skopeo inspect command

- cmd/skopeo/copy.go
- docs/skopeo-copy.1.md
because that's what users are looking for, and instead of using a `containers-storage:` source, which might not even work all that well with all the automatic defaults Podman sets up.
Fixes #924 .
> Use an inter-registry copy as the example for (skopeo copy)

- Makefile
- nix/default.nix
- nix/nixpkgs.json
Also synchronize nix build implementation between skopeo/buildah/podman/cri-o.
Also see:
- https://github.com/containers/crun/pull/428
- https://github.com/containers/conmon/pull/189
- https://github.com/containers/skopeo/pull/973
- https://github.com/containers/buildah/pull/2428
- https://github.com/containers/podman/pull/7076
- https://github.com/cri-o/cri-o/pull/4012
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>
```release-note
Build static binary with `buildGoModule`
```
> Build static binary with `buildGoModule`

- Makefile
Signed-off-by: Xiaodong Liu <liuxiaodong@loongson.cn>
I build skopeo on mips64le with error:
`-buildmode=pie not supported on linux/mips64le`
There are the same issue on other cpu arch. 
reference: https://github.com/containerd/containerd/blob/master/Makefile.linux#L23
> -buildmode=pie is not supported for some arch

- install.md
... which no longer works after #932.
This does not add documentation for the current static build approach, nor does it add any other place where `DISABLE_CGO` is documented; both are not tested by CI, and discouraged due to bad integration with the rest of the system.
> Remove an obsolete documentation of (make binary-static)

- cmd/skopeo/utils.go
- cmd/skopeo/utils_test.go
- completions/bash/skopeo
- docs/skopeo-copy.1.md
- docs/skopeo-delete.1.md
- docs/skopeo-inspect.1.md
- docs/skopeo-list-tags.1.md
- docs/skopeo-sync.1.md
This feature https://github.com/containers/image/pull/842 was merged in containers/image to support authentication using a provided Bearer token (example use case: integration with Harbor webhooks).
This PR adds a flag to the skopeo CLI to provide support for the registry Bearer token.
Signed-off-by: Alvaro Iradier <airadier@gmail.com>
> Add --registry-token flags to support Bearer token authentication

- .travis.yml
- Makefile
Add a make target that cross-compiles for a handful of the possible targets that `go tool dist list` can tell us about, and exercise it in CI.
> Makefile: add a local-cross target

- systemtest/helpers.bash
Go 1.15 deprecates checking CN; this broke gating tests:
Get "https://localhost:5000/v2/": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
Easy two-line solution in the 'openssl' invocation. Huge
thanks to Nalin for tracking down and fixing while I was
still getting started:
https://github.com/containers/buildah/pull/2595
Copied from 0f2892a5b021de3b1cf273f5679fda8298b57c02 in buildah
> Add Subject Alternative Name to local openssl cert

- Makefile
- install.md
By default we should build bin/skopeo locally
and build docs locally.
Show output when doing make docs.
Add description in `make help` to explain default
behaviour.
Fixes: https://github.com/containers/skopeo/issues/580
> Make Makefile a little easier to use

- README.md
Small fix in examples: the `--user` flag is not recognized, but `--username` is.
> Fix `skopeo login` example in README

- .travis.yml
- release/Makefile
- release/README.md
This PR is connected to https://github.com/containers/skopeo/issues/1010 to get skopeo multi-arch container images.
To build multi-arch upstream container image Travis is used, as it has native hardware to run the build for many architectures (amd64, s390x, ppc64le). Docker is used as build and manifest tool. `quay.io/skopeo/upstream:master`, `quay.io/skopeo/stable:v1.2.0` and `quay.io/containers/skopeo:v1.2.0` are specified as target multi-arch images.
Travis config file has 3 stages:
- `local-build` to do the local binary build and test for linux/amd64 and osx, as it was in
the initial code
- `image-build-push` to build and push images for specific architectures (amd64, s390x, ppc64le)
- `multi-arch-manifest-push` to create and push manifest for multi-arch image - …
> add multi-arch build of upstream skopeo image via Travis

- Makefile
Similar to https://github.com/containers/buildah/pull/2752:
`LDFLAGS` is a common/standard variable to hold linker flags for C/C++ compilers.
This PR uses a different name (`SKOPEO_LDFLAGS`) for the `-ldflags` passed on to Go so that we avoid overriding `LDFLAGS` set in the environment.
@mtrmac in https://github.com/containers/skopeo/pull/1099#pullrequestreview-525574335 :
> For the record, a missing part of the motivation is that CGo uses LDFLAGS when referring to C libraries, so this breaks overriding e.g. paths with `-L`.
> Avoid overriding LDFLAGS in Makefile

- release/Makefile
Service accounts (a.k.a. robots) in `quay.io` are forcably namespaced
to the user or orginization under which they are created.  Therefore,
it is impossible to use a common login/password to push images for
both `skopeo` and `containers` namespaces.  Worse, because the
authentication is recorded against `quay.io`, multiple login sessions
are required.
Fix this by adding a function definition which verifies non-empty
username/password arguments, before logging in.  Call this function
as needed from relevant targets, prior to pushing images.
> Support namespaced logins for quay.io

- cmd/skopeo/sync.go
- docs/skopeo-sync.1.md
- integration/sync_test.go
In addition, this changes the copy options to pass
CopyAllImages such that any digests referencing manifest
lists work as expected. While this is potentially a change
in behavior for previous sync incantations, it is most likely
desired as there is no option to override ones architecture
with the sync command anyways.
Signed-off-by: Andrew DeMaria <ademaria@cloudflare.com>
> Fix #858 Add support for digests in sync

- contrib/skopeoimage/README.md
- release/README.md
Also update to the correct one information about required env variables
for multi-arch build
Signed-off-by: Yulia Gaponenko <yulia.gaponenko1@de.ibm.com>
> Add information about multi-arch image to README

- .travis.yml
<s>We are updating it because Homebrew warns about the old version, so updating it only afterwards does not help.</s>
Homebrew:
> Warning: You are using macOS 10.13.
> We (and Apple) do not provide support for this old version.
> You will encounter build failures with some formulae.
So, update to the 10.14 major version, fully-updated.
Also remove the Xcode update attempt, it was added before Homebrew was warning about the Xcode version, but updating only after running Homebrew does not help, and anyway it does not complain anymore after the update.
> Update to macOS 10.14

- cmd/skopeo/sync.go
Pass down the creds from yaml file only if the values are not empty.
Enables to use credentials from other authfiles alternatively.
close: #1122 
> fix creds sync from yaml

- integration/sync_test.go
From https://github.com/containers/skopeo/pull/1146#discussion_r552718986 .
Filed somewhat as a reminder, this may need updating after #1146.
> Fix reading the after-sync list of tags in SyncSuite.TestYamlUntagged

- integration/copy_test.go
- integration/sync_test.go
Do repository synchronization tests using k8s.gcr.io/pause instead of docker.io/alpine.  The k8s.gcr.io/pause repository includes multiple tags, at least one of which is a single image ("1.0"), and at least one of which is a manifest list ("3.2", "3.3"), so I don't think we sacrifice coverage by switching to it.
> integration test: sync k8s.gcr.io/pause instead of docker.io/alpine

- Makefile
- contrib/skopeoimage/upstream/Dockerfile
- hack/make/test-integration
- hack/make/test-system
- integration/openshift_shell_test.go
PREFIX should default to /usr/local according to GNU coding standards.
DESTDIR should just be used for install
This will allow us to specify
make PREFIX=/usr DESTDIR=/tmp/build/ install
> Fix Makefile to handle PREFIX correctly

- systemtest/010-inspect.bats
- systemtest/020-copy.bats
- systemtest/030-local-registry-tls.bats
- systemtest/040-local-registry-auth.bats
- systemtest/050-signing.bats
- systemtest/060-delete.bats
- systemtest/helpers.bash
- systemtest/make-noarch-manifest
Switch to using images from quay.io/libpod instead, where
we're not (yet) subject to rate limiting.
Disable (skip) one test that I have no idea how to migrate,
because it needs only-one-arch images from docker.io/$arch.
> Migrate tests from docker.io

- Makefile
Unconditionally set PREFIX to /usr/local on FreeBSD and Darwin
platforms.
Use gpg-config to detect libraries paths on all platforms.
Fixes error with gpgme not able to locate gpgme.h on FreeBSD.
Ref https://github.com/containers/skopeo/issues/1163
> Set PREFIX on FreeBSD and use gpg-config to detect paths

- cmd/skopeo/main.go
- cmd/skopeo/main_test.go
- cmd/skopeo/utils_test.go
Prior to this, the User-Agent used by containers/image would default to
the default User-Agent for golang, which makes it difficult to
distinguish skopeo from any other golang binaries in registry logs.
Fixes https://github.com/containers/skopeo/issues/1109
If you think this requires a test, I'm happy to add something, but `go test` fails to build for me because I'm missing certain header files, and I figured I'd give this a shot before diving into that 😉 
Signed-off-by: Jon Johnson <jonjohnson@google.com>
> Set User-Agent to skopeo/$VERSION

- go.mod
- go.sum
- vendor/github.com/gogo/protobuf/proto/text_parser.go
- vendor/modules.txt
Bumping github.com/gogo/protobuf/proto to v1.3.2 to enusure
a low likelyhood CVE is reached.  Partially addresses:
https://bugzilla.redhat.com/show_bug.cgi?id=1924544
> Bump github.com/gogo/protobuf/proto to v1.3.2

- go.mod
- go.sum
- vendor/github.com/gogo/protobuf/proto/text_parser.go
- vendor/modules.txt
Bumping github.com/gogo/protobuf/proto to v1.3.2 to ensure
a low likelihood CVE is not reached. Partially addresses:
https://bugzilla.redhat.com/show_bug.cgi?id=1924544
> Bump vendor/modules.txt in release-1.2

- .github/workflow/stale.yml
By popular demand, add the stale bot which we'are already using at
Podman.  The bot will remind us every 30 days of inactivity on specific
issues or pull requests and has turned into a useful tool to keep things
on the radar.
> add stale bot

- contrib/skopeoimage/stable/Dockerfile
- contrib/skopeoimage/testing/Dockerfile
- contrib/skopeoimage/upstream/Dockerfile
The quay.io/skopeo/testing:latest image was showing v1.2.0 for a version when it
should have been showing at least v1.2.1.  The issue was the Fedora tag in the
Dockerfiles used to build the images was set to 32 and not the later 33.
Addresses: #1204
> Bump skopoeoimage Dockerfiles to user Fedora 33

- Dockerfile
- Makefile
- hack/make.sh
These tests need to operate as part of the c/image repository CI to
verify downstream-usage.  That environment is already inside the
container built from the Dockerfile (here).  Support this use-case by
adding 'local' targets which bypass the container build.  Also,
simplify the "in-container" check to more specifically verify the exact
container image it's operating under.
Ref: https://github.com/containers/image/pull/1140
> Add local integration and system test targets

- Makefile
- hack/make.sh
Without this env. var. being set from hack/make.sh, many/most
integration tests will `SKIP`.  Fix this by notifying the user
and setting the magic `SKOPEO_CONTAINER_TESTS` variable.
> Fix skipping tests in test container

- systemtest/020-copy.bats
- systemtest/030-local-registry-tls.bats
- systemtest/040-local-registry-auth.bats
- systemtest/050-signing.bats
Add system tests for the following subcommands and flags:
- skopeo copy --format
- skopeo copy --additional-tag
- skopeo copy --dest-shared-blob-dir
- skopeo copy --src-shared-blob-dir
- skopeo inspect --tls-verify --cert-dir
- skopeo delete --tls-verify --cert-dir
- skopeo copy --dest-creds
- skopeo copy --src-creds
- skopeo copy --authfile
- skopeo inspect --authfile
- skopeo delete --authfile
- skopeo copy --remove-signatures
- skopeo standalone-sign
- skopeo standalone-verify
- skopeo manifest-digest
Signed-off-by: Hironori Shiina <shiina.hironori@jp.fujitsu.com>
> Add system tests

- go.mod
- go.sum
This updates the indirect dependency we have on dsnet/compress (via
opencontainer/image-tools) to the latest master commit, which includes
an update to a non-vulnerable version of xz.
Closes #1226
> Upgrade dsnet/compress to avoid vulnerable xz version

- contrib/skopeoimage/stable/Dockerfile
- contrib/skopeoimage/testing/Dockerfile
- contrib/skopeoimage/upstream/Dockerfile
The Skopeo images set `REGISTRY_AUTH_FILE=/auth.json` which is breaking
non-root users inside the container from logging in (`/` is writable by
root only).  Setting it to `/tmp/auth.json` will support running
non-root users inside the container.
Fixes: #1233
> skopeo images: set authfile to /tmp/auth.json

- README.md
login and logout don't seem to support or require the `docker://` scheme prefix.
Fixes part of #1240
> Fix for login / logout registry argument

- Makefile
In 18e6c6f17b1ef900e3a3ce4cde94ab23073b9ebf there where changes to
better handle PREFIX and DESTDIR in the Makefile. "CONTAINERSCONFIGDIR"
was renamed to "CONTAINERSCONFDIR" without ensuring it was correct in
the install block. This results in policy.json being isntalled into
"${DESTDIR}/" which is "/policy.json" for Linux distros.
Signed-off-by: Morten Linderud <morten@linderud.pw>
> Makefile: Ensure policy.json uses new variable

- .cirrus.yml
- .travis.yml
- contrib/cirrus/runner.sh
- hack/get_ci_vm.sh
Partial replacement for #1213 (does ***not*** migrate the problematic OSX-cross build)
> Travis -> Cirrus: validate, vendor, and test

- install.md
This commit removes installation steps for older distros:
1. Amazon Linux 2
2. CentOS 7
3. Debian 10
4. Raspbian 10
5. Raspberry Pi OS armhf
We're no longer building new packages for these distros and the
installation steps for older packages are no longer guaranteed to work.
So, these are best removed from the official docs.
Related blog post (also applies to skopeo):
https://podman.io/blogs/2021/03/02/podman-support-for-older-distros.html
@TomSweeneyRedHat @rhatdan @vrothberg PTAL
> Remove older distro docs

- cmd/skopeo/copy.go
- docs/skopeo-copy.1.md
- integration/copy_test.go
`podman push` gained this a while ago, and we want it here for the
same reason.
Motivated by closing a race condition in ostree-rs-ext:
https://github.com/ostreedev/ostree-rs-ext/blob/17a991050c5bf371633695b0bbd5cdbb3d717bca/lib/src/container/export.rs#L85
> copy: Add --digestfile

- .gitignore
- cmd/skopeo/copy.go
Compilation error in copy.go fixed by adding the import statement.
> Add the missing import and a gitignore entry for bin

- install.md
The Building Documentation section of the `install.md` also needs a MacOS section because go-md2man is not present there, by default, either.
> install.md Building Docs needs MacOS section

- .github/workflows/multi-arch-build.yaml
This was copy-pasted from buildah and podman, unfortunately the
Dockerfile entrypoint is different for skopeo. Fix it.
Ref: https://github.com/containers/skopeo/runs/2771691404?check_suite_focus=true
> Fix multi-arch build version check

- cmd/skopeo/copy.go
- cmd/skopeo/sync.go
- docs/skopeo-copy.1.md
- docs/skopeo-sync.1.md
It affects all transports; and without `--format`, we try several manifest formats.
Fixes #1265 .
> Fix documentation of the --format option of skopeo copy and skopeo sync

- Makefile
This partially reverts commit a81cd747341e04783e7e3a94a76c4444c3bd5cd8 so that most path variables like `PREFIX` and `BINDIR` refer to paths on the installed system, and `DESTDIR` is used only in `make install`, following the philosophy of the GNU coding standards for path variables. (But not precisely the variable names, which are lowercase in the standard, nor the principle that even `SYSCONFDIR` should be under `$PREFIX`.)
Keep the use of `?=` instead of `=` because it somewhat better expresses the idea that the values can be overridden.
Use `${DESTDIR}${BINDIR}` instead of `${DESTDIR}/${BINDIR}` etc, so that a plain `make install` does not use paths like `//usr/bin/...` ; strictly speaking they are IIRC reserved by POSIX, and more importantly it just looks untidy :)
Cc: @cevich This …
> Reintroduce the GNU semantics of DESTDIR

- go.mod
- go.sum
- vendor/modules.txt
- version/version.go
Bump containers/common to v0.38.12 and Skopeo to v1.2.4 in preparation for RHEL 8.4.0.2.  Will make a v1.2.4 release from this once merged.
> Bump to Skopeo v1.2.4, c/common to v0.38.12

- Makefile
- cmd/skopeo/login.go
- cmd/skopeo/logout.go
- cmd/skopeo/manifest.go
- cmd/skopeo/sync.go
- docs/skopeo-copy.1.md
- docs/skopeo-delete.1.md
- docs/skopeo-list-tags.1.md
- docs/skopeo-login.1.md
- docs/skopeo-logout.1.md
- docs/skopeo-standalone-sign.1.md
- docs/skopeo-standalone-verify.1.md
- docs/skopeo-sync.1.md
- docs/skopeo.1.md
- hack/man-page-checker
Add new script, hack/man-page-checker, copied from podman. Run it
in 'make validate-local' target.
This is NOT the checker requested in #1332 (verify that flags
listed in 'skopeo foo --help' are documented in man pages and
vice-versa). This is a much simpler script that merely looks
for very basic typos or discrepancies between skopeo.1.md
and skopeo-foo.1.md.
The next part (cross-checking flags) is in progress but will
require a huge number of changes to the man pages. I'm submitting
this now because it's easy to review.
> man page checker - part 1 of 2

- Makefile
- cmd/skopeo/signing.go
- docs/skopeo-list-tags.1.md
- docs/skopeo-standalone-sign.1.md
- docs/skopeo.1.md
- hack/man-page-checker
@edsantiago A few proposed follow-ups on #1347 .
One non-trivial issue is that the macOS `sed` does not support `\U` in replacements. That doesn’t matter in CI because the CI’s macOS build target runs `validate-local` _before_ building `bin/skopeo`, so the `--help` consistency checks are skipped, but it’s a hassle for local development where a `bin/skopeo` is almost always around:
```console
% hack/man-page-checker 
skopeo copy:              man='Usource-image Udestination-image' help='SOURCE-IMAGE DESTINATION-IMAGE'
skopeo delete:            man='Uimage-name' help='IMAGE-NAME'
…
```
For now this PR just carelessly compares case-insensitively, to have _something_ to fall back on if doing something better turned out to be too difficult.
> Misc man-page-checker RFCs

- cmd/skopeo/main.go
Disable the implicit `completion` command that cobra 1.2.x added.
> disable `completion` command

- integration/copy_test.go
This reverts commit 65c5b0bf8d391ab19c86c0e7d337c457369ecba5.
We never diagnosed the cause for #1093; but now that we are on a different CI implementation, let’s just blindly try to see if it happens to work now.
> Revert "integration tests: disable `ls` for logs"

- cmd/skopeo/main.go
... because our unit tests use `createApp`, so the current `main()`-only edit is not visible to unit tests.
Cc: @vrothberg , I’m afraid I have missed this originally.
> Set cobra.Command.CompletionOption already in createApp

- .cirrus.yml
- Makefile
- contrib/cirrus/runner.sh
- docs/skopeo-copy.1.md
- docs/skopeo-delete.1.md
- docs/skopeo-inspect.1.md
- docs/skopeo-list-tags.1.md
- docs/skopeo-login.1.md
- docs/skopeo-manifest-digest.1.md
- docs/skopeo-standalone-sign.1.md
- docs/skopeo-standalone-verify.1.md
- docs/skopeo-sync.1.md
- docs/skopeo.1.md
- hack/man-page-checker
- hack/xref-helpmsgs-manpages
Taking over https://github.com/containers/skopeo/pull/1350
> Implement manpage checker in CI

- integration/check_test.go
- integration/copy_test.go
- integration/openshift_shell_test.go
- integration/utils.go
The necessary images have been manually copied over to quay.  Code was
updated with centralized constants for the utilized images.  Tests then
all reference the constants (in case the image locations need to change
again).
> Fix using images from rate-limited docker hub

- cmd/skopeo/copy.go
- cmd/skopeo/delete.go
- cmd/skopeo/inspect.go
- cmd/skopeo/layers.go
- cmd/skopeo/list_tags.go
- cmd/skopeo/logout.go
- cmd/skopeo/main.go
- cmd/skopeo/sync.go
- cmd/skopeo/utils.go
- cmd/skopeo/utils_test.go
- docs/skopeo-delete.1.md
- docs/skopeo-inspect.1.md
- docs/skopeo-list-tags.1.md
- docs/skopeo-login.1.md
- docs/skopeo-logout.1.md
- Make the --help presence match deprecation status
- Warn on (skopeo --tls-verify command) again
See https://github.com/containers/skopeo/pull/1350#discussion_r667184279 for past discussion
<s>WIP, this needs unit tests and much more documentation.</s>
@edsantiago I think this works, but I’d very much appreciate a second pair of eyes.
> Fix --tls-verify

- integration/copy_test.go
- integration/openshift.go
\*cough\* Go is an easy-to-use, hard-to-misuse language \*cough\*
> Fix two instances of unused err found by go-staticcheck

- install.md
Build on Ubuntu should include pkg-config otherwise it will fail:
```
skopeo (main) # make bin/skopeo
CGO_CFLAGS="" CGO_LDFLAGS="-L/usr/lib/x86_64-linux-gnu -lgpgme -lassuan -lgpg-error" GO111MODULE=on go build -mod=vendor "-buildmode=pie" -ldflags '-X main.gitCommit=a8f0c902060288bd02db15bf6671c8cd0149704e ' -gcflags "" -tags "  " -o bin/skopeo ./cmd/skopeo
pkg-config: exec: "pkg-config": executable file not found in $PATH
make: *** [Makefile:134: bin/skopeo] Error 2
```
> Update on Building on Ubuntu

- cmd/skopeo/login.go
- cmd/skopeo/logout.go
/kind feature
We now synchronize the behavior with Podman and accept repositories during login and logout per default.
Login/logout with a repository and verify `auth.json`. Push and pull should use the credentials in the same way as the Podman integration tests described in https://github.com/containers/podman/pull/11054.
Requires https://github.com/containers/skopeo/pull/1395
Incorporates with https://github.com/containers/podman/pull/11054
```release-note
Accept repositories (and registry namespaces) on login/logout and during push/pull.
```
> Accept repositories on login/logout

- .github/workflows/check_cirrus_cron.yml
The Cirrus-CI configuration for this repository is setup to execute test
builds on certain important release branches.  There is no built-in way
to monitor these for success or failure.  This commit adds a
Github-Actions Workflow to e-mail the podman-monitor list if any fail.
Otherwise it will take no action if everything is successful.
Note: This duplicates 99.999% of the same YAML used for the Buildah
repository.  The only changes were for the settings URL and
mentioning "skopeo" in a comment.  A similar workflow is also in use
on the Podman repository.
> [CI:DOCS] Github: Add workflow to monitor Cirrus-Cron builds

- systemtest/helpers.bash
the 'signing' test is flaking; symptom is that we can never
connect to the port on the registry:
https://api.cirrus-ci.com/v1/task/6208385738604544/logs/system.log
By all indications, the registry is up, i.e., the 'podman rm -f reg'
in teardown() succeeds, as shown by the 53c (CID) in the log. (It
bothers me that the FAIL message from die() does not appear in the
log, and I can't figure out why).
To try to diagnose this, run 'podman logs' on the registry upon
failure.
> systemtests: if registry times out, show container logs

- Makefile
- hack/make.sh
> Add codespell fixes

- OWNERS
> [CI:DOCS] Add OWNERS file

- cmd/skopeo/cgo_pthread_ordering_workaround.go
- cmd/skopeo/unshare.go
- integration/openshift_shell_test.go
Go 1.17 introduces a much more reasonable build constraint format, and gofmt now fails without using it.
Sadly we still need the old format as well, to support <1.17 builds.
Signed-off-by: Miloslav Trmač <mitr@redhat.com>
> Run (gofmt -s -w)

- Makefile
- install.md
As discussed in https://github.com/containers/skopeo/issues/1411 the commit in this PR introduces a way to disable docs generation while building from source. This will allows `DISABLE_DOCS=1 make install` command to be used on setups where `go-md2man` tool isn't available for doc generation.
> Introduce DISABLE_DOCS to skip doc generation while building from source

- .cirrus.yml
Release-branches infrequently change, but the OSX VM images constantly
change.  Disable this test to avoid encountering flakes.
> Cirrus: Disable OSX task

- Makefile
- install.md
This PR is for the 1.4.x release series and brings in the changes that were merged recently against the master branch in https://github.com/containers/skopeo/pull/1443
> release-1.4: Introduce DISABLE_DOCS to skip doc generation while building from source

- .cirrus.yml
1.17 has changed the expected `gofmt` format, and we don't want to follow such changes on the stable branch.
Then re-enable the `osx` task disabled in #1449.
An alternative to #1446 .
> [release-1.4] pin go

- .cirrus.yml
Release-branches infrequently change, but the OSX VM images constantly
change.  Disable this test to avoid encountering flakes.
> [release-1.3] Cirrus: Disable OSX task

- cmd/skopeo/cgo_pthread_ordering_workaround.go
- cmd/skopeo/unshare.go
- integration/openshift_shell_test.go
This is a backport of #1427 for the release-1.4 branch.
Marked as draft to ensure there is consensus on this (vs. pinning an earlier Go version).
---
Go 1.17 introduces a much more reasonable build constraint format, and gofmt now fails without using it.
Sadly we still need the old format as well, to support <1.17 builds.
Signed-off-by: Miloslav Trmač <mitr@redhat.com>
> release-1.4: Run (gofmt -s -w)

- cmd/skopeo/flag.go
- cmd/skopeo/utils.go
- docs/skopeo-copy.1.md
- docs/skopeo-delete.1.md
- docs/skopeo-inspect.1.md
- docs/skopeo-list-tags.1.md
- docs/skopeo-login.1.md
- docs/skopeo-logout.1.md
- docs/skopeo-sync.1.md
By default skopeo checks to see if the user actually uses one of the
--*tls-verify flags. Their initial value is ignored.  Setting the
initial value to false causes Cobra to not display the default value on
the screen when the user runs a `skopeo --help` command.
If the user does not specify a --*tls-verify option, it falls back to
using the value specified in the registries.conf file.
Fixes: #1383
> Remove the extra (defaults to true) help msg

- install.md
Update installation doc with latest steps
- Remove Kubic repo suggestions where skopeo exists by default
- Include documentation about lack of Windows package
(RE: https://github.com/containers/skopeo/issues/715)
@vrothberg @mtrmac @rhatdan @TomSweeneyRedHat @lbscorpio PTAL
> Update installation doc with latest steps

- cmd/skopeo/sync.go
- completions/bash/skopeo
- docs/skopeo-sync.1.md
Fixes https://github.com/containers/skopeo/issues/1466
As noted in the linked issue, in the current form, the `sync` command aborts as soon as any image tag has issue during copy. This ends up being a blocker if any one of the image tag out of hundreds (for a particular image) has some issue.
As suggested in the linked issue, the commit in this PR introduces a `--ignore` option to the `sync` command which allows the `sync` to continue with the rest of the images/tags. When an error occurs during the image copy, that error is logged and when the sync finally finishes, such errors contribute to `sync` being marked as failed.
I have tested this change against our setup where we were running into this issue. With this change, when `--ignore` is used, the error is now logged and the next image …
> Introduce a --ignore option to allow "sync" command to continue syncing even after a particular image sync fails

- .cirrus.yml
The logic parser for `only_if` and `skip` is a little weird in that it
wants a boolean, but doesn't support using them.  In this case, using `1
== 0` results in an error from the parser:
`Error while parsing tasks: INVALID_ARGUMENT: internal boolevator error:
parsing error: 1 == 0 :1:1 - 1:2 unexpected Int while scanning
extensions!`
However, since the goal is to block this particular task from running
(essentially) indefinitely, it's easier to just remove it.  We can rely
on git recording it's history in case it needs to be recovered in the
future.
> Cirrus: Fix only_if error

- systemtest/helpers.bash
Sigh. 'expr 1 - 1' yields 0 (correctly) but also exits 1. This
is even documented in the man page, but I didn't know it. And
thus, on the final iteration, when timeout reached 0, BATS
errored out on the expr instead of continuing to the 'podman logs'
or the 'die' message.
Solution is super trivial: use $(( ... )) instead of expr.
> Fix bug that prevented useful diagnostics on registry fail

- cmd/skopeo/proxy.go
- integration/procutils.go
- integration/procutils_linux.go
- integration/proxy_test.go
proxy: Add an API to fetch the config upconverted to OCI
While the caller could fetch this today as a blob, it'd be in
either docker or oci schema.  In keeping with the model of having
this proxy only expose OCI, add an API which uses the c/image logic
to do the conversion.
This is necessary for callers to get the diffIDs, and in general
to implement something like an external `skopeo copy`.
---
proxy: Add a helper to return a byte array
Since this is shared between the manifest and config paths.
---
proxy: Use float → int helper for pipeid
Just noticed while scrolling past the code.
---
tests/integration/proxy_test: New test that exercises `proxy.go`
I debated adding "reverse dependency testing" using
https://crates.io/crates/containers-image-proxy
but I think it's easier to reuse the …
> proxy: Add `GetConfig`, add manifest list support, add an integration test

- .cirrus.yml
- contrib/cirrus/runner.sh
The Fedora 35 cloud images have switched to UEFI boot with a GPT
partition. Formerly, all Fedora images included support for runtime
re-partitioning. However, the requirement to test alternate storage
has since been dropped/removed.  Rather than maintain a disused
feature, and supporting scripts, these Fedora VM images have reverted
to the default: Automatically resize to 100% on boot.
> Cirrus: Bump Fedora to release 35 & Ubuntu to 21.10

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/docker_image_src.go
- vendor/github.com/containers/image/v5/manifest/common.go
- vendor/github.com/containers/image/v5/manifest/docker_schema1.go
- vendor/github.com/containers/image/v5/manifest/docker_schema2.go
- vendor/github.com/containers/image/v5/manifest/docker_schema2_list.go
- vendor/github.com/containers/image/v5/manifest/oci.go
- vendor/github.com/containers/image/v5/manifest/oci_index.go
- vendor/github.com/containers/image/v5/oci/layout/oci_src.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
Includes a fix for CVE-2021-41190 / GHSA-77vh-xpmg-72qh .
> Update to c/image v5.17.0

- version/version.go
… after https://github.com/containers/skopeo/pull/1512 . Includes a fix for CVE-2021-41190 / GHSA-77vh-xpmg-72qh .
> Release v1.5.2

- integration/copy_test.go
Use a dynamic temp dir for test
This test was incorrectly assuming that nothing would be made on disk,
but it was putting files into the source directory.
Signed-off-by: James Hewitt <james.hewitt@uk.ibm.com>
> Stop test producing output in source directory

- cmd/skopeo/copy.go
- completions/bash/skopeo
- docs/skopeo-copy.1.md
- integration/copy_test.go
This new --list-processing option deprecates the --all option and, when
an image index is copied, allows the user to select between copying the
image associated with the system platform, all images in the index, or
just the index itself without attempting to copy the images.
Signed-off-by: James Hewitt <james.hewitt@uk.ibm.com>
> Add an option to allow copying image indexes alone

- cmd/skopeo/proxy.go
- integration/proxy_test.go
Sadly...I swear I had tested this at one point, but it was
*definitely* not the intention that we just return the container
runtime configuration.
I need a method to return the full image configuration.  At some point
I must have accidentally added a redundant `.Config`.
This whole new method `GetFullConfig` is like `GetConfig` but
returns the whole image configuration.  A specific motivation
here is that it's only in the image configuration that we can
stick arbitrary metadata (labels) that will survive a round trip through
docker schema v2.
> proxy: Add a GetFullConfig method

- cmd/skopeo/copy.go
- cmd/skopeo/sync.go
- completions/bash/skopeo
- docs/skopeo-copy.1.md
- docs/skopeo-sync.1.md
- go.mod
- go.sum
- integration/copy_test.go
- integration/sync_test.go
- vendor/github.com/containers/image/v5/copy/copy.go
- vendor/github.com/containers/image/v5/copy/manifest.go
- vendor/github.com/containers/image/v5/types/types.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
- vendor/github.com/opencontainers/selinux/go-selinux/xattrs_linux.go
- vendor/modules.txt
When enabled, if digests can't be preserved an error will be raised.
Signed-off-by: James Hewitt <james.hewitt@uk.ibm.com>
> Add option to preserve digests on copy and sync

- go.mod
- go.sum
- vendor/modules.txt
... to silence warnings about CVE-2021-43784 / GHSA-v95c-p5hm-xq8f .
NOTE: The vulnerable code was not used in this package, so Skopeo is has not been vulnerable to this issue.
> Update github.com/opencontainers/runc to v1.0.3

- go.mod
- go.sum
- vendor/modules.txt
```
go get github.com/containerd/containerd@latest
make vendor
```
... because 1.5.9 contains a vulnerability fix, and we want to silence scanners.
NOTE: Skopeo DOES NOT use the vulnerable code that was fixed in containerd 1.5.9, so it is NOT vulnerable to GHSA-mvff-h3cj-wj9c .
---
This PR also updates opencontainers/image-spec to fix using c/image along with other Go modules that reference the 1.0.2 release tag, like https://github.com/containers/buildah/pull/3678 (that includes this containerd update).
> Update github.com/containerd/containerd to 1.5.9

- .github/workflows/check_cirrus_cron.yml
Port of changes from https://github.com/containers/podman/pull/12997 and
https://github.com/containers/podman/pull/13005 to the workflow in this
repository.
***Note***: Impractical to automatically verify these changes until
they're merged into `main`.  Though the similar changes made in the
podman repo. have been manually confirmed to function as intended.
> [CI:DOCS] Github-workflow: Report both failures and errors

- .github/workflows/check_cirrus_cron.yml
Same problem as addressed in
https://github.com/containers/podman/pull/13005 I neglected to include
in https://github.com/containers/skopeo/pull/1546 for whatever reason.
This commit makes it right.
> Github workflow: Fix yaml syntax

- docs/skopeo-copy.1.md
- docs/skopeo-delete.1.md
- docs/skopeo-inspect.1.md
- docs/skopeo-list-tags.1.md
- docs/skopeo-sync.1.md
The Go behavior of boolean flags is as follows:
Accepted values are `--flag`, which is the same as `--flag=true`, and `--flag=false`, which is the default (except for `OptionalBoolFlag`). `--flag {false,true}` is parsed as `--flag=true` with a non-option {`false`,`true`} argument.
So, for almost all flags, document them just as `--flag`, not mentioning the [`=`{`false`,`true`}] part, because users can just
omit `=true`, or the whole flag instead of `=false`.
OTOH, for `tls-verify`, document only the `tls-verify=`{`true`,`false`} variant, because the primary use is `tls-verify=false`, and because `tls-verify` is not “the default”, but equivalent to an explicit `tls-verify=true` (overriding `registries.conf`).
Fixes #1435 .
> Improve the documentation of boolean flags

- docs/skopeo-inspect.1.md
- Make the documentation of _image-name_ more useful
- Document how some data is repo/manifest/architecture-specific, to fix #1345 .
> Improve documentation of skopeo inspect

- systemtest/020-copy.bats
(or, more precisely, if fakeroot binary not in $PATH).
Solves RHEL gating-test failure.
Also, fix rootless cleanup bug (need unshare, to avoid EPERM)
> tests: skip sif test on RHEL

- systemtest/010-inspect.bats
... because it currently isn't.
(Eventually #1554, but need working CI in order to provide a c/image feature that can then be exposed in Skopeo.)
> Don't expect the config blob to be listed in (skopeo inspect)

- integration/copy_test.go
... per https://github.com/containers/skopeo/pull/1558 .
Hopefully fixes #1567, but absolutely untested.
> Resolved workaround

- install.md
The command to install skopeo for Ubuntu 20.04 includes a forced upgrade step for all packages.
Installing skopeo does not require the upgrade step, and it could lead to possible issues completely unrelated to the project.
> do not recommend upgrading all packages

- systemtest/010-inspect.bats
This a backport of https://github.com/containers/skopeo/pull/1572 to fix CI on this branch.
> [release-1.4] Don't expect the config blob to be listed in (skopeo inspect)

- cmd/skopeo/copy.go
- cmd/skopeo/proxy.go
- cmd/skopeo/sync.go
- cmd/skopeo/utils.go
- integration/check_test.go
- integration/copy_test.go
- integration/openshift.go
- integration/proxy_test.go
- integration/registry.go
- integration/sync_test.go
… found by manually running `golangci-lint`. See the individual commit messages for details.
WARNING: Completely untested.
Note that this does not actually add `golangci-lint` to the CI pipeline. Is there a standard set of linters used throughout the containers/* ecosystem? (@cevich do you happen to know?)
> Various lint fixes

- .cirrus.yml
- go.mod
- integration/copy_test.go
- integration/openshift.go
- integration/registry.go
- integration/signing_test.go
- integration/sync_test.go
- vendor/modules.txt
We already do that in practice:
```
vendor/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
```
so make that official to possibly benefit from that.
Only partially related, simplify tests using `check.C.Mkdir`.
> Formally require Go 1.15

- contrib/skopeoimage/README.md
The documentation is incomplete that tags are v-prefixed:
- https://github.com/containers/skopeo/blob/2b910649b9d86ac5dcd132ed45bb4c2551515490/contrib/skopeoimage/README.md
```
$ docker pull quay.io/skopeo/stable:1.7.0
Error response from daemon: manifest for quay.io/skopeo/stable:1.7.0 not found: manifest unknown: manifest unknown
```
> Update skopeoimage/README.md that tags are v-prefixed

- cmd/skopeo/copy.go
- completions/bash/skopeo
- docs/skopeo-copy.1.md
- go.mod
- go.sum
- integration/copy_test.go
- vendor/github.com/containers/image/v5/copy/copy.go
- vendor/github.com/containers/image/v5/copy/sign.go
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/docker_image_src.go
- vendor/github.com/containers/image/v5/docker/lookaside.go
- vendor/github.com/containers/image/v5/openshift/openshift.go
- vendor/github.com/containers/image/v5/pkg/sysregistriesv2/shortnames.go
- vendor/github.com/containers/image/v5/pkg/sysregistriesv2/system_registries_v2.go
- vendor/github.com/containers/image/v5/signature/mechanism.go
- vendor/github.com/containers/image/v5/signature/mechanism_openpgp.go
- vendor/github.com/containers/image/v5/storage/storage_image.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/github.com/docker/distribution/.mailmap
- vendor/github.com/docker/distribution/Dockerfile
- vendor/github.com/docker/distribution/README.md
- vendor/github.com/docker/distribution/docker-bake.hcl
- vendor/github.com/opencontainers/selinux/go-selinux/rchcon.go
- vendor/github.com/opencontainers/selinux/go-selinux/rchcon_go115.go
- vendor/github.com/sylabs/sif/v2/pkg/sif/arch.go
- vendor/modules.txt
This enables pushing to registries where the push and pull uris may be
different, for example where pushed images are mirrored to a read only
replica for distribution.
Closes #1588
> Add option to specify the identity for signing

- cmd/skopeo/copy.go
- cmd/skopeo/layers.go
- cmd/skopeo/manifest.go
- cmd/skopeo/signing.go
- cmd/skopeo/signing_test.go
- cmd/skopeo/sync.go
- go.mod
- go.sum
- integration/copy_test.go
- integration/openshift.go
- integration/proxy_test.go
- integration/registry.go
- integration/signing_test.go
- integration/sync_test.go
- integration/utils.go
After https://github.com/containers/storage/pull/1176 requiring Go 1.16, Skopeo will effectively require Go 1.16 as soon as it updates to that version of c/storage; so, update as well.
This is mostly trivial updates to remove references `io/ioutil`, along with a few very small optimizations (`ReadDir` and `WalkDir` not calling `lstat(2)` on every entry).
> Update to benefit from Go 1.16

- docs/skopeo-delete.1.md
… per https://github.com/containers/image/issues/1010 , at least as a short-term stopgap. Compare that issue, and #1432, for much more about possible code improvements.
- Actually add a DESCRIPTION heading.
- Warn about deleting by digest —  it affects an unknown set of tags.
- Warn about deleting by tag — it currently works by the resolved digest.
> Improve the (skopeo delete) man page

- .cirrus.yml
- contrib/cirrus/runner.sh
- hack/make/test-system
… from #1631 , so that tests on this branch, and c/image tests on the 5.19 branch, can run.
Compare https://github.com/containers/image/pull/1540 .
> [release-1.6] Backport the F36 CI image change

- Makefile
- hack/btrfs_installed_tag.sh
- hack/btrfs_tag.sh
- hack/libdm_tag.sh
- hack/tree_status.sh
Config files for non-base packages live in /usr/local/etc and **https://github.com/containers/image/pull/1544** changes the default paths in containers/image. This changes the skopeo Makefile to match.
> Config files live in /usr/local/etc on FreeBSD (highlight in release notes!)

- .github/workflows/check_cirrus_cron.yml
- .github/workflows/multi-arch-build.yaml
- .github/workflows/stale.yml
This corresponds to similar changes made in Buildah and Podman: https://github.com/containers/podman/pull/13564 https://github.com/containers/buildah/pull/3872
+ Pin actions to a full length commit SHA is currently the only way
to use an action as an immutable release. Pinning to a particular SHA
helps mitigate the risk of a bad actor adding a backdoor to the action's
repository, as they would need to generate a SHA-1 collision for a valid
Git object payload. Ref:
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
+ Explicitly set permissions for actions to minimum required.  The
defaults are (unfortunately) overly permissive: Ref:
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-fo …
> [CI:DOCS] Pin actions to a full length commit SHA

- Makefile
The {a,b} syntax is not POSIX compatible. The Makefile should run with
all POSIX shells so we cannot use shell specific features like this.
Fixes #1657
> fix make completions for all POSIX shells

- go.mod
- go.sum
- vendor/modules.txt
... to silence Dependabot alerts about CVE-2022-29162 = GHSA-f3fp-gc8g-vw66.
Note that the vulnerable code is not actually included in Skopeo at all, this is purely to silence imprecise vulnerability checkers.
> Update to github.com/opencontainers/runc >= 1.1.2

- integration/sync_test.go
The `k8s.gcr.io/coredns/coredns` repo now contains an OCI artifact, which we can't copy; so, use a different repo to test syncing.
> [release-1.4] Change a repo used for sync tests

- integration/sync_test.go
The `k8s.gcr.io/coredns/coredns` repo now contains an OCI artifact, which we can't copy; so, use a different repo to test syncing.
> [release-1.3] Change a repo used for sync tests

- integration/sync_test.go
The `k8s.gcr.io/coredns/coredns` repo now contains an OCI artifact, which we can't copy; so, **temporarily** use a different
repo to test syncing.
> Change a repo used for sync tests

- Makefile
- skopeo.spec.rpkg
The new file `skopeo.spec.rpkg` along with a webhook will automatically
build rpms on every PR merge on the main branch.
Run `rpkg local` or `make rpm` to generate the rpm.
Known issue: Doesn't yet build for EL8 environments.
@rhatdan @vrothberg @mtrmac PTAL
I have added the webhook already, so merging this should trigger an rpm build on the copr.
> CoPR: Autobuild rpm on rhcontainerbot/podman-next

- Makefile
- skopeo.spec.rpkg
@mtrmac I got too excited and merged the previous rpm PR. Just adding a cautionary note for any users tempted to use the rpm target.
@rhatdan @vrothberg PTAL
> [CI:DOCS] Makefile: include cautionary note for rpm target

- skopeo.spec.rpkg
For whatever reason, the comment rearrangement is
required for vim rpm synatx highlighting to work.
@vrothberg @mtrmac @rhatdan PTAL.
> [CI:DOCS] skopeo.spec.rpkg: Fix syntax highlighting

- integration/utils.go
... for a trivial improvement in readability.
Should not change behavior.
> Use bytes.ReplaceAll instead of bytes.Replace(..., -1)

- .cirrus.yml
Contains important updates re: preserving release-branch CI VM images.
Ref: https://github.com/containers/automation_images/pull/157
> [release-1.6] [CI:DOCS] Cirrus: Use the latest imgts container

- .cirrus.yml
Contains important updates re: preserving release-branch CI VM images.
Ref: https://github.com/containers/automation_images/pull/157
> [release-1.4] [CI:DOCS] Cirrus: Use the latest imgts container

- .cirrus.yml
Contains important updates re: preserving release-branch CI VM images.
Ref: https://github.com/containers/automation_images/pull/157
> [release-1.3] [CI:DOCS] Cirrus: Use the latest imgts container

- .cirrus.yml
Note: Removed disused `PRIOR_FEDORA*` and `UBUNTU_*` references since
they're not actually used in this CI.  Further, F35 VM images were not
built as part of `c6013173500215296` due to a missing golang 1.18
requirement for podman.
> Cirrus: Update CI VM images to match podman CI

- integration/sync_test.go
The k8s.gcr.io/coredns/coredns repo now contains an OCI artifact, which we can't copy; so, use a different repo to test syncing.
> [release-1.6] Change a repo used for sync tests

- contrib/skopeoimage/upstream/Containerfile
Running cross-platform compiles using emulation is a painfully
slow process.  Since CI-runtime is limited, improve image build time
by leveraging the automatic RPM builds occurring for the podman-next
COPR repo.  This adds build-time efficiency by offloading the
compilation task.  Note: These RPMs are built any time the 'main'
branch changes, so they'll still be very recent.
https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/
> [CI:BUILD] Optimize upstream skopeo container image build

- .github/workflows/check_cirrus_cron.yml
It's a PITA to maintain duplicate code across repos.  Relatively
github-actions added a feature that allows re-using workflows
from other repos.  Use that here to reduce duplication.
> [CI:DOCS] GHA: Re-use identical workflow from buildah repo

- cmd/skopeo/utils.go
- hack/make.sh
- integration/openshift_shell_test.go
This is primarily `gofmt` updates (the minimal version, not a full review to benefit from the new syntax).
Let’s see if the current version’s formatters accept the outcome…
> Fix building with Go 1.19

- .cirrus.yml
1.19 has changed the expected gofmt format, and we don't want to follow such changes on the stable branch.
`go@1.18` is "keg-only", i.e. not installed by Brew to `/usr/local/bin`, so we need to change `PATH` to point at it (as the installation instructs us to).
---
This is based on commit 1b6d7f79a521bdcf5947f14363211d3d3ca92c99 from the 1.4 branch.
> Pin Go to 1.18

- Makefile
Fix looking for commands with GNU make 4.2.1
Before https://git.savannah.gnu.org/cgit/make.git/commit/job.c?h=4.3&id=1af314465e5dfe3e8baa839a32a72e83c04f26ef , `make` was incorrectly trying to avoid running a shell for `command -v`.  Use the workaround recommended in https://savannah.gnu.org/bugs/index.php?57625 .
Fixes one half of (the reported problems in) #1584.
Compare #1730 .
> Workaround GNU Make 4.2.1 incorrectly executing shell commands

- README.md
- docs/skopeo-sync.1.md
- docs/skopeo.1.md
- We don't sync complete registries.
- This should still refer to the remote registry servers.
This is a proposed replacement for #1706 .
> Talk about "registry repositories" in (skopeo sync) documentation

- Makefile
Fixes #1707.
See individual commit messages for details.
> Don't include git commit from a parent directory in the --version output

- cmd/skopeo/sync.go
The user is not very likely to be able to do anything about that, and we have no other way to read those images - so just skip them; we already skip image copies in much more directly user-caused situations, including invalid user-provided strings.
Fixes #1740, hopefully (untested).
> Don't abort sync if the registry returns invalid tags

- default.yaml
Rely on the hard coded defaults in libraries rather then overriding in the yaml file.
> default.yaml should have all options commented

- version/version.go
`skopeo inspect` now provides more information about individual layers.
The default `/etc/containers/registries.d/default.yaml` now has all entries commented-out, to use built-in defaults; that can change the default for `lookaside-staging` to use an unprivileged users’ home directory instead of a path in `/var/`.
-  GHA: Re-use identical workflow from buildah repo
-  Optimize upstream skopeo container image build
-  Fix running tests on macOS
-  Reformat with Go 1.19's gofmt
-  Fix a comment
-  Fix looking for commands with GNU make 4.2.1
-  Talk about "registry repositories" in (skopeo sync) documentation
-  Point at --all in the --preserve-digests option documentation
-  Remove unused GIT_BRANCH definition
-  Don't include git commit from a parent directory in the --version output
- …
> Release v1.10.0

- cmd/skopeo/proxy.go
I should have done this in the previous commit, it's how clients can discover that we have the API.
Signed-off-by: Colin Walters <walters@verbum.org>
> proxy: Bump semver for OpenImageOptional

- version/version.go
Given there is a release-1.10 branch, we should bump main to the next minor version.
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>
> bump to v1.11.0-dev

- .cirrus.yml
- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/errors.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
Just https://github.com/containers/image/pull/1695 + tagging 1.9.3.
> [release-1.9] 1.9 backports

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/errors.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
... to include https://github.com/containers/image/pull/1696 and to make sure the release-1.10 branch is not regressing against release-1.9.
```sh
go get github.com/containers/image/v5@release-5.23
make vendor
```
> [release-1.10] Update c/image from the release-5.23 branch

- integration/registry.go
Fix a bug found by `golangci-lint run --enable-all ./...`
> Close a HTTP response body

- .github/renovate.json5
The `behind-base-branch` setting means:
Renovate will rebase whenever the branch falls 1 or more
commit behind its base branch
> Renovate: Override global no-rebase option

- .cirrus.yml
- contrib/cirrus/ostree_ext.dockerfile
This does reverse-dependency testing, verifying `proxy.go` using the ostree-rs-ext Rust code's unit tests.
Based on #1781 by @cgwalters
> Cirrus: Add reverse-deps. test to verify proxy with ostree-rs-ext

- .cirrus.yml
Migrate our OSX build to a M1 instance, since Cirrus is sunsetting Intel-based macOS instances.
Signed-off-by: Ashley Cui <acui@redhat.com>
> [CI:BUILD] Cirrus: Migrate OSX task to M1

- README.md
- docs/skopeo-inspect.1.md
I discovered skopeo via [this link](https://docs.gitlab.com/ee/user/packages/container_registry/reduce_container_registry_data_transfer.html#determine-image-size) in the gitlab docs which advertises skopeo for exposing layer sizes. I then got confused by the layer sizes not being exposed in the "skopeo inspect" example of the README. Now I realize this to be a rather new feature, and this PR updates the documentation for it.
Fix:
---
Since d9dfc44 the 'skopeo inspect' command exposes the LayerData which often contains the layer size. This is a very useful feature so we mentioned it in the README now.
> README: Update example to show newly exposed LayerData

- cmd/skopeo/sync.go
- docs/skopeo-sync.1.md
Adds the option to append the sync timestamp to the destination image tag. 
This is useful for syncing source containers which have non-immutable tags to a destination which does have immutable tags, and allows a point-in-time view of the moving source tag.
For example - source `ubuntu:bionic` would be synced to `<host>/ubuntu:bionic-1664722433` with the `--append-timestamp` flag specified.
> Adds `--append-suffix` flag to sync command

- docs/skopeo-copy.1.md
... with the image correctly tagged.
I also snuck a warning against `docker-archive:` in there.
Fixes #1609 . (I could well see an argument that this is not worth the space in the man page and that #1609 should just be closed.)
> Add an example for creating a docker-archive file

- cmd/skopeo/proxy.go
Missing `.Close()` on the blob currently leaks a temporary file.  Noticed this when doing repeated pulls.
Signed-off-by: Colin Walters <walters@verbum.org>
> proxy: Fix leak of blobs from containers-storage

- cmd/skopeo/inspect.go
- cmd/skopeo/sync.go
Should not change behavior - it would matter for unit tests which don't exist.
Also, `promptForPassphrase` must continue to hard-code "real" `os.Stdin` and `os.Stdout`.
So, this is just a low-priority pedantic cleanup.
> Correctly use the stdout parameter in some places

- .cirrus.yml
This task does not make sense to maintain long-term on release
branches.  Its intent is always/only to test the latest/greatest code
and environment.  After release, it's simply too difficult to maintain
functioning CI with a constantly changing (Cirrus-managed) OSX environment.
Ensure the task only runs for PRs targeted at the default branch, or if
the current branch is the default branch.
See also:
* https://github.com/containers/skopeo/pull/1851
* https://github.com/containers/skopeo/pull/1852
> Cirrus: Skip OSX CI on release-branches

- contrib/cirrus/runner.sh
The containers/image CI setup reuses the runner script from this repo to execute the skopeo tests.  However, an env. var. is being taken out of context in that environment, leading to failure.  Fix this by hard-coding an image-name which will always be available in both environments.
> Cirrus: Fix c/image CI testing

- Makefile
- systemtest/040-local-registry-auth.bats
This, _together with #1864_, allows running `make test-system` as an unprivileged user. (It doesn’t work for me as `root` and I don’t currently think it’s worth spending time on that.)
That makes the “single Linux developer” use case working again… in case anyone cares.
> Fix `make test-system` when run as an unprivileged user (containerized)

- docs/skopeo-copy.1.md
- docs/skopeo-delete.1.md
- docs/skopeo-generate-sigstore-key.1.md
- docs/skopeo-inspect.1.md
- docs/skopeo-list-tags.1.md
- docs/skopeo-login.1.md
- docs/skopeo-logout.1.md
- docs/skopeo-manifest-digest.1.md
- docs/skopeo-standalone-sign.1.md
- docs/skopeo-standalone-verify.1.md
- docs/skopeo-sync.1.md
- Add a prompt to the skopeo commands.
- Add a "console" identifier to fenced code blocks which has a prompt, not "sh".
Signed-off-by: Toshiki Sonoda <sonoda.toshiki@fujitsu.com>
If the commands has a prompt, we should use a "console" identifier.
> [CI:DOCS] Format manual page documents

- cmd/skopeo/sync_test.go
This is a security-critical piece of code, make sure we detect if it breaks.
Compare #1885.
> Add unit tests for tlsVerifyConfig's yaml.Unmarshaler

- skopeo.spec.rpkg
This common set seemed to work for all envs:
- disable debuginfo
- GO111MODULE=on
TODO: enable GO111MODULE=off
TODO: enable debuginfo
Fedora 35 builds are disabled, so remove fedora 35
conditionals while we're at it.
Successful el8 build with this change: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/5082067/
@mtrmac @vrothberg @rhatdan PTAL
> [CI:BUILD] copr: fix el8 build

- skopeo.spec.rpkg
Follow up on #1816.
successful build at: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/5407239/
> [CI:BUILD] enable debuginfo for el8 copr builds

- cmd/skopeo/generate_sigstore_key_test.go
- cmd/skopeo/utils.go
- contrib/skopeoimage/README.md
- systemtest/040-local-registry-auth.bats
> Run codespell on codebase

- .packit.sh
- .packit.yaml
This commit will run COPR builds on every PR against all active releases of CentOS Stream and Fedora, thus allowing buildability checks before the PR merges.
Builds are done on a custom COPR project:
`rhcontainerbot/packit-builds`.
Ref: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/
The build targets are set in the copr itself, so we don't need to explicitly mention them in `.packit.yaml`, making upstream configuration a lot simpler.
The `spec.rpkg` file meant for rpm builds post-pr-merge at `rhcontainerbot/podman-next` copr gets reused for packit builds, so the packit jobs are independent of Fedora / CentOS dist-git.
NOTE: The Packit copr_build tasks help to check if every commit builds on
supported Fedora and CentOS Stream arches. They do not block the current …
> [CI:BUILD] Packit: initial enablement

- cmd/skopeo/inspect.go
`tabwriter` buffers lines that contain `\t` in memory, and only writes them out on a `.Flush()`. So actually call that.
Without this, things like `--format 'name\tdigest\tlabels\n{{.Name}}\t{{.Digest}}\t{{.Labels}}\n'` result in no output at all.
> Fix tabelating output in (skopeo inspect --format)

- cmd/skopeo/inspect.go
- docs/skopeo-inspect.1.md
This uses the common library reporter template generation, so that we can use the DefaultFuncs in format output: https://github.com/containers/common/blob/main/pkg/report/template.go#L37
> Use common library reporter

- cmd/skopeo/list_tags.go
- cmd/skopeo/main.go
- integration/check_test.go
- integration/copy_test.go
- integration/proxy_test.go
- integration/registry.go
- integration/sync_test.go
- integration/utils.go
golangci-lint linter: unparam
This primarily fixes TestProxy to test the correct image.
> Fix some warnings

- cmd/skopeo/inspect.go
Just a cleanup, should not change behavior.
> Avoid duplicated code in `skopeo inspect`

- systemtest/040-local-registry-auth.bats
Need to restore `XDG_RUNTIME_DIR` when podman removes the registry.
---
The test fails on rootless because it fails to remove the registry container.
<details>
<summary>tests are failed on rootless</summary>
```
ok 1 auth: credentials on command line
not ok 2 auth: credentials via podman login
ok 3 auth: copy with --src-creds and --dest-creds
not ok 4 auth: credentials via authfile
```
</details>
<details>
<summary>tests are succeeded on rootless after applying this commit</summary>
```
ok 1 auth: credentials on command line
ok 2 auth: credentials via podman login
ok 3 auth: copy with --src-creds and --dest-creds
ok 4 auth: credentials via authfile
```
</details>
> systemtests: Fix 040-local-registry-auth about XDG_RUNTIME_DIR

- cmd/skopeo/signing.go
- cmd/skopeo/signing_test.go
- docs/skopeo-standalone-verify.1.md
- integration/signing_test.go
- systemtest/050-signing.bats
Add the ability to use an on-disk trust store to verify signatures. Also allow the user to trust any known fingerprint instead of having to specify one.
The reason here is that we now have a number of different keys we have used to sign our images over time as they have been rotated. Being able to supply someone with a keystore they can use to verify any of our images with is valuable to us.
> Verify signatures from a list of public keys

- cmd/skopeo/unshare_linux.go
This is reported by golangci-lint in #1967 .
(Absolutely untested.)
> Avoid use of a deprecated capability.NewPid

- cmd/skopeo/signing.go
`signature.NewEphemeralGPGSigningMechanism is called` in an `if` branch where the previous `err :=` introduces a "new" `err` variable, which means the failure isn't visible after the `if`.
So, do the dumb thing and just check on both branches explicitly. (We still need to worry about correctly setting `mech` and `publicKeyfingerprints` to persist after the `if`.)
How I hate Go sometimes. And this shows we really should update the linter.
> Fix error handling of signature.NewEphemeralGPGSigningMechanism

- docs/skopeo-copy.1.md
- docs/skopeo-delete.1.md
- docs/skopeo-generate-sigstore-key.1.md
- docs/skopeo-inspect.1.md
- docs/skopeo-list-tags.1.md
- docs/skopeo-login.1.md
- docs/skopeo-logout.1.md
- docs/skopeo-standalone-sign.1.md
- docs/skopeo-standalone-verify.1.md
- docs/skopeo-sync.1.md
- docs/skopeo.1.md
... primarily to make the top-level options more discoverable.
Should help a bit with #1914 .
> Cross-link the top-level and subcommand option lists

- version/version.go
More template functions available in `skopeo inspect --format`
Adds new ways to supply trusted keys to `skopeo standalone-verify`.
Now requires Go 1.18.
- [CI:DOCS] Fix up language in README
- Add unit tests for tlsVerifyConfig's yaml.Unmarshaler
- Cirrus: Use human-readable CI VM Images
- [CI:BUILD] copr: fix el8 build and enable debuginfo
- [CI:BUILD] enable debuginfo for el8 copr builds
- Update to use, and benefit from, Go 1.18
- [CI:DOCS] Disable dependabot
- Renovate: c/common rule moved to defaults
- [CI:BUILD] Packit: initial enablement
- Replace gopkg.in/check.v1 by github.com/stretchr/testify/suite/
- Corrected typo in skopeo-sync and updated description
- Fix tabelating output in (skopeo inspect --format)
- Use common library reporter
- Fix formatting of inspect examples
- Use …
> Release 1.12

- install.md
- Accurately document the effect of `GO_DYN_FLAGS`
- Fix a typo
- Remove a shell script example; removes a `docker` command, we don't care to maintain it to run correctly, and anyone knowledgeable enough to understand the trade-offs of static linking can almost certainly create that from scratch.
Fixes #1700
> Improve the static build documentation a tiny bit

- contrib/cirrus/runner.sh
This branch will never receive any security-backports when the associated RHEL release reaches EOL.  Add a condition to force CI to break with a helpful message, after this RHEL EOL date.
> [release-1.3] Cirrus: Add CI self-destruct condition on EOL date

- contrib/cirrus/runner.sh
This branch will never receive any security-backports when the associated RHEL release reaches EOL.  Add a condition to force CI to break with a helpful message, after this RHEL EOL date.
> [release-1.11] Cirrus: Add CI self-destruct condition on EOL date

- .github/renovate.json5
- Makefile
It's a bit cumbersome to manage a tooling version buried deep in a command, let alone one also buried deep in a `Makefile`.  Add a variable to hold the version number so renovate can easily manage it. This happens via a `regex` manager in the shared configuration include `containers/automation//renovate/defaults.json5`.  Also add a helpful note/reminder to humans who may want to manually change the version for some reason.
Depends on: https://github.com/containers/automation/pull/145
> Help Renovate manage the golangci-lint version

- rpm/skopeo.spec
- rpm/update-spec-provides.sh
Distro conditionals have been rewritten in a cleaner
and easier to read way.
All `bcond` macros have been replaced with friendlier alternatives.
Also removed macros related to `import_path` as they are no longer
necessary.
> Packit: easier to read distro conditionals

- rpm/skopeo.spec
For Fedora, we need to ensure ELN builds are successful.
The recent skopeo builds have been failing on copr because of /usr/bin/go-md2man being available via different package names. https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/6119200/
This commit changes go-md2man dependency directly on the binary path instead of a pacakge.
ELN scratch builds are now successful:
https://koji.fedoraproject.org/koji/taskinfo?taskID=102706281
> [CI:BUILD] RPM: fix ELN builds

- cmd/skopeo/proxy.go
Helps address the lack of policy verification in rpm-ostree:
https://github.com/coreos/rpm-ostree/issues/4272
An Image pull triggered by `rpm-ostree rebase` will look to verify the policy by default as a part of `OpenImage` 
The other route taken here adds a new API call
https://github.com/containers/skopeo/issues/1829
> proxy: Policy verification of OCI Image before pulling

- version/version.go
As the title says.  Bumping the version to dev
in the 1.13 release branch.
> [release-1.13] Bump to v1.13.1-dev

- rpm/update-spec-provides.sh
The default Packit sandbox environment that runs Packit tasks for downstream Fedora does not have golist installed by default and can't run superuser tasks.
This commit will download and extract the golist binary from the Fedora rpm and use it to provide golist.
The GOPATH mention in `rpm/update-spec-provides.sh` is only required for golist to generate the gopaths and doesn't affect upstream or the rpm spec.
Currently, the only way to reliably test this is on an open github issue by running `/packit propose-downstream`. This can't be run on an open PR. The job-specific packit actions can only be tested via the packit service and not via packit cli.
(cherry picked from commit a39972ca35e334b0f04ac999f57faf1ec32cdc79)
> [release-1.13 backport] [CI:BUILD] Packit: install golist before updating downstream spec

- cmd/skopeo/proxy.go
- integration/proxy_test.go
In PR review for a different issue, the question of what happens if we hit overflow for the imageid serial was hit.  This feels pretty unlikely; if I did the math right, it'd require opening an average of 136 images per second to overflow it in a year. Nevertheless, in practice what we're sending on the wire is just a JSON number, and if we extend this to the "max safe JSON number" of 2^53, it'd take 285,616,414 images per second to overflow in a year, going from implausible to probably impossible.
With a bit more work of course, we could make this a sparse mapping and reuse freed numbers, but eh.
> proxy: Change the imgid to uint64

- cmd/skopeo/proxy.go
See individual commit messages for details.
> Follow-up fixes to #2029

- version/version.go
In preparation for functional freeze for RHEL 8.9/9.3, create Skopeo v1.31.1 and then bump it to 1.13.2-dev in this branch.
I'll tag and spin a release after this merges for Jindrich.
> [release-1.13] Bump to v1.13.1

- rpm/skopeo.spec
The current gobuild macro doesn't account for build tags on both c9s and c8s. This is currently causing copr build failures for c9s.
Ref: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/6220412/
This commit will define gobuild for all those envs until gobuild is fixed by default.
Refs:
c9s bz: https://bugzilla.redhat.com/show_bug.cgi?id=2227328
c8s bz: https://bugzilla.redhat.com/show_bug.cgi?id=2227331
> RPM: define gobuild macro for rhel/centos stream

- go.mod
We already require it, because docker/credential-helpers uses Go 1.19 os/exec.Cmd.Environ(). So make that official.
> go mod tidy -go=1.19
> Update to Go 1.19

- go.mod
- go.sum
- vendor/modules.txt
- version/version.go
Readying for final release for RHEL 8.9/9.3.  Bumping c/common to v0.55.3 and Skopeo to 1.13.2, then 1.13.3-dev
> [release-1.13] Bump c/common to v0.55.3, skopeo to 1.13.2 and 1.13.3-dev

- rpm/skopeo.spec
The current gobuild macro doesn't account for build tags on both c9s and c8s. This is currently causing copr build failures for c9s.
Ref: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/6220412/
This commit will define gobuild for all those envs until gobuild is fixed by default.
Refs:
c9s bz: https://bugzilla.redhat.com/show_bug.cgi?id=2227328
c8s bz: https://bugzilla.redhat.com/show_bug.cgi?id=2227331
(cherry picked from commit ab892075114ac08881e074513817e631fc140e94)
> [release-1.13 backport] RPM: define gobuild macro for rhel/centos stream

- rpm/skopeo.spec
The lowercase `and` in the License field isn't compatible with spdx license format.
This commit replaces all `and` with `AND` in the License field in spec.
> rpm: spdx compatible license field

- rpm/skopeo.spec
The lowercase `and` in the License field isn't compatible with spdx license format.
This commit replaces all `and` with `AND` in the License field in spec.
(cherry picked from commit b87a1b3e8ef775fd79215c245b8748ea4692adf0)
> [release-1.13 backport] rpm: spdx compatible license field

- .cirrus.yml
These jobs have been failing since early August due to technical/scripting problems.  Disable/remove entirely since a fix is unlikely to be implemented anytime soon.
If anybody ever cares, I gave up trying to debug the script problem in https://github.com/containers/podman/pull/19720.
> Cirrus: Remove multi-arch skopeo image builds

- .github/workflows/discussion_lock.yml
Lock discussions on closed PRs and Issues after 90-days of inactivity.
Ref:
https://github.com/containers/podman/discussions/19012
and
https://github.com/containers/podman/pull/19691
and
https://github.com/containers/podman/pull/19700
> [skip-ci] GHA: Closed issue/PR comment-lock

- .packit.yaml
This change will auto-tag @lsm5 in a github comment on every copr build failure.
@mtrmac @vrothberg PTAL
> Packit: tag @lsm5 on copr build failures

- docs/skopeo-copy.1.md
Since this comes from the underlying c/image library.
> copy: Note support for `zstd:chunked`

- version/version.go
As the title says.
Bumping to v1.14.0 and then to v1.14.1-dev in preparation for RHEL 8.10/9.4
> Bump to v1.14.0

- contrib/cirrus/runner.sh
Fedora 36 repos no longer exist, so these installations always fail: https://cirrus-ci.com/build/5827089207656448 .
The SIF test in systemtest/020-copy.bats is already conditionalized on the presence of the tools, so it should now be skipped.
> [release-1.6] Stop trying to install sif prerequisite RPMs

- integration/check_test.go
- integration/copy_test.go
- integration/openshift_shell_test.go
- integration/utils.go
`release-1.3` CI has started failing, e.g. https://cirrus-ci.com/task/6649192429387776 . Apparently, at least `docker.io/library/busybox` used to be a schema2 image and now it is an OCI one.
This backports #1382, which replaces `docker.io` images with images maintained at `quay.io/libpod`.
> [release-1.3] Fix using images from rate-limited docker hub

- hack/libsubid_tag.sh
Currently, `$(hack/libsubid_tag.sh)` produces no buildtag output. This patch fixes it.
1. Library arguments must be positioned after sources when invoking GCC.
2. Use new function name: `subid_get_uid_ranges`.
Refs:
rhbz: https://bugzilla.redhat.com/show_bug.cgi?id=2254902
podman file: https://github.com/containers/podman/blob/main/hack/libsubid_tag.sh
@mtrmac @rhatdan PTAL
> Fix libsubid detection

- version/version.go
As the title says.
Skopeo v1.14.1 is headed for RHEL 8.10/9.4.  Once this first commit below merges, I'll create a release and a release branch (release-1.14) from it.  We'll then continue working on Skopeo v1.15.0-dev in main, and will target 1.15 or another Y version towards RHEL 9.5/10.0 beta sometime in the fall of 2024.
> Bump to v1.14.1, and then to v1.15.0-dev

- install.md
As we found out with kind Sir Miloslav Trmač, CGO_ENABLED has to enabled in order for the installed system libraries to get used and compile successfully.
Best Regards!
> [DOCS]: make sure that CGO_ENABLED is enable

- cmd/skopeo/unshare.go
Should not change behavior.
`gopls` 0.15 newly warns about the unused parameter.
> Avoid a warning by gopls / VSCode

- go.mod
Otherwise go tends to create a third section at every opportunity.
Should not change behavior.
> Move a go.mod dependency entry to the right section

- version/version.go
As the title says.  Given the changes to the c/* projects underneath Skopeo, I thought it would make sense to create a version that is using the same level of the c/* projects as Podman v5.0 and Buildah v1.35.  If this merges, I'll create a release and a release branch.
Setting main to 1.16.0-dev at the end of this.
> Bump to v1.15.0 and then to v1.16.0-dev

- rpm/skopeo.spec
This removes the need for any `Provides: bundled()` we needed in spec files.
The updated Provides will be visible in the build logs and can also be verified with `rpm -q --provides $RPM_FILE`.
> [skip-ci] rpm: use macro supported vendoring

- go.mod
This is needed on the off-chance that some tool or a human suggests updating the minimum version to 1.21 or later. Since doing so would cause Fedora and Debian to start behaving differently WRT builds.
Ref: https://github.com/containers/podman/pull/22073
> [CI:DOCS] Add golang 1.21 update warning

- go.mod
- go.sum
- vendor/modules.txt
- version/version.go
Bump c/common to v0.57.4, then Skopeo to v1.14.3.
This is in preparation for RHEL 8.10/9.4
> [release-1.14] Bump c/common to v0.57.4, Skopeo to v1.14.3

- cmd/skopeo/list_tags.go
- go.mod
- install.md
- integration/utils.go
After https://github.com/containers/image/pull/2337 (notably https://github.com/go-openapi/swag/compare/v0.22.10...v0.23.0 ), c/image will require Go 1.20 to build.
This does not yet update to that version of c/image, but that will happen soon enough.
So, update to Go 1.20, and take advantage of new standard library features.
> Update to Go 1.20

- cmd/skopeo/copy.go
- docs/skopeo-copy.1.md
It would be useful when there are many layers while most of layers are unchanged between versions.
See discussion at https://github.com/nlewo/nix2container/pull/125
> feat: add `--image-parallel-copies` flag

- .github/workflows/issue_pr_lock.yml
Followup to https://github.com/containers/podman/pull/22304
This will stop the torment of failure-alert e-mails due to the filename change.
> [skip-ci] Fix issue/pr lock workflow

- integration/copy_test.go
This branch is used by the c/image `release-5.29` branch.
> [release-1.14] Backport #2280

- integration/copy_test.go
... because the tests are assuming a v2s2 image, but as of Fedora 39, the image uses the OCI format.
> [release-1.11] Backport #2280

- integration/copy_test.go
This branch is used by the c/image `release-5.26` branch.
> [release-1.13] Backport #2280

- README.md
- docs/skopeo-standalone-sign.1.md
- docs/skopeo-standalone-verify.1.md
- docs/skopeo.1.md
Correct the summary for `standalone-sign`. The old summary appears to be a bad copy-and-paste from `skopeo copy`.
Clarify that both of these tools are debugging tools, only operating on local files.
> fix summaries for `standalone-sign` and `standalone-verify`

- .packit.yaml
This commit will enable downstream syncing to CentOS Stream 10. The
centos maintainer will need to manually run `packit propose-downstream`
and `centpkg build` until better centos integration is in place.
This commit also builds both rhel9 and centos9 copr rpms so we can check
for things like differences in golang compiler.
> Packit c10s

- README.md
In the Buildah repo, we had a request for a ptr to the container image location in the docs.  We've added similar to Podman and Buildah.
> Add info on Skopeo image to README.md

- rpm/skopeo.spec
The bats package is not available on RHEL. It's in Fedora and EPEL.
Having bats as a requirement for the `skopeo-tests` subpackage will cause installibility test failures for RHEL 10 / C10S gating tests.
This commit makes `bats` a requirement only on Fedora. RHEL and CentOS Stream gating will need to fetch bats through separately enabling EPEL or other means.
Podman PR with similar change: https://github.com/containers/podman/pull/22632
> [skip-ci] RPM: bats requirement only on Fedora

- hack/btrfs_installed_tag.sh
- hack/btrfs_tag.sh
- hack/libsubid_tag.sh
Until now `cc' was hard-coded as the only compiler used.  Supporting selecting the compiler and preprocessor to be used via environment variables makes life easier for distributors, so this commit mimics how podman does it in its hack/* scripts.
Fixes #2278.
> hack: Support picking cc and cpp via environment variables.

- Makefile
- rpm/skopeo.spec
The code has now been completely removed and nothing checks for that tag.
> Stop using the exclude_graphdriver_devicemapper build tag

- .packit.yaml
Without this change, packit will trigger duplicate jobs on podman-next for `skopeo-fedora`, `skopeo-centos` etc, which essentially point to the same spec file.
1 triggered job builds packages for all environments enabled on the COPR, so simply `skopeo-fedora` should suffice.
> [skip-ci] Packit: `packages: [skopeo-fedora]` for podman-next jobs

- .packit.yaml
We only care about buildability on epel 9 (RHEL). It won't be shipped to centos stream or to fedora.
> Packit: update packit targets

- .cirrus.yml
Changes:
- fix from @mtrmac for go-1.22 panic ("alphabet, duplicate symbols")
- debian is now cgroupsv2 + crun (does not affect skopeo)
- many other Red Queen fixes
Built in: https://github.com/containers/automation_images/pull/338
> CI: bump VMs

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/copy/progress_bars.go
- vendor/github.com/containers/image/v5/copy/single.go
- vendor/github.com/containers/image/v5/directory/directory_dest.go
- vendor/github.com/containers/image/v5/directory/directory_src.go
- vendor/github.com/containers/image/v5/directory/directory_transport.go
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/docker_image_src.go
- vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go
- vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go
- vendor/github.com/containers/image/v5/docker/registries_d.go
- vendor/github.com/containers/image/v5/openshift/openshift_src.go
- vendor/github.com/containers/image/v5/ostree/ostree_dest.go
- vendor/github.com/containers/image/v5/ostree/ostree_src.go
- vendor/github.com/containers/image/v5/storage/storage_dest.go
- vendor/github.com/containers/image/v5/storage/storage_image.go
- vendor/github.com/containers/image/v5/storage/storage_reference.go
- vendor/github.com/containers/image/v5/storage/storage_src.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
Add the fix to the release-14 branch for CVE-2024-3727.  This will fix the issue in OCP v4.16 and RHEL 8.10/9.4
Currently addresses: https://issues.redhat.com/browse/OCPBUGS-33267 until the RHEL 8.10  and 9.4 Jira cards are created.
> [release-1.14] CVE-2024-3727 

- .cirrus.yml
- contrib/cirrus/mac_cleanup.sh
Previously this task ran using the Cirrus-CI compute service, consuming compute credits.  However, since podman is already using a persistent worker pool for CI, it can also be leveraged for use here.  Since Mac resources are relatively expensive, it also makes financial sense to re-use infrastructure where possible.
Notes:
- This change also restricts the cross-build task to only running on the default branch.  This is necessary because the PW Pool environment is always rolling forward and may not match what was in place at the time a release-branch was created.
- This changes the test from an install + run, to just a build + run. This is required because the task is running as a regular user w/o permissions to install anything system-wide, on a host shared with other CI tasks.
> Execute cross-build task using PW pool

- integration/copy_test.go
- integration/sync_test.go
> [release-1.14] Refer to registry.k8s.io instead of k8s.gcr.io

- integration/copy_test.go
- integration/sync_test.go
> [release-1.13] Refer to registry.k8s.io instead of k8s.gcr.io

- integration/copy_test.go
- integration/sync_test.go
> [release-1.11] Refer to registry.k8s.io instead of k8s.gcr.io

- integration/copy_test.go
- integration/sync_test.go
> [release-1.6] Refer to registry.k8s.io instead of k8s.gcr.io

- integration/copy_test.go
- integration/sync_test.go
> [release-1.3] Refer to registry.k8s.io instead of k8s.gcr.io

- integration/copy_test.go
- integration/sync_test.go
> [release-1.15] Refer to registry.k8s.io instead of k8s.gcr.io

- .packit.yaml
This commit will enable downstream syncing to CentOS Stream 10. The centos maintainer will need to manually run `packit propose-downstream` and `centpkg build` until better centos integration is in place.
This commit also builds both rhel9 and centos9 copr rpms so we can check for things like differences in golang compiler.
(cherry picked from commit 1d70f69326d4e1b80aa917d6720d5c82a0e54949)
> [release-1.15 backport] [skip-ci] Packit: enable c10s downstream sync

- rpm/skopeo.spec
All our supported distros except CentOS Stream 9 support autochangelog and we currently build rpms for CentOS Stream 9 only on the podman-next copr, where we don't really care much about changelog.
So, there's no need for this conditional to exist.
Podman Ref: https://github.com/containers/podman/pull/23110
> [skip-ci] RPM: spec file cleanup

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
Fixes an interoperability issue while listing tags in JFrog Artifactory may fail
Addresses: https://github.com/containers/skopeo/issues/2346
> [release-1.15] Fixes an interoperability issue while listing tags, bump to v1.15.2

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
- version/version.go
Addresses the problem first described in https://github.com/containers/skopeo/issues/2346
in the release-1.14 branch
Also addresses: https://issues.redhat.com/browse/RHEL-40801
https://issues.redhat.com/browse/RHEL-40805
> [release-1.14] Fixes Listing tags in JFrog Artifactory may fail

- version/version.go
Bump c/storage to v1.55.0, c/image to v5.32.0, and c/common to v0.60.0.  
Then bump to Skopeo v1.16.0, then back to the v1.17.0-dev version in the main branch.
This to coincide with the Podman v5.2 release and to ready for the RHEL
9.5/10.0 Beta release
> Bump to Skopeo v1.16.0

- rpm/skopeo.spec
The fakeroot package doesn't exist in RHEL.
> The fakeroot package doesn't exist in RHEL.

- hack/get_fqin.sh
- hack/man-page-checker
- systemtest/010-inspect.bats
- systemtest/helpers.bash
This should silence any `egrep is obsolescent; using grep -E` warnings.
> Replace egrep with grep -E

- .packit.yaml
- go.mod
- install.md
- integration/registry.go
Cc: @Luap99 
@lsm5 PTAL — marking as draft to let you review, to make sure this is not a problem for downstream.
> Update to Go 1.22

- docs/skopeo-copy.1.md
A part of https://github.com/containers/common/issues/2117 .
> Document that zstd:chunked is downgraded to zstd when encrypting

- cmd/skopeo/sync.go
- docs/skopeo-sync.1.md
Added `--digestfile` for skopeo `sync` option
* This will create the digest file if not exists. 
* Will append the sha and image reference for each image that is copied separated by space. 
* This option would not be available in `dry-run` flag is set.
> Add support for `--digestfile` for skopeo `sync`

- .packit.yaml
This constraint helps to avoid duplicate Packit jobs. The effect will only be seen at the time of Fedora koji build and not on upstream. This doesn't affect upstream.
> Packit: constrain downstream koji job to fedora package

- .packit.yaml
This constraint helps to avoid duplicate Packit jobs. The effect will only be seen at the time of Fedora koji build and not on upstream. This doesn't affect upstream.
(cherry picked from commit 6ad77a1bc4418ba0976c4f91cae696622248c9aa)
> [backport release-1.16] Packit: constrain downstream koji job to fedora package

- cmd/skopeo/proxy.go
After a manually-pushed version of #2400 .
Cc: @cgwalters .
(There are some indications the tests are going to fail for an unrelated purpose later; if so, I’ll include a fix for that in this PR.)
> Fix format string inconsistency causing a build failure

- systemtest/helpers.bash
The "2" tag is very old and not a multi arch manifest. As such testing on aarch64 failed because it pulled and x86_64 image instead. This was found in downstream RHEL testing.
The "2.8.2" is multi arch and used in podman testing were we successfully run aarch64 based testing.
> systemtest: update quay.io registry image

- cmd/skopeo/utils.go
- docs/skopeo-copy.1.md
- docs/skopeo-delete.1.md
- docs/skopeo-inspect.1.md
- docs/skopeo-list-tags.1.md
- docs/skopeo-sync.1.md
- Add option to set a fixed delay between retries.
- Clarify that if delay is unset, skopeo uses an exponential delay for retries.
Fixes #2476
> feat: Add `--retry-delay` Option

- rpm/skopeo.spec
The default gobuild macro on CentOS Stream now accounts for `BUILDTAGS`, so we don't need to redefine the macro in rpm spec.
> RPM: cleanup gobuild macro for CentOS Stream

- version/version.go
As the title says, bumping to v1.18.0 to go out with Podman v5.4.
> Bump Skopeo to v1.18.0, then to v1.19.0-dev

- .packit.yaml
- go.mod
- install.md
This is a very minimal change, just to handle the version bump.
I intend to let Renovate do the dependency updates. And a separate PR to actually benefit from new language features will follow.
> Update to Go 1.23

- cmd/skopeo/inspect.go
- cmd/skopeo/layers.go
Nobody should be using `skopeo layers`.
For `skopeo inspect`, I could see an argument that it should return the data even if it does not match the digest, so that users can diagnose that. On balance, I think matching the expectation that digests are enforced is more valuable.
> Enforce manifest and blob digests in (skopeo inspect) and (skopeo layers)

- .packit.yaml
Switch to keeping TMT tests independent of PR labels for now.
In order to keep PR-label dependent tests, Packit UI would need improvement making it clear that some tests are not meant to run, perhaps also changing the status to `ignore` or `neutral`.
> [skip-ci] TMT: keep PR-label independent tests

- GOVERNANCE.md
- MAINTAINERS.md
- OWNERS
Many of the people in OWNERS no longer contribute to the project, so clean the file and restrict to those who are still active. Alongside this, add our core maintainers who have merge authority on all repos.
Governance is a simple link to the Podman governance model, and MAINTAINERS.md mirrors the new OWNERS.
> Add MAINTAINERS.md and Governance, update OWNERS

- .golangci.yml
1. Remove some unused exclusions, document the used ones.
2. ~~Add `errorlint`, fix found warnings ("Use `%w` to format errors").~~ (dropped)
> .golangci.yml: simplify

- .github/labeler.yml
This was added earlier as part of PR label-based triggering of Packit jobs. But we decided not to go ahead with that approach, thus keeping only a single set of tests. This file should've been removed during the revert, but better late than never.
Ref: https://github.com/containers/skopeo/pull/2558
FWIW, this yaml file doesn't work by itself without the corresponding GHA which was never included. So, this yaml config was pretty much a NOP anyway.
> GHA: remove .github/labeler.yaml

- cmd/skopeo/proxy.go
- integration/proxy_test.go
The original model the idea here is the proxy centralizes verification of things like digest. However in practice, this causes reading to be seriously awkward; ref
https://github.com/containers/containers-image-proxy-rs/issues/79
Also, I have a project to implement a registry frontend to `containers-storage:` and a core problem with `GetBlob` right now is it *requires* the blob size up front even though the underlying Go logic doesn't.
Moving to a "raw" interface solves that.
> proxy: Add GetRawBlob

- .packit.yaml
F40 is now EOL and all current Fedora releases have Go 1.23. So, we're safe to re-enable fedora-all.
> [skip-ci] Packit: set fedora-all after F40 EOL

- version/version.go
This bumps c/common and c/image to v0.63.0 and v5.35.0, respectively.  It then bumps Skopeo to v1.19.0, and then to the next dev version, v1.20.0-dev.
c/storage has already been bumped to v1.58.0, with this PR, we will line up with Podman v5.5.0
There are way more updates from the c/common and c/image bumps than I anticipated.....
> Bump to c/common 0.63.0, c/image 5.35.0, Skopeo to v1.19.0, v1.20.0-dev

- systemtest/helpers.bash
Previously, internal CI gating tests sometimes fail because the required registry container image only supports x86_64.  Update to the `2.8.2` image tag with support for all primary architectures.
> [release-1.14] Support CI testing on non-x86_64

- systemtest/helpers.bash
Previously, internal CI gating tests sometimes fail because the required registry container image only supports x86_64.  Update to the `2.8.2` image tag with support for all primary architectures.
> [release-1.11] Support CI testing on non-x86_64

- cmd/skopeo/unshare_linux.go
Some container storage operations (e.g., mounting the home directory for containers/storage) require CAP_SYS_ADMIN.
> unshare: Add CAP_SYS_ADMIN to needed capabilities

- contrib/cirrus/runner.sh
- integration/check_test.go
- integration/copy_test.go
... to decrease impact of flakes.
---
We now see a network error at least once in most PRs in this repo, it’s becoming too much of a hassle.
I intend to keep expanding the scope of this PR as long as CI keeps showing new classes of avoidable failures.
> Add --retry to test operations that tend to fail

- Makefile
- hack/sqlite_tag.sh
- rpm/skopeo.spec
Dynamically link sqlite3 when installed, the main motivation is that we
reduce the podman binary size with that. I see about 3.3 MB savings.
But also dynamically linking it means if there a vulnerabilities only
the sqlite3 distro package needs updating and we don't have to make a
new podman release with the vendored update.
> dynamically link sqlite3

- GOVERNANCE.md
- MAINTAINERS.md
Tweak the Governance and Maintainers files to align them with those in Buildah and Podman.
For reference, here's the Buildah PR that started this effort: https://github.com/containers/buildah/pull/6124
> Tweak Governance and Maintainers for alignment

- .packit.yaml
Doesn't currently work for go packages anyway.
> Packit: disable osh-diff-scan

- MAINTAINERS.md
This PR updates Neil Smith's GitHub username from 'Neil-Smith' to 'actionmancan' in the MAINTAINERS.md file.
- Changed GitHub username from 'Neil-Smith' to 'actionmancan'
- Fixed GitHub URL from https://github.com/Neil-Smith to https://github.com/actionmancan
- Corrected column alignment for consistent formatting
- Maintains Neil Smith's role as Community Manager
- No functional changes, just updating the GitHub handle
Does this PR introduce a user-facing change?
```release-note
None
```
Signed-off-by: G A Neil Smith <nesmith@redhat.com>
> Update Neil Smith's GitHub username in MAINTAINERS.md

- systemtest/001-basic.bats
Unfortunately on a number of occasions, Skopeo has been released officially with a `-dev` suffix in the version number.  Assist in catching this mistake at release time by the addition of a simple conditional test.  Note that it must be positively enabled by a magic env. var. before executing the system tests.
Original PR: https://github.com/containers/skopeo/pull/2631
(AI was used to help craft this PR)
> [release-1.14] Add conditional release-checking system test

- cmd/skopeo/copy.go
- cmd/skopeo/inspect.go
- cmd/skopeo/login.go
- cmd/skopeo/logout.go
- cmd/skopeo/sync.go
- cmd/skopeo/utils.go
- cmd/skopeo/utils_test.go
This will allow adding other signing options in a single place.
Also, use a consistent ordering for `AddFlagSet` — it turns out one ordering is better than the other.
Should not change behavior, apart from some help texts.
> Consolidate options shared between copy and sync to sharedCopyOptions

- version/version.go
Since Skopeo now has the same versions of the c/* libraries as Buildah v1.41 and Podman v5.6, bumping it to v1.20.0 to go along with those for RHEL 9.7/10.1.    Once this merges, I'll tag and create a release branch.
The second commit is to 1.21.0-dev, to get the main branch back onto a dev version.
> Bump to v1.20.0 then v1.21.0-dev

- version/version.go
This branch is utilized for RHEL releases and therefore should never ever represent a `-dev` development release.  Bump the version number to account for the change.
Resolves: RHEL-97102
> [release-1.9] Bump to release version 1.9.4

- MAINTAINERS.md
Since I am a community manager for podman. I would like to add myself to the community manager role, as per https://github.com/containers/podman/blob/main/GOVERNANCE.md#maintainers-file, specifically "The MAINTAINERS.md file in the main Podman repository is used for project-spanning roles, including Core Maintainer and Community Manager."
https://github.com/containers/podman/blob/main/MAINTAINERS.md
> Adding mohanboddu as community manager to MAINTAINERS.md

- integration/copy_test.go
- systemtest/050-signing.bats
Currently, if a key is not found, the GPG mechanism reports
> Invalid GPG signature: {$GoStructDump}
while the Sequoia one reports
> $keyFingerprint was not found
Accept both.
This is split from https://github.com/containers/skopeo/pull/2645 , to make it easier to sequence the PRs: First this PR, then https://github.com/containers/image/pull/2876 (which will pass tests), and then https://github.com/containers/skopeo/pull/2645 .
> Update tests to work with the Sequoia c/image backend

- Makefile
- cmd/skopeo/main.go
- go.mod
- integration/signing_test.go
- integration/sync_test.go
@jnovy @lsm5 please note the “Rely on Go-maintained commit value instead of handling that ourselves” commit, I might well be missing something.
> Update to Go1.24
