hack/.vendor-helpers.sh

Instead of only checking dependencies of the `"main"` packages, include also test dependencies of all subpackages of the project, and their transitive dependencies.

Do not clean test-only dependencies from vendor packages

---

docker.go

fix invalid credentials error

---

vendor/github.com/mtrmac/gpgme/data.go
vendor/github.com/mtrmac/gpgme/gpgme.go

This contains:
- https://github.com/mtrmac/gpgme/commit/3a6e25fe9998e44270053bd2562dae117c614efd , a straightforward build fix
- https://github.com/mtrmac/gpgme/commit/c2302e1b78cadab51d73d0250a672f09e4830134 , fixing an important memory management error first noticed on CentOS 7.

Update mtrmac/gpgme vendor to fix build on CentOS 7

---

man1/skopeo.1

Signed-off-by: Jhon Honce <jhonce@redhat.com>

Add disclaimer to man page for sign-* commands

---

vendor/github.com/mtrmac/gpgme/callbacks.go
vendor/github.com/mtrmac/gpgme/data.go
vendor/github.com/mtrmac/gpgme/go_gpgme.c
vendor/github.com/mtrmac/gpgme/go_gpgme.h
vendor/github.com/mtrmac/gpgme/gpgme.go

See https://github.com/proglottis/gpgme/pull/7 for the full discussion.

Rerun hack/vendor.sh to pick up gpgme changes

---

docker/docker_utils.go
integration/signing_test.go

See individual commit descriptions.

Random cleanups

---

integration/fixtures/image.manifest.json
integration/fixtures_info_test.go
integration/signing_test.go
signature/docker_test.go
signature/fixtures_info_test.go
signature/mechanism_test.go
signature/signature_test.go

@mtrmac PTAL I somehow missed this one also

signature: remove pkg fixtures

---

cmd/skopeo/copy.go
directory/directory.go
docker/docker_image.go
docker/docker_image_src.go
docker/utils/fixtures/v2list.manifest.json
docker/utils/manifest.go
docker/utils/manifest_test.go
openshift/openshift.go
types/types.go

add mimetypes

---

signature/fixtures/policy.json
signature/json.go
signature/json_test.go
signature/policy_config.go
signature/policy_config_test.go
signature/policy_types.go

There are a few outstanding FIXMEs, but otherwise this should be pretty feature-complete, if anyone wanted to review this now.
Depends on / includes #54, I will rebase as necessary.

Add policy configuration data structures, construction and parsing

---

signature/policy_types.go

This was supposed to be the last update to #55, no idea how I failed to push it. Sorry.

Update a comment for prInsecureAcceptAnything

---

version/version.go

bump version for a new release, I will merge this, tag, push and release here on github

bump to v0.1.12

---

version/version.go

bump to v0.1.13-dev

---

docker/utils/manifest.go

taking care of https://github.com/projectatomic/skopeo/pull/71/files#r64399468

Remove ManifestMIMETypes

---

vendor/github.com/mtrmac/gpgme/go_gpgme.h
vendor/github.com/mtrmac/gpgme/gpgme.go

i.e. to pick up https://github.com/proglottis/gpgme/pull/10
Fixes #80.

Rerun hack/vendor.sh to fix build on 32-bit systems

---

version/version.go

bump to v0.1.13

---

version/version.go

bump v0.1.14-dev

---

signature/json_test.go

This was created for https://github.com/mtrmac/skopeo/tree/go142 but is useful independently.

Another random cleanup

---

README.md

README.md: fix examples

---

image/image.go

I have stared at that code often enough now that at least some minimal documentation seems warranted.
This does not really go into why duplicate layers can happen or why it is worth supporting that; the code originates from https://github.com/docker/docker/commit 504e67b867865a2835e8002c01087a2cfd7bfd0e , which does not explain either.
(This will conflict with other PRs, notably #98 . I will rebase as necessary.)

Add minimal comments to fixManifestLayers

---

cmd/skopeo/copy.go
directory/directory.go
docker/docker_image_src.go
image/image.go
openshift/openshift.go
types/types.go

expose blob size

---

Dockerfile
Makefile
integration/check_test.go
integration/copy_test.go
integration/openshift.go
integration/signing_test.go
integration/utils.go

See the individual commits for detailed comments.

Add Atomic registry integration tests

---

cmd/skopeo/fixtures/.gitignore
cmd/skopeo/fixtures/corrupt.signature
cmd/skopeo/fixtures/image.manifest.json
cmd/skopeo/fixtures/image.signature
cmd/skopeo/fixtures/pubring.gpg
cmd/skopeo/fixtures/secring.gpg
cmd/skopeo/fixtures/trustdb.gpg
cmd/skopeo/inspect.go
cmd/skopeo/main.go
cmd/skopeo/main_test.go
cmd/skopeo/signing.go
cmd/skopeo/signing_test.go

This demonstrates command handler unit tests based on #16 .
Note: depends on #16, do not merge as is.

Signing unit tests

---

README.md

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

README: fewer build steps

---

LICENSE
README.md

For consistency with other OSS projects and to make our legal lives so much easier  :-)
Signed-off-by: Doug Davis <dug@us.ibm.com>

Move to Apache 2 license

---

cmd/skopeo/copy.go
cmd/skopeo/inspect.go
cmd/skopeo/layers.go
vendor/github.com/containers/image/directory/directory.go
vendor/github.com/containers/image/directory/directory_dest.go
vendor/github.com/containers/image/directory/directory_src.go
vendor/github.com/containers/image/docker/docker_image_src.go
vendor/github.com/containers/image/image/image.go
vendor/github.com/containers/image/manifest/manifest.go
vendor/github.com/containers/image/signature/policy_eval_signedby.go
vendor/github.com/containers/image/types/types.go

Depends on https://github.com/containers/image/pull/24 .

Update for changed images.Type API

---

cmd/skopeo/layers.go
cmd/skopeo/utils.go
vendor/github.com/containers/image/directory/directory_dest.go
vendor/github.com/containers/image/directory/directory_src.go
vendor/github.com/containers/image/docker/docker_image.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/docker/docker_image_src.go
vendor/github.com/containers/image/docker/docker_utils.go
vendor/github.com/containers/image/oci/oci_dest.go
vendor/github.com/containers/image/openshift/openshift.go

Vendor containers/image

---

cmd/skopeo/layers.go
vendor/github.com/containers/image/directory/directory_transport.go
vendor/github.com/containers/image/directory/explicitfilepath/path.go
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/docker/docker_transport.go
vendor/github.com/containers/image/docker/policyconfiguration/naming.go
vendor/github.com/containers/image/oci/oci_transport.go
vendor/github.com/containers/image/openshift/openshift.go
vendor/github.com/containers/image/openshift/openshift_transport.go
vendor/github.com/containers/image/signature/json.go
vendor/github.com/containers/image/signature/policy_config.go
vendor/github.com/containers/image/signature/policy_eval.go
vendor/github.com/containers/image/signature/policy_types.go
vendor/github.com/containers/image/types/types.go

This demonstrates https://github.com/containers/image/pull/33 .

Use transport abstraction and transport-abstracted references

---

cmd/skopeo/copy.go
cmd/skopeo/delete.go
cmd/skopeo/inspect.go
cmd/skopeo/layers.go
cmd/skopeo/main.go
cmd/skopeo/signing.go
man1/skopeo.1

Should, at least partially, address #134 and #137.

Improve man page and --help

---

.gitignore

… and reorder it alphabetically.

Add the generated man page to .gitignore

---

README.md

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

minor cleanup for build issues related to the manual

---

Makefile

Clean up dependencies.
Signed-off-by: Mike Brown <brownwm@us.ibm.com>

fix dependencies

---

Makefile

Adds `make debug`.. allows a developer to build a source debuggable version of skopeo. For example, using delve.
Signed-off-by: Mike Brown <brownwm@us.ibm.com>

add a source debug build

---

cmd/skopeo/copy.go
cmd/skopeo/delete.go
cmd/skopeo/layers.go
cmd/skopeo/utils.go
vendor/github.com/containers/image/directory/directory_src.go
vendor/github.com/containers/image/directory/directory_transport.go
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/docker/docker_image.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/docker/docker_image_src.go
vendor/github.com/containers/image/docker/docker_transport.go
vendor/github.com/containers/image/image/image.go
vendor/github.com/containers/image/manifest/manifest.go
vendor/github.com/containers/image/oci/oci_transport.go
vendor/github.com/containers/image/openshift/openshift.go
vendor/github.com/containers/image/openshift/openshift_transport.go
vendor/github.com/containers/image/signature/policy_config.go
vendor/github.com/containers/image/types/types.go

This updates API usage for https://github.com/containers/image/pull/64 ; I will re-vendor after it is merged.

Vendor in API changes from https://github.com/containers/image/pull/64

---

vendor/github.com/containers/image/oci/oci_dest.go
vendor/github.com/containers/image/oci/oci_transport.go

Vendors in https://github.com/containers/image/pull/67

vendor containers/image for oci dest fix

---

cmd/skopeo/inspect.go
cmd/skopeo/layers.go
cmd/skopeo/utils.go
vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/directory/directory_dest.go
vendor/github.com/containers/image/directory/directory_src.go
vendor/github.com/containers/image/directory/directory_transport.go
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/docker/docker_image.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/docker/docker_image_src.go
vendor/github.com/containers/image/docker/docker_transport.go
vendor/github.com/containers/image/image/image.go
vendor/github.com/containers/image/manifest/manifest.go
vendor/github.com/containers/image/oci/oci_dest.go
vendor/github.com/containers/image/oci/oci_transport.go
vendor/github.com/containers/image/openshift/openshift.go
vendor/github.com/containers/image/openshift/openshift_transport.go
vendor/github.com/containers/image/types/types.go

This pulls in https://github.com/containers/image/pull/73 and updates the users of the API to conform.

Update for mtrmac/image:api-changes

---

hack/vendor.sh
vendor/github.com/containers/image/manifest/manifest.go
vendor/github.com/containers/image/oci/oci_dest.go
vendor/github.com/opencontainers/image-spec/LICENSE
vendor/github.com/opencontainers/image-spec/specs-go/descriptor.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest_list.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
vendor/github.com/opencontainers/image-spec/specs-go/version.go
vendor/github.com/opencontainers/image-spec/specs-go/versioned.go

Vendors in https://github.com/containers/image/pull/71 and opencontainers/image-spec

vendor containers/image and OCI/image-spec

---

cmd/skopeo/layers.go
vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/directory/directory_dest.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/oci/oci_dest.go
vendor/github.com/containers/image/openshift/openshift.go
vendor/github.com/containers/image/types/types.go

Vendors https://github.com/containers/image/pull/70

vendor containers/image for PutBlob returns

---

Makefile

As a new contributor I required this change to my environment.

Fix selinux perms in Makefile binary build

---

cmd/skopeo/layers.go
vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/directory/directory_dest.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/docker/docker_image_src.go
vendor/github.com/containers/image/image/image.go
vendor/github.com/containers/image/manifest/manifest.go
vendor/github.com/containers/image/oci/layout/oci_dest.go
vendor/github.com/containers/image/oci/layout/oci_transport.go
vendor/github.com/containers/image/openshift/openshift.go
vendor/github.com/containers/image/transports/transports.go
vendor/github.com/containers/image/types/types.go
vendor/github.com/davecgh/go-spew/spew/bypass.go
vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
vendor/github.com/davecgh/go-spew/spew/config.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go

vendor containers/image, OCI/image-spec

---

vendor/github.com/containers/image/image/image.go

vendor containers/image to fix RH

---

vendor/github.com/containers/image/oci/layout/oci_dest.go

vendor containers/image#84

---

integration/copy_test.go
integration/fixtures/policy.json
vendor/github.com/containers/image/openshift/openshift.go
vendor/github.com/containers/image/openshift/openshift_transport.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go

Vendor containers/image#81
Fix #189 
Fix #194 

Change atomic URI

---

cmd/skopeo/layers.go
vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/directory/directory_dest.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/docker/lookaside.go
vendor/github.com/containers/image/image/docker_schema1.go
vendor/github.com/containers/image/image/docker_schema2.go
vendor/github.com/containers/image/image/image.go
vendor/github.com/containers/image/oci/layout/oci_dest.go
vendor/github.com/containers/image/openshift/openshift-copies.go
vendor/github.com/containers/image/openshift/openshift.go
vendor/github.com/containers/image/types/types.go

Updates for https://github.com/containers/image/pull/90 .

Vendor after merging mtrmac/image:api-changes and update API use

---

cmd/skopeo/copy.go
hack/vendor.sh
vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/openshift/openshift.go
vendor/github.com/containers/image/openshift/openshift_transport.go
vendor/gopkg.in/cheggaaa/pb.v1/.travis.yml
vendor/gopkg.in/cheggaaa/pb.v1/LICENSE
vendor/gopkg.in/cheggaaa/pb.v1/README.md
vendor/gopkg.in/cheggaaa/pb.v1/format.go
vendor/gopkg.in/cheggaaa/pb.v1/pb.go
vendor/gopkg.in/cheggaaa/pb.v1/pb_appengine.go
vendor/gopkg.in/cheggaaa/pb.v1/pb_nix.go
vendor/gopkg.in/cheggaaa/pb.v1/pb_solaris.go
vendor/gopkg.in/cheggaaa/pb.v1/pb_win.go
vendor/gopkg.in/cheggaaa/pb.v1/pb_x.go
vendor/gopkg.in/cheggaaa/pb.v1/pool.go
vendor/gopkg.in/cheggaaa/pb.v1/pool_win.go
vendor/gopkg.in/cheggaaa/pb.v1/pool_x.go
vendor/gopkg.in/cheggaaa/pb.v1/reader.go
vendor/gopkg.in/cheggaaa/pb.v1/runecount.go
vendor/gopkg.in/cheggaaa/pb.v1/termios_bsd.go
vendor/gopkg.in/cheggaaa/pb.v1/termios_nix.go

@mtrmac PTAL since this is vendoring other stuff not related to progress bars.

add progress bars during copy

---

vendor/github.com/containers/image/copy/copy.go

fix containers/image progress

---

vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/docker/docker_client.go
version/version.go

Close #197 
* Vendor containers/image
* Bump to v0.1.16
* Bump again to v0.1.17-dev

Bump v0.1.16

---

vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/types/types.go

skopeo side PR for https://github.com/containers/image/pull/113
@mtrmac PTAL, I'll revendor after https://github.com/containers/image/pull/113's merged

vendor containers/image for DockerAuthConfig

---

vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/types/types.go

vendor containers/iamge for DockerRegistryUserAgent

---

README.md

Add instructions to build skopeo on OSX

Add OSX instructions to Readme

---

default-policy.json

Add insecureAcceptAnything to default docker-daemon transport

---

hack/vendor.sh
vendor/github.com/containers/image/docker/docker_client.go

revendor containers/image

---

vendor/github.com/containers/image/docker/docker_client.go

docker: fix ping routine

---

README.md

README.md: add dependencies management tips

---

cmd/skopeo/copy.go
cmd/skopeo/delete.go
cmd/skopeo/inspect.go
cmd/skopeo/layers.go
cmd/skopeo/main.go
cmd/skopeo/utils.go
completions/bash/skopeo
docs/skopeo.1.md
hack/vendor.sh
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/types/types.go
vendor/github.com/docker/go-connections/nat/nat.go
vendor/github.com/docker/go-connections/nat/parse.go
vendor/github.com/docker/go-connections/sockets/inmem_socket.go
vendor/github.com/docker/go-connections/sockets/sockets.go
vendor/github.com/docker/go-connections/sockets/sockets_unix.go
vendor/github.com/docker/go-connections/sockets/sockets_windows.go
vendor/github.com/docker/go-connections/sockets/tcp_socket.go
vendor/github.com/docker/go-connections/tlsconfig/certpool_go17.go
vendor/github.com/docker/go-connections/tlsconfig/certpool_other.go
vendor/github.com/docker/go-connections/tlsconfig/config.go

Based on #263 
@mtrmac @rhatdan PTAL

cmd: per command tls flags

---

vendor/github.com/containers/image/signature/mechanism.go

Last piece before the release
Fix https://github.com/projectatomic/skopeo/issues/268

provide better error when key not found

---

hack/vendor.sh
vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest_list.go
vendor/github.com/opencontainers/image-spec/specs-go/versioned.go

update opencontainers/image-spec to v1.0.0-rc3

---

vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/image/memory.go
vendor/github.com/containers/image/signature/mechanism.go
vendor/github.com/containers/storage/storageversion/version_lib.go
vendor/github.com/mtrmac/gpgme/gpgme.go

bump c/image

---

vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/docker/docker_image_src.go

vendor containers/image@d23efe9c5a1f332a025f0a4b1078dde201ce8365
fix https://bugzilla.redhat.com/show_bug.cgi?id=1413987

docker: fix registry authentication issues

---

vendor/github.com/containers/image/image/docker_schema2.go

oci: fix config conversion from docker v2s2

---

vendor/github.com/containers/image/docker/daemon/daemon_dest.go
vendor/github.com/containers/image/docker/docker_client.go

Pulling in latest c/image changes for a new release
@mtrmac PTAL

vendor c/image@c1893ff40cd5faa2e8badd04678441d7d27441a8

---

version/version.go

I'll tag `v0.1.18` the following commit https://github.com/projectatomic/skopeo/commit/b08008c5b21ec869f40f8eb2a6f2e8687984bf95
@mtrmac PTAL

New release: v0.1.18

---

vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/docker/daemon/daemon_src.go
vendor/github.com/containers/image/pkg/compression/compression.go

Signed-off-by: Aleksa Sarai <asarai@suse.de>

[donotmerge] vendor: update to c/i@copy-obey-destination-compression

---

cmd/skopeo/copy.go
cmd/skopeo/delete.go
cmd/skopeo/utils.go
vendor/github.com/containers/image/directory/directory_transport.go
vendor/github.com/containers/image/docker/daemon/daemon_transport.go
vendor/github.com/containers/image/docker/docker_transport.go
vendor/github.com/containers/image/manifest/manifest.go
vendor/github.com/containers/image/oci/layout/oci_transport.go
vendor/github.com/containers/image/openshift/openshift_transport.go
vendor/github.com/containers/image/signature/policy_config.go
vendor/github.com/containers/image/storage/storage_transport.go
vendor/github.com/containers/image/transports/alltransports/alltransports.go
vendor/github.com/containers/image/transports/transports.go

PR to validate containers/image#216

vendor c/image for pluggable transports

---

integration/copy_test.go
vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/manifest/manifest.go

@mtrmac added a test also for https://github.com/containers/image/pull/246

fix copy panic on http response with tls-verify true

---

integration/copy_test.go
integration/fixtures/policy.json
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/docker/docker_image.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/docker/docker_image_src.go

This pulls in https://github.com/containers/image/pull/255 , and adds an integration test.

Add support for the X-Registry-Supports-Signatures API extension

---

cmd/skopeo/inspect.go

Some registries may choose to block the "list all tags" endpoint for
performance or other reasons. In this case we should still allow an
inspect which will not include the "tag list" in the output.
Signed-off-by: Phil Estes <estesp@gmail.com>

Allow inspect to work even if tag list blocked

---

version/version.go

Will tag `v0.1.19` on https://github.com/projectatomic/skopeo/commit/62e3747a114bfaf23a2ff3583f7f73eff8bf9711

New release: v0.1.19

---

version/version.go

will tag https://github.com/projectatomic/skopeo/commit/e802625b7cb7f4af9ab77bd2be9eb441ff2f28a2 as v0.1.20

New release v0.1.20

---

docs/skopeo.1.md

Signed-off-by: Michael Hrivnak <mhrivnak@redhat.com>

Fixes a typo in the Name field

---

version/version.go

I'll tag https://github.com/runcom/skopeo-1/commit/0b7315460126b8945fd53f9318a65d7cc8796af1 as v0.1.21
/cc @rhatdan

Bump release 0.1.21

---

vendor.conf
vendor/github.com/ostreedev/ostree-go/pkg/glibobject/gobject.go

This will fix the compiler issues.

Vendor in ostree fixes

---

cmd/skopeo/copy.go
cmd/skopeo/delete.go
cmd/skopeo/inspect.go
cmd/skopeo/main.go
docs/skopeo.1.md

Remove docker references whereever possible

---

vendor.conf
vendor/github.com/containers/image/transports/transports.go
vendor/github.com/containers/image/vendor.conf
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/commit.go

@rhatdan @mtrmac PTAL vendors https://github.com/containers/image/pull/287

vendor c/image for ListNames in transports pkg

---

cmd/skopeo/copy.go
cmd/skopeo/delete.go
cmd/skopeo/inspect.go
docs/skopeo.1.md

Also specify container-storage as a valid transport

Give more useful help when explaining usage

---

version/version.go

will tag https://github.com/projectatomic/skopeo/commit/5d24b67f5eeeca348966adb412d8119837faa1c2 as v0.1.22

Cut v0.1.22

---

vendor.conf
vendor/github.com/containers/image/docker/tarfile/dest.go
vendor/github.com/containers/image/docker/tarfile/src.go
vendor/github.com/containers/image/docker/tarfile/types.go
vendor/github.com/containers/image/vendor.conf

This is similar to #377, bumping the tag but the only code changes are in unrelated packages…
@rhatdan FYI

Update to image-spec v1.0.0 and revendor

---

version/version.go

Will tag 1bbd87f4356fed4f21b860b18c50dbe72027b1a0 as v0.1.23
@rhatdan @mtrmac PTAL

Bump v0.1.23 for OCIv1 support and bug fixes

---

.travis.yml
Makefile
hack/darwin_tag.sh
hack/travis_osx.sh

I have updated the README with build instructions that currently work on OSX. And added some travis fu to try and build the project on OSX...

Adds automated build for OSX

---

Makefile
hack/darwin_tag.sh
hack/travis_osx.sh

Fixes #383
Signed-off-by: Ed Robinson <ed.robinson@reevoo.com>

Fix `make install` on OSX

---

vendor.conf
vendor/github.com/containers/image/README.md
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/image/oci.go
vendor/github.com/containers/image/oci/archive/oci_dest.go
vendor/github.com/containers/image/oci/archive/oci_src.go
vendor/github.com/containers/image/oci/archive/oci_transport.go
vendor/github.com/containers/image/oci/layout/oci_dest.go
vendor/github.com/containers/image/ostree/ostree_dest.go
vendor/github.com/containers/image/ostree/ostree_transport.go
vendor/github.com/containers/image/transports/alltransports/alltransports.go
vendor/github.com/containers/image/types/types.go
vendor/github.com/containers/image/vendor.conf
vendor/github.com/docker/docker-credential-helpers/LICENSE
vendor/github.com/docker/docker-credential-helpers/README.md
vendor/github.com/docker/docker-credential-helpers/client/client.go
vendor/github.com/docker/docker-credential-helpers/client/command.go
vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go
vendor/github.com/docker/docker-credential-helpers/credentials/error.go
vendor/github.com/docker/docker-credential-helpers/credentials/helper.go
vendor/github.com/docker/docker-credential-helpers/credentials/version.go
vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.c
vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.go
vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.h
vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_go18.go
vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_non_go18.go
vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.c
vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go
vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.h

Ref https://github.com/containers/image/pull/339

Add docker-credential-helpers dependency.

---

README.md

Try two, hopefully without merge issues from github.  Touching up a few typos in the README.md as noted in a review earlier today.

Touch up a few tpyos

---

README.md
docs/skopeo.1.md

Changes up the verbiage a bit, especially the opening stanza.

Spruce up the README.md a bit

---

integration/copy_test.go
vendor/github.com/containers/image/manifest/manifest.go
vendor/github.com/containers/image/ostree/ostree_dest.go
vendor/github.com/containers/image/ostree/ostree_transport.go
vendor/github.com/containers/image/types/types.go

Vendor in mtrmac/image:manifest-list-hotfix

---

vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/docker/docker_image_src.go
vendor/github.com/containers/image/image/oci.go
vendor/github.com/containers/image/oci/archive/oci_dest.go
vendor/github.com/containers/image/oci/layout/oci_dest.go
vendor/github.com/containers/image/oci/layout/oci_src.go
vendor/github.com/containers/image/oci/layout/oci_transport.go
vendor/github.com/containers/image/ostree/ostree_dest.go
vendor/github.com/containers/image/pkg/tlsclientconfig/tlsclientconfig.go
vendor/github.com/containers/image/signature/signature.go
vendor/github.com/containers/image/types/types.go

Vendor in latest containers/image

containers/image: vendor

---

version/version.go

Will tag https://github.com/runcom/skopeo-1/commit/dd2c3e3a8e33b849f3625f4f56fa229c76448629 as `v0.1.24`

Bump v0.1.24

---

README.md
docs/skopeo.svg

[do not merge yet] add logo :)

---

README.md
docs/skopeo.1.md

Fix spelling mistakes
Fix reference to garbage collection on the container registry server.

Cleanup skopeo man page and README.md

---

vendor/github.com/containers/image/ostree/ostree_dest.go
vendor/github.com/containers/image/ostree/ostree_src.go
vendor/github.com/containers/image/ostree/ostree_transport.go

Include last changes in the ostree driver.

vendor: revendor containers/image

---

vendor/github.com/containers/image/docker/archive/src.go
vendor/github.com/containers/image/docker/archive/transport.go
vendor/github.com/containers/image/docker/daemon/daemon_src.go
vendor/github.com/containers/image/docker/tarfile/src.go
vendor/github.com/containers/image/transports/alltransports/ostree.go
vendor/github.com/containers/image/transports/alltransports/ostree_stub.go

Adds support to handle compressed docker-archive files
Signed-off-by: umohnani8 <umohnani@redhat.com>

Vendor in latest containers/image

---

version/version.go

Bump 0.1.29

---

version/version.go

Bump 0.1.30

---

cmd/skopeo/copy.go

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

cmd/skopeo: show full help on 'copy' with no args

---

Makefile

Makefile: make vendor a .PHONY target

---

cmd/skopeo/inspect.go

Instead, use `DockerReference()` to obtain the repository name (which also makes it work for other transports that support Docker references), and a check for `docker.Transport` + the newly introduced `docker.GetRepositoryTags`.
This will allow dropping `docker.Image` from `containers/image`, and maybe even all of `ImageReference.NewImage` (forcing callers to think about manifest lists, among other things).
@runcom PTAL (non-urgent), primarly WDYT about eventually dropping the `NewImage` interface and forcing callers to deal with `ImageSource` and `image.FromSource` / `FromUnparsedImage` themselves? Or maybe wrap that in something like `c/image/image.FromReference(types.ImageReference)` so that callers continue to need only one call instead of two?

Stop using docker.Image

---

vendor.conf

vendor.conf: remove unused github.com/golang/glog

---

Makefile

Add support for using podman in testing skopeo

---

Dockerfile
hack/travis_osx.sh

Signed-off-by: Antonio Murdaca <runcom@linux.com>

fix golint

---

Makefile

This makes #535 work for me. 🌷 @rhatdan , @mtrmac

Enable build in podman

---

vendor.conf
vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/storage/storage_image.go
vendor/github.com/containers/image/tarball/tarball_src.go
version/version.go

Mainly picking https://github.com/containers/image/pull/553

release v0.1.34

---

Makefile
hack/btrfs_installed_tag.sh
hack/ostree_tag.sh

Copy the build tag scripts from Buildah

Allow building without btrfs and ostree

---

Makefile

`make all` builds the skopeo binary in a container, but does not build the skopeo man-page in the container in spite of the fact that go-md2man was installed.
This PR consistently builds the skopeo binary and man-page in a container.

Makefile: Build docs in a container

---

Makefile
docs/skopeo-copy.1.md
docs/skopeo-delete.1.md
docs/skopeo-inspect.1.md
docs/skopeo-manifest-digest.1.md
docs/skopeo-standalone-sign.1.md
docs/skopeo-standalone-verify.1.md
docs/skopeo.1.md

split up skopeo man pages

---

vendor.conf
vendor/github.com/containers/image/copy/copy.go
vendor/github.com/containers/image/pkg/blobinfocache/memory.go
vendor/github.com/containers/image/version/version.go
vendor/github.com/containers/storage/images.go
vendor/github.com/containers/storage/layers.go
vendor/github.com/containers/storage/lockfile.go
vendor/github.com/containers/storage/lockfile_unix.go
vendor/github.com/containers/storage/store.go

Vendor in latest containers/storage and image

---

Dockerfile.build

build image updated to ubuntu:18.10

---

cmd/skopeo/main.go
cmd/skopeo/utils.go
integration/copy_test.go
integration/fixtures/registries.conf
vendor.conf
vendor/github.com/BurntSushi/toml/COPYING
vendor/github.com/BurntSushi/toml/README.md
vendor/github.com/BurntSushi/toml/decode.go
vendor/github.com/BurntSushi/toml/decode_meta.go
vendor/github.com/BurntSushi/toml/doc.go
vendor/github.com/BurntSushi/toml/encode.go
vendor/github.com/BurntSushi/toml/lex.go
vendor/github.com/BurntSushi/toml/parse.go
vendor/github.com/BurntSushi/toml/type_fields.go
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/docker/docker_image.go
vendor/github.com/containers/image/docker/docker_image_src.go
vendor/github.com/containers/image/docker/docker_transport.go
vendor/github.com/containers/image/docs/containers-registries.conf.5.md
vendor/github.com/containers/image/docs/containers-transports.5.md
vendor/github.com/containers/image/pkg/sysregistriesv2/system_registries_v2.go
vendor/github.com/containers/image/registries.conf

This PR adds the registry mirror integration test to skopeo.
- Update toml to latest release
- Update containers/image

Add skopeo registry mirror integration tests

---

docs/skopeo.1.md

Signed-off-by: Hunor Csomortáni <csomh@redhat.com>

Fix typo on the main man page

---

Dockerfile
Makefile
hack/make/test-system
systemtest/001-basic.bats
systemtest/010-inspect.bats
systemtest/020-copy.bats
systemtest/030-local-registry-tls.bats
systemtest/040-local-registry-auth.bats
systemtest/050-signing.bats
systemtest/helpers.bash
systemtest/run-tests

systemtest - new set of BATS tests for RHEL8 gating

---

README.md

README: Clarify use of `libbtrfs-dev` on Ubuntu

---

systemtest/040-local-registry-auth.bats

Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>

systemtest/040-local-registry-auth.bats: fix a typo

---

Makefile

Go 1.13.x isn't sensitive to the `GO111MODULE` environment variable
causing `make binary-local` to not use the vendored sources in
`./vendor`.  Force builds of module-supporting go versions to use the
vendored sources by setting `-mod=vendor`.
Verified in a `fedora:rawhide` container.

go build: use `-mod=vendor` for go >= 1.11.x

---

.travis.yml

Travis: use go 1.12.x

---

go.mod
go.sum
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/pkg/docker/config/config.go
vendor/github.com/containers/image/pkg/sysregistriesv2/system_registries_v2.go
vendor/github.com/containers/image/version/version.go
vendor/modules.txt

vendor github.com/containers/image@v3.0.0

---

cmd/skopeo/inspect.go

Skip the `NewImage()` step if we're just inspecting the raw manifest, so that if the image tag or digest being inspected resolves to a manifest list, the local arch/OS combination don't need to be found in it to avoid an error.

inspect --raw: skip the NewImage() step

---

completions/bash/skopeo

Fixes for https://bugzilla.redhat.com/show_bug.cgi?id=1701373.
Ran locally with `shellcheck -a`.
Tested the updated script locally and it continues working as before.
@rhatdan @mtrmac PTAL

Shellcheck fixes

---

version/version.go

@mtrmac @rhatdan @TomSweeneyRedHat PTAL

Release v0.1.40

---

systemtest/010-inspect.bats

When --raw is provided, can inspect show the raw manifest list, w/o
requiring any particular platform to be present, this test case is
used for make sure inspect command w/ --raw option works well for
container image is different from current platform arch.
$ bats -f "diff platform" systemtest/010-inspect.bats
✓ inspect: image manifest list w/ diff platform
1 test, 0 failures
Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>

systemtest: inpsect container image different from current platform arch

---

docs/skopeo-copy.1.md

Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>

Fix typos in doc for image encryption

---

README.md

Signed-off-by: Daniel Strobusch <1847260+dastrobu@users.noreply.github.com>

document installation via apk on alpine

---

docs/skopeo-sync.1.md

Sync: Add example with repository

---

systemtest/helpers.bash

PR 834 broke Fedora gating tests, because "--runtime runc"
doesn't work so well on Rawhide. Let's try to be smarter
about when we add that override.

Update on #834: force runc only when cgroupsv1

---

go.mod
go.sum
vendor/github.com/containers/image/v5/copy/copy.go
vendor/github.com/containers/image/v5/docker/docker_client.go
vendor/github.com/containers/image/v5/version/version.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
vendor/modules.txt

Bump containers/image to v5.4.3

---

docs/skopeo-copy.1.md

container-storage => containers-storage

fix copy doc

---

docs/skopeo-copy.1.md
docs/skopeo-delete.1.md
docs/skopeo-inspect.1.md
docs/skopeo-list-tags.1.md
docs/skopeo-login.1.md
docs/skopeo-logout.1.md
docs/skopeo-standalone-sign.1.md
docs/skopeo-standalone-verify.1.md
docs/skopeo-sync.1.md
docs/skopeo.1.md

Help users discover additonal man pages by completing
SEE ALSO section.

Add links to configuration man pages

---

README.md
docs/skopeo.1.md

Update skopeo readme and man page

---

install.md

add very short line in docs
```
brew install skopeo
```

there is a brew formula for skopeo

---

go.mod
go.sum
vendor/modules.txt

vendor github.com/containers/common v0.14.0

---

docs/skopeo-copy.1.md

Updating skopeo docs based on doc changes discussed in https://github.com/containers/buildah/pull/2271
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

update enc/dec docs to be consistent with buildah

---

Makefile
nix/default.nix
nix/nixpkgs.json

Switch from nix `channel:nixpkgs-unstable` to `channel:nixos-20.03` for better stability.
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

nix run -f channel:nixos-20.03

---

cmd/skopeo/copy.go
cmd/skopeo/delete.go
cmd/skopeo/layers.go
cmd/skopeo/list_tags.go
cmd/skopeo/sync.go

Applies retry on more skopeo subcommands.
Related issue: https://github.com/containers/skopeo/issues/918

Retry on skopeo subcommands

---

Dockerfile.build

19.10 is EOL since July 17, 2020

Dockerfile.build: Upgrade to Ubuntu 20.04

---

Makefile
contrib/skopeoimage/README.md

We want to use containers/podman for podman repo and make clean was blowing up.

A couple of minor code cleanups.

---

cmd/skopeo/inspect.go
cmd/skopeo/inspect/output.go

Make InspectOutput an external object

---

cmd/skopeo/copy.go
cmd/skopeo/delete.go
cmd/skopeo/inspect.go
cmd/skopeo/layers.go
cmd/skopeo/list_tags.go
cmd/skopeo/sync.go
cmd/skopeo/utils.go
go.mod
vendor/github.com/containers/common/pkg/retry/retry.go
vendor/modules.txt

Use c/common retry package

---

docs/skopeo-copy.1.md

Fixes #730 .
(I’m honestly not sure that this is necessary, and the wording feels a bit clumsy. Suggestions are very welcome.)

Add an extra clarification to skopeo-copy(1)

---

docs/skopeo.1.md

Add oci-archive to transport list, and link to the authoritative man page

---

Dockerfile.build

fix build in docker container

---

CONTRIBUTING.md
cmd/skopeo/inspect.go
cmd/skopeo/sync.go
cmd/skopeo/utils.go
docs/skopeo-copy.1.md
integration/copy_test.go
integration/sync_test.go

Fix problems found by codespell

---

version/version.go

Signed-off-by: Frank Ederveen <frank.ederveen@gmail.com>

Added SemVer tag compare to sync and a 'noop' option.

---

install.md

@TomSweeneyRedHat @rhatdan PTAL

include OBS install steps for CentOS

---

.travis.yml
Dockerfile
integration/copy_test.go

Travis: bump go to 1.15.x

---

install.md

install: make commands copy-pasteable

---

cmd/skopeo/inspect.go
completions/bash/skopeo
docs/skopeo-inspect.1.md
vendor/github.com/containers/common/pkg/report/camelcase/LICENSE.md
vendor/github.com/containers/common/pkg/report/camelcase/README.md
vendor/github.com/containers/common/pkg/report/camelcase/camelcase.go
vendor/github.com/containers/common/pkg/report/doc.go
vendor/github.com/containers/common/pkg/report/template.go
vendor/github.com/containers/common/pkg/report/validate.go
vendor/github.com/containers/common/pkg/report/writer.go
vendor/modules.txt

Fixes https://github.com/containers/skopeo/issues/642

Add --format option to skopeo inspect

---

.travis.yml
install.md

Update install docs

---

install.md

@TomSweeneyRedHat @rhatdan PTAL

update debian/ubuntu docs

---

integration/copy_test.go
integration/fixtures/policy.json

This <s>vendors in https://github.com/containers/image/pull/1075 and</s> adds an end-to-end smoke test.

Tests for remapIdentity

---

systemtest/020-copy.bats

When copying to an OCI layout destination, forcing zstd compression, check that the manifest correctly describes the type of the layer blob.

020-copy.bats: check that we set the manifest type correctly

---

systemtest/010-inspect.bats
systemtest/020-copy.bats
systemtest/030-local-registry-tls.bats
systemtest/040-local-registry-auth.bats
systemtest/050-signing.bats
systemtest/060-delete.bats
systemtest/helpers.bash
systemtest/make-noarch-manifest

Cherry pick of #1169 to get gatin tests happy.
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1914884

Fix gating test in release-1.2 port #1169

---

version/version.go

Bumping to v1.2.2
After this merges and a release is cut, I'll spin a separate PR to put this branch on 1.2.3-dev.

Skopeo v1.2.2

---

version/version.go

Bump the release-1.2 branch to 1.2.3-dev

Bump to v1.2.3-dev

---

Dockerfile.build
integration/copy_test.go
integration/fixtures/policy.json

Resolves: gh#174
@rhatdan @vrothberg

Dockerfile.build: switch to fedora:latest

---

.cirrus.yml

Cirrus: Initial implementation support for GCP VMs

---

go.mod
go.sum
vendor/github.com/containers/image/v5/copy/copy.go
vendor/github.com/containers/image/v5/oci/layout/oci_src.go
vendor/github.com/containers/image/v5/storage/storage_image.go
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt

vendor c/image v5.11.1

---

cmd/skopeo/copy.go
cmd/skopeo/sync.go
cmd/skopeo/utils.go
cmd/skopeo/utils_test.go
completions/bash/skopeo
docs/skopeo-sync.1.md
integration/copy_test.go
integration/sync_test.go
integration/utils.go

Signed-off-by: Brendan Aye <brendan.aye@t-mobile.com>

Added format parameter to sync command

---

Makefile
nix/default-arm64.nix
nix/default.nix
nix/nixpkgs.json

- Bugfix `make nixpkgs` which pin with branch `nixos-21.05`
- Code lint with `nixpkgs-fmt`
- Code sync between x86\_64 and aarch64
Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

Update nix pin with `make nixpkgs`

---

.cirrus.yml
Dockerfile
hack/make/.validate

Ref: https://github.com/containers/image/pull/1272 and https://github.com/containers/skopeo/issues/1282
Fixes #1282

Fix automation re: master->main rename

---

Dockerfile

Ref: [quay.io build failure](https://quay.io/repository/skopeo/ci/build/3992488d-ab5b-430a-856e-10a382c4b7cf)

[CI:DOCS] Workaround quay.io image build failure

---

docs/skopeo-copy.1.md
docs/skopeo-delete.1.md
docs/skopeo-list-tags.1.md
docs/skopeo-sync.1.md

Add --retry-times to markdown docs

---

.cirrus.yml

Cirrus: Add vendor + tree status check

---

.cirrus.yml
contrib/cirrus/runner.sh

Cirrus: Rename cross -> osx task, add cross task.

---

version/version.go

Bump the release branch version to the next numbered dev.

[release-1.3] Bump to Skopeo v1.3.2-dev

---

CONTRIBUTING.md

:wave: skopeo maintainers!
This updates the contribution instructions to use go modules vendoring instead of `vndr`.
I hope I interpreted the intention correctly as I stumbled into this while trying to open my first PR (trying to do that according to documentation!).

CONTRIBUTING: update vendoring instructions

---

version/version.go

@vrothberg @mtrmac @rhatdan PTAL. v1.3.1 is already released.

Bump main version to v1.4.0-dev

---

cmd/skopeo/inspect.go
cmd/skopeo/list_tags_test.go
cmd/skopeo/login.go
cmd/skopeo/sync.go
cmd/skopeo/unshare.go
cmd/skopeo/utils.go

… as shown by Visual Studio Code.
Should not change behavior.
See individual commit messages for details.

Fix staticcheck-reported problems

---

.github/workflows/multi-arch-build.yaml

This mirrors changes from
https://github.com/containers/buildah/pull/3381

[CI:DOCS] Multi-arch image build: Daily version-tag push

---

integration/openshift.go

… so that we terminate with the full context and pointing at the relevant code, instead of relying on the overall test suite timeout.

Add timeouts when waiting on OpenShift or the registry to start

---

Makefile

@mtrmac @TomSweeneyRedHat PTAL

vendor-in-container: update to golang:1.16

---

version/version.go

[release-1.4] Bump to v1.4.1

---

version/version.go

@rhatdan @mtrmac @TomSweeneyRedHat PTAL.

1.5.1 bump

---

contrib/skopeoimage/stable/Dockerfile
contrib/skopeoimage/testing/Dockerfile
contrib/skopeoimage/upstream/Dockerfile

Fixes: #1492
@vrothberg @mtrmac @rhatdan @TomSweeneyRedHat @cevich PTAL

use fedora:latest in contrib/skopeoimage/*/Dockerfile

---

Makefile
cmd/skopeo/proxy.go
integration/proxy_test.go

Run codespell on code

---

go.mod
go.sum
vendor/github.com/containers/common/pkg/flag/flag.go
vendor/modules.txt

Update vendor of containers/common

---

go.mod
go.sum
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt

Bump version of containers/image and containers/common

---

version/version.go

Highlights:
- A new sif: transport
- New options --multi-arch, --preserve-digests, --sign-passphrase-file
---
- Use a dynamic temp dir for test
- Add an option to allow copying image indexes alone
- proxy: Add a GetFullConfig method
- proxy: Also bump compatible semver
- Add option to preserve digests on copy
- Run codespell on code
- prompt-less signing via passphrase file
- add a SIF systemtest
- Merge pull request #1550 from vrothberg/sif-test
- Improve the documentation of the argument to (skopeo inspect)
- Document where various fields of (skopeo inspect) come from
- Improve the documentation of boolean flags

Release v1.6.0

---

systemtest/010-inspect.bats

… per review comments in https://github.com/containers/skopeo/pull/1575 .

Improve a comment in the 010-inspect.bats test

---

systemtest/010-inspect.bats

This a backport of #1572 to fix CI on this branch.

[release-1.3] Don't expect the config blob to be listed in (skopeo inspect)

---

cmd/skopeo/signing_test.go

...added in github.com/stretchr/testify 1.7.1.

Use assert.ErrorContains

---

docs/skopeo-delete.1.md

Signed-off-by: Masatake YAMATO <yamato@redhat.com>

delete non-existent option in the cmdline example

---

install.md

@TomSweeneyRedHat @vrothberg @mtrmac @rhatdan PTAL

[CI:DOCS] install.md: remove Kubic package info for Ubuntu

---

install.md

[CI:DOCS] install.md: include distro package info links

---

version/version.go

… primarily to sync the c/common version with Podman 4.2 (assuming it updates as well.)
- [CI:DOCS] Cirrus: Use the latest imgts container
- Cirrus: Update CI VM images to match podman CI
- Bump github.com/containers/common from 0.49.0 to 0.49.1

Release 1.9.2

---

docs/skopeo-copy.1.md
docs/skopeo-sync.1.md

Point at --all in the --preserve-digests option documentation

---

cmd/skopeo/copy.go
cmd/skopeo/sync.go
cmd/skopeo/utils.go
systemtest/020-copy.bats

warn users about --dest-compress and --dest-decompress misuse

---

default.yaml

Fix documentation in the default registries.d content.

---

contrib/skopeoimage/README.md

Fixes: https://github.com/containers/podman/issues/15989

[CI:DOCS] Add quay-description update reminder

---

cmd/skopeo/inspect.go
cmd/skopeo/sync.go
go.mod
go.sum
integration/check_test.go
integration/copy_test.go
integration/sync_test.go
systemtest/040-local-registry-auth.bats
vendor/github.com/containers/image/v5/docker/docker_client.go
vendor/github.com/containers/image/v5/docker/docker_image.go
vendor/github.com/containers/image/v5/docker/docker_image_dest.go
vendor/github.com/containers/image/v5/docker/docker_image_src.go
vendor/github.com/containers/image/v5/docker/errors.go
vendor/github.com/containers/image/v5/oci/archive/oci_src.go
vendor/github.com/containers/image/v5/oci/layout/oci_src.go
vendor/github.com/containers/image/v5/oci/layout/oci_transport.go
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt

This updates expected test output for https://github.com/containers/image/pull/1299 .
<s>Still outstanding: Figure out what kinds of “list tags” failures we care about, and how to detect that.</s>

Update for https://github.com/containers/image/pull/1299

---

cmd/skopeo/proxy.go
integration/proxy_test.go

In some code I'm writing I want to be able to cleanly test if an image exists, as distinguished from other errors like authentication problems, network flakes etc.
As best I can tell, the containers/image abstraction doesn't offer a clean way to do this.
For now, I chose the route of adding the ugly string error matching here for the two cases I care about (docker v2s2 registry and oci directories), so my Rust code can operate in terms of clean `Option<Image>`.

proxy: Add `OpenImageOptional`

---

cmd/skopeo/proxy.go

ref: https://github.com/ostreedev/ostree-rs-ext/pull/396

proxy: Add LayerInfoJSON API

---

cmd/skopeo/proxy.go

This is a complementary fix for
https://github.com/coreos/rpm-ostree/issues/4213
Basically in the case of `oci-archive` we have a temporary directory that needs cleanup.

proxy: Ensure images are closed when proxy is shutting down

---

.cirrus.yml

Ref: https://github.com/containers/skopeo/pull/1850

[release-1.4] Cirrus: Drop OSX task

---

.cirrus.yml

Ref: https://github.com/containers/skopeo/pull/1850

[release-1.6] Cirrus: Drop OSX  task

---

README.md
contrib/skopeoimage/README.md
docs/skopeo.1.md
integration/utils.go

Touch up a few issues with language in the project to make it more inclusive.
Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

Touch up conscious language issues

---

README.md

Touch up a few left over comments from #1871
Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

[CI:DOCS] Fix up language in README

---

cmd/skopeo/sync.go
cmd/skopeo/sync_test.go
go.mod

Signed-off-by: Renovate Bot <bot@renovateapp.com>

Update module gopkg.in/yaml.v2 to v3

---

cmd/skopeo/list_tags_test.go
cmd/skopeo/proxy.go
cmd/skopeo/sync.go
cmd/skopeo/utils_test.go
integration/check_test.go
integration/copy_test.go
integration/openshift.go
integration/procutils.go
integration/proxy_test.go
integration/utils.go

… when running all linters. Mostly just trivial cleanups.

Fix some golangci-lint-reported nits

---

go.mod
go.sum
vendor/github.com/containers/image/v5/docker/body_reader.go
vendor/github.com/containers/image/v5/docker/docker_client.go
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt

... to include an unexpected EOF workaround.
(I have also created the `release-1.11` branch.)

[release-1.11] Update to c/image 5.24.1

---

.github/renovate.json5

Ref: https://github.com/containers/automation/pull/128

[CI:DOCS] Renovate: c/common rule moved to defaults

---

version/version.go

As the title says.  To ready for RHEL 8.8/9.2

[release-1.11] Bump to v1.11.1

---

docs/skopeo-sync.1.md

Corrected typo (rep**oo**sitories) and updated the description to read better.

Corrected Skopeo-Sync Documentation

---

README.md

... per https://github.com/containers/skopeo/issues/1940 .

Make the installation instructions more prominent in README.md

---

version/version.go

… for #1948 .
Cc: @lsm5 @jnovy

[release-1.11] Release 1.11.2

---

version/version.go

… for #1949 .
Cc: @lsm5 @jnovy

[release-1.6] Release 1.6.3

---

docs/skopeo-copy.1.md
docs/skopeo-sync.1.md

Emphasize the semantics of --preserve-digests a tiny bit

---

version/version.go

As the title says.  In preparation for RHEL 8.9/9.3
Once merged, I'll create a tag, release, and release branch.

Bump to v1.13.0

---

go.mod
go.sum
vendor/modules.txt

[release-1.13] Bump c/common to v0.55.2

---

Makefile
install.md

~~The rationale behind this pull request is that it simplifies the process of building and testing by utilizing the RISCV-64 SBC.~~
Add information about cross-compilation in install.md

Improve the docs with cross-compilation info

---

docs/skopeo.1.md

Reported in https://github.com/containers/skopeo/issues/2061 .

Fix a man page link

---

install.md

Add Arch Linux installation & build instruction in `install.md`.
Signed-off-by: Hanxing Wang <hxstarrys@gmail.com>

DOCS: Update to add Arch Linux in install.md

---

integration/copy_test.go

... because the tests are assuming a v2s2 image, but as of Fedora 39, the image uses the OCI format.
See e.g. https://api.cirrus-ci.com/v1/task/6504550402621440/logs/integration.log for the test failures this is trying to fix.

Freeze the fedora-minimal image reference at Fedora 38

---

integration/copy_test.go

... because the tests are assuming a v2s2 image, but as of Fedora 39, the image uses the OCI format.
This should fix failing tests. Originally from #2280 , thanks to a backport in #2293 by Tom.

[release-1.3] Freeze the fedora-minimal image reference at Fedora 38

---

go.mod
go.sum
integration/copy_test.go
vendor/github.com/containers/image/v5/copy/progress_bars.go
vendor/github.com/containers/image/v5/copy/single.go
vendor/github.com/containers/image/v5/directory/directory_dest.go
vendor/github.com/containers/image/v5/directory/directory_src.go
vendor/github.com/containers/image/v5/directory/directory_transport.go
vendor/github.com/containers/image/v5/docker/docker_client.go
vendor/github.com/containers/image/v5/docker/docker_image.go
vendor/github.com/containers/image/v5/docker/docker_image_dest.go
vendor/github.com/containers/image/v5/docker/docker_image_src.go
vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go
vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go
vendor/github.com/containers/image/v5/docker/registries_d.go
vendor/github.com/containers/image/v5/openshift/openshift_src.go
vendor/github.com/containers/image/v5/ostree/ostree_dest.go
vendor/github.com/containers/image/v5/ostree/ostree_src.go
vendor/github.com/containers/image/v5/storage/storage_dest.go
vendor/github.com/containers/image/v5/storage/storage_image.go
vendor/github.com/containers/image/v5/storage/storage_reference.go
vendor/github.com/containers/image/v5/storage/storage_src.go
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt
version/version.go

Addresses CVE-2024-3727
https://issues.redhat.com/browse/RHEL-35443
https://issues.redhat.com/browse/RHEL-35440

[release-1.15] CVE-2024-3727, bump to v1.15.1

---

.cirrus.yml
contrib/cirrus/runner.sh

Also fix a problem with a dnf command that no longer works on f41

update CI images to f41

---

systemtest/010-inspect.bats

https://github.com/containers/image/pull/2595 will change it.
This should work with current c/image; https://github.com/containers/skopeo/pull/2441 tests whether it will work with the proposed change.

Update an expected error message

---

cmd/skopeo/copy_test.go
cmd/skopeo/list_tags_test.go
cmd/skopeo/sync_test.go
cmd/skopeo/utils.go

- Exit with a non-zero exit code
- Actually report the error we detected
- Write usage to stderr
Fixes #2468.

Fix handling of errorShouldDisplayUsage

---

ROADMAP.md

Closes: https://issues.redhat.com/browse/RUN-2450

ROADMAP: new file

---

cmd/skopeo/proxy.go
integration/openshift.go

fix some function names in comment

chore: fix some function names in comment

---

.cirrus.yml
Makefile
contrib/cirrus/runner.sh
hack/btrfs_tag.sh
rpm/skopeo.spec

c/storage no longer uses either of these.
FYI @jnovy : spec file changes

Stop setting unused build tags

---

CONTRIBUTING.md

[CI:DOCS] CONTRIBUTING.md: Update communication channels

---

README.md

Rebased on #2596 . Can remove it if we decide against it.
I guess similar procedure and concerns as https://github.com/containers/podman/pull/26087 .

[CI:DOCS] README.md: Add openssf passing badge

---

.packit.yaml

See individual commits. These only relate to PR jobs. Downstream jobs not affected.

Packit: re-enable ELN and CentOS Stream jobs on PRs
